// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class APP_IFOOD_EVENTOS
    {
        public int COD_EVENTO { get; set; }
        public DateTime? CREATE_AT { get; set; }
        public string? FULL_CODE { get; set; }
        public string? CODE { get; set; }
        public string? ORDER_ID { get; set; }
        public string? ID { get; set; }
        public int? COD_PEDIDO_IFOOD { get; set; }
        public int COD_EMPRESA { get; set; }
        public int COD_ORGANIZACAO { get; set; }

        public virtual GE_EMPRESAS COD_EMPRESANavigation { get; set; } = null!;
        public virtual GE_ORGANIZACAO COD_ORGANIZACAONavigation { get; set; } = null!;
        public virtual APP_IFOOD_PEDIDOS? COD_PEDIDO_IFOODNavigation { get; set; }
    }
}