// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class APP_IFOOD_PEDIDO_ITENS
    {
        public int COD_ITEM { get; set; }
        public int COD_PEDIDO_IFOOD { get; set; }
        public string? EXTERNAL_CODE { get; set; }
        public decimal TOTAL_PRICE { get; set; }
        public decimal UNIT_PRICE { get; set; }
        public int QUANTITY { get; set; }
        public decimal PRICE { get; set; }
        public string? NAME { get; set; }
        public string? ID { get; set; }
        public int NUM_INDEX { get; set; }

        public virtual APP_IFOOD_PEDIDOS COD_PEDIDO_IFOODNavigation { get; set; } = null!;
    }
}