// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class APP_IFOOD_PEDIDOS
    {
        public APP_IFOOD_PEDIDOS()
        {
            APP_IFOOD_EVENTOS = new HashSet<APP_IFOOD_EVENTOS>();
            APP_IFOOD_PEDIDO_ITENS = new HashSet<APP_IFOOD_PEDIDO_ITENS>();
        }

        public int COD_PEDIDO { get; set; }
        public DateTime DTA_ATUALIZACAO { get; set; }
        public string? ID { get; set; }
        public string? DISPLAY_ID { get; set; }
        public string? MERCHANT_NAME { get; set; }
        public string? MERCHANT_ID { get; set; }
        public DateTime? CREATE_AT { get; set; }
        public decimal TOTAL_BENEFITS { get; set; }
        public decimal TOTAL_DELIVERYFEE { get; set; }
        public decimal TOTAL_ORDERAMOUNT { get; set; }
        public decimal TOTAL_SUBTOTAL { get; set; }
        public decimal TOTAL_ADDITIONALFEES { get; set; }
        public string? CUSTOMER_NAME { get; set; }
        public int CUSTOMER_ORDERS_COUNT_ON_MERCHANT { get; set; }
        public string? CUSTOMER_ID { get; set; }
        public string? CUSTOMER_PHONE_NUMBER { get; set; }
        public string? ORDERTYPE { get; set; }
        public string? DES_JSON { get; set; }
        public int COD_EMPRESA { get; set; }
        public int COD_ORGANIZACAO { get; set; }
        public string? CUSTOMER_DOCUMENT_NUMBER { get; set; }

        public virtual GE_EMPRESAS COD_EMPRESANavigation { get; set; } = null!;
        public virtual GE_ORGANIZACAO COD_ORGANIZACAONavigation { get; set; } = null!;
        public virtual ICollection<APP_IFOOD_EVENTOS> APP_IFOOD_EVENTOS { get; set; }
        public virtual ICollection<APP_IFOOD_PEDIDO_ITENS> APP_IFOOD_PEDIDO_ITENS { get; set; }
    }
}