// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class APP_IFOOD_AUTORIZACAO
    {
        public APP_IFOOD_AUTORIZACAO()
        {
            APP_IFOOD_TOKEN = new HashSet<APP_IFOOD_TOKEN>();
        }

        public int COD_AUTORIZACAO { get; set; }
        public int COD_EMPRESA { get; set; }
        public string? USER_CODE { get; set; }
        public string? AUTORIZATION_CODE_VERIFIER { get; set; }
        public string? VERIFICATION_URL_COMPLETE { get; set; }
        public int? EXPIRE_IN { get; set; }
        public DateTime? DTA_EXPIRACAO { get; set; }
        public bool TIP_ATIVO { get; set; }
        public string? AUTHORIZATION_CODE { get; set; }
        public int? COD_USUARIO { get; set; }
        public string? MERCHANT_ID { get; set; }

        public virtual GE_EMPRESAS COD_EMPRESANavigation { get; set; } = null!;
        public virtual GE_USUARIOS? COD_USUARIONavigation { get; set; }
        public virtual ICollection<APP_IFOOD_TOKEN> APP_IFOOD_TOKEN { get; set; }
    }
}