// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class APP_IFOOD_TOKEN
    {
        public int COD_TOKEN { get; set; }
        public int COD_AUTORIZACAO { get; set; }
        public string? DES_TOKEN { get; set; }
        public string? TYPE { get; set; }
        public int? EXPIRE_IN { get; set; }
        public DateTime DTA_EMISSAO { get; set; }
        public DateTime? DTA_EXPIRACAO { get; set; }

        public virtual APP_IFOOD_AUTORIZACAO COD_AUTORIZACAONavigation { get; set; } = null!;
    }
}