// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class CA_ABERTURA_FECHAMENTO
    {
        public CA_ABERTURA_FECHAMENTO()
        {
            CA_MOVIMENTOS = new HashSet<CA_MOVIMENTOS>();
            FT_NOTAS = new HashSet<FT_NOTAS>();
        }

        public int COD_ABERTURA { get; set; }
        public int COD_FRENTE_CAIXA { get; set; }
        public int COD_EMPRESA { get; set; }
        public DateTime? DTA_ABERTURA { get; set; }
        public DateTime? DTA_FECHAMENTO { get; set; }
        public int? COD_USUARIO_ABERTURA { get; set; }
        public decimal VLR_ABERTURA { get; set; }
        public decimal VLR_FECHAMENTO { get; set; }
        public string? DES_GUID { get; set; }
        public int? COD_USUARIO_FECHAMENTO { get; set; }

        public virtual GE_EMPRESAS COD_EMPRESANavigation { get; set; } = null!;
        public virtual GE_CADASTRO_FRENTE_CAIXA COD_FRENTE_CAIXANavigation { get; set; } = null!;
        public virtual GE_USUARIOS? COD_USUARIO_ABERTURANavigation { get; set; }
        public virtual GE_USUARIOS? COD_USUARIO_FECHAMENTONavigation { get; set; }
        public virtual ICollection<CA_MOVIMENTOS> CA_MOVIMENTOS { get; set; }
        public virtual ICollection<FT_NOTAS> FT_NOTAS { get; set; }
    }
}