// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class CA_MOVIMENTOS
    {
        public int COD_MOVIMENTO { get; set; }
        public int COD_ABERTURA { get; set; }
        public int COD_TIPO { get; set; }
        public DateTime DTA_MOVIMENTO { get; set; }
        public decimal VLR_MOVIMENTO { get; set; }
        public int COD_USUARIO { get; set; }
        public int COD_EMPRESA { get; set; }
        public string? DES_HISTORICO { get; set; }
        public string? DES_GUID { get; set; }

        public virtual CA_ABERTURA_FECHAMENTO COD_ABERTURANavigation { get; set; } = null!;
        public virtual GE_EMPRESAS COD_EMPRESANavigation { get; set; } = null!;
        public virtual CA_TIPOS_MOVIMENTOS COD_TIPONavigation { get; set; } = null!;
        public virtual GE_USUARIOS COD_USUARIONavigation { get; set; } = null!;
    }
}