// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class CE_CONFIGURADOR_VERSOES
    {
        public CE_CONFIGURADOR_VERSOES()
        {
            CE_PRODUTOS_CONFIGURADOS = new HashSet<CE_PRODUTOS_CONFIGURADOS>();
        }

        public int COD_VERSAO { get; set; }
        public int? COD_CONFIGURADOR { get; set; }
        public string? DES_VERSAO { get; set; }
        public DateTime? DTA_CRIACAO { get; set; }
        public bool? TIP_ATIVO { get; set; }

        public virtual CE_CONFIGURADOR? COD_CONFIGURADORNavigation { get; set; }
        public virtual ICollection<CE_PRODUTOS_CONFIGURADOS> CE_PRODUTOS_CONFIGURADOS { get; set; }
    }
}