// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class CE_INVENTARIO_SPED_ITENS
    {
        public int COD_ITEM { get; set; }
        public int COD_INVENTARIO { get; set; }
        public int NUM_SEQUENCIA { get; set; }
        public int COD_PRODUTO { get; set; }
        public decimal QTD_PRODUTO { get; set; }
        public decimal VLR_UNITARIO { get; set; }
        public decimal VLR_TOTAL { get; set; }
        public int? COD_UNIDADE_MEDIDA { get; set; }
        public int? COD_PESSOA { get; set; }
        public decimal VLR_TOTAL_IR { get; set; }
        public int IND_ESTOQUE_TERCEIROS { get; set; }

        public virtual CE_INVENTARIO_SPED COD_INVENTARIONavigation { get; set; } = null!;
        public virtual PS_PESSOAS? COD_PESSOANavigation { get; set; }
        public virtual CE_PRODUTOS COD_PRODUTONavigation { get; set; } = null!;
        public virtual GE_UNIDADE_MEDIDA? COD_UNIDADE_MEDIDANavigation { get; set; }
    }
}