// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class CE_INVENTARIO_SPED
    {
        public CE_INVENTARIO_SPED()
        {
            CE_INVENTARIO_SPED_ITENS = new HashSet<CE_INVENTARIO_SPED_ITENS>();
        }

        public int COD_INVENTARIO { get; set; }
        public DateTime DTA_GERACAO { get; set; }
        public DateTime DTA_REFERENCIA { get; set; }
        public decimal VLR_TOTAL_INVENTARIO { get; set; }
        public int COD_USUARIO { get; set; }
        public int COD_EMPRESA { get; set; }

        public virtual GE_EMPRESAS COD_EMPRESANavigation { get; set; } = null!;
        public virtual GE_USUARIOS COD_USUARIONavigation { get; set; } = null!;
        public virtual ICollection<CE_INVENTARIO_SPED_ITENS> CE_INVENTARIO_SPED_ITENS { get; set; }
    }
}