// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class CE_INVENTARIOS_PRODUTOS_HISTORICOS
    {
        public int COD_HISTORICO { get; set; }
        public int COD_INVENTARIO_PRODUTO { get; set; }
        public DateTime DTA_HISTORICO { get; set; }
        public decimal? QTD_INVENTARIO { get; set; }
        public int COD_USUARIO { get; set; }

        public virtual CE_INVENTARIOS_PRODUTOS COD_INVENTARIO_PRODUTONavigation { get; set; } = null!;
        public virtual GE_USUARIOS COD_USUARIONavigation { get; set; } = null!;
    }
}