// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class CE_ITENS_NOTAS_ORDENS_ATENDIDAS
    {
        public int COD_RELACAO_ITENS { get; set; }
        public int COD_ITEM_NOTA { get; set; }
        public int COD_ITEM_ORDEM_COMPRA { get; set; }
        public decimal QTD_ATENDIDA { get; set; }

        public virtual CE_NOTAS_ITENS COD_ITEM_NOTANavigation { get; set; } = null!;
        public virtual CO_ORDENS_ITENS COD_ITEM_ORDEM_COMPRANavigation { get; set; } = null!;
    }
}