// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class CE_INVENTARIOS
    {
        public CE_INVENTARIOS()
        {
            CE_INVENTARIOS_PRODUTOS = new HashSet<CE_INVENTARIOS_PRODUTOS>();
        }

        public int COD_INVENTARIO { get; set; }
        public int NUM_INVENTARIO { get; set; }
        public string DES_INVENTARIO { get; set; } = null!;
        public DateTime DTA_CRIACAO { get; set; }
        public int COD_USUARIO { get; set; }
        public bool TIP_ENCERRADO { get; set; }
        public DateTime? DTA_ENCERRADO { get; set; }
        public string? DES_OBS { get; set; }
        public int? COD_USUARIO_ENCERRAMENTO { get; set; }
        public int COD_EMPRESA { get; set; }
        public DateTime? DTA_REFERENCIA { get; set; }
        public bool TIP_ZERAR_PRODUTOS { get; set; }
        public bool TIP_ZERAR_PRODUTOS_NAO_CONTADOS { get; set; }
        public int? IND_REGRA_ENCERRAMENTO { get; set; }

        public virtual GE_EMPRESAS COD_EMPRESANavigation { get; set; } = null!;
        public virtual GE_USUARIOS COD_USUARIONavigation { get; set; } = null!;
        public virtual GE_USUARIOS? COD_USUARIO_ENCERRAMENTONavigation { get; set; }
        public virtual ICollection<CE_INVENTARIOS_PRODUTOS> CE_INVENTARIOS_PRODUTOS { get; set; }
    }
}