// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class CE_MOVIMENTOS_ESTOQUES
    {
        public CE_MOVIMENTOS_ESTOQUES()
        {
            CE_INVENTARIOS_PRODUTOS = new HashSet<CE_INVENTARIOS_PRODUTOS>();
            CE_NOTAS_ITENS = new HashSet<CE_NOTAS_ITENS>();
            FT_NOTAS_ITENS = new HashSet<FT_NOTAS_ITENS>();
        }

        public int COD_MOVIMENTO_ESTOQUE { get; set; }
        public int COD_EMPRESA { get; set; }
        public int COD_ORGANIZACAO { get; set; }
        public DateTime DTA_MOVIMENTO { get; set; }
        public int? COD_PESSOA { get; set; }
        public int? NUM_DOCUMENTO { get; set; }
        public int COD_TIPO_DOCUMENTO { get; set; }
        public int IND_ENTRADA_SAIDA { get; set; }
        public decimal? QTD_MOVIMENTO { get; set; }
        public decimal? VLR_UNITARIO { get; set; }
        public decimal? QTD_ESTOQUE_ANTERIOR { get; set; }
        public bool? TIP_EXCLUIDO { get; set; }
        public int COD_USUARIO { get; set; }
        public bool? TIP_ATUALIZA_ESTOQUE { get; set; }
        public int COD_PRODUTO_ALMOXARIFADO { get; set; }
        public int? COD_PRODUTO { get; set; }
        public decimal? QTD_ESTOQUE_ATUAL { get; set; }
        public decimal? VLR_CUSTO_MEDIO { get; set; }
        public decimal? VLR_CUSTO_REAL { get; set; }
        public decimal? VLR_CUSTO_REPOSICAO { get; set; }
        public string? DES_OBSERVACAO { get; set; }

        public virtual GE_EMPRESAS COD_EMPRESANavigation { get; set; } = null!;
        public virtual GE_ORGANIZACAO COD_ORGANIZACAONavigation { get; set; } = null!;
        public virtual PS_PESSOAS? COD_PESSOANavigation { get; set; }
        public virtual CE_PRODUTOS? COD_PRODUTONavigation { get; set; }
        public virtual CE_PRODUTO_ALMOXARIFADOS COD_PRODUTO_ALMOXARIFADONavigation { get; set; } = null!;
        public virtual SW_TIPOS_DOCUMENTOS COD_TIPO_DOCUMENTONavigation { get; set; } = null!;
        public virtual GE_USUARIOS COD_USUARIONavigation { get; set; } = null!;
        public virtual ICollection<CE_INVENTARIOS_PRODUTOS> CE_INVENTARIOS_PRODUTOS { get; set; }
        public virtual ICollection<CE_NOTAS_ITENS> CE_NOTAS_ITENS { get; set; }
        public virtual ICollection<FT_NOTAS_ITENS> FT_NOTAS_ITENS { get; set; }
    }
}