// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class CE_NOTA_AVISOS
    {
        public int COD_AVISO { get; set; }
        public int COD_NOTA { get; set; }
        public bool TIP_NAO_ALERTAR { get; set; }
        public string DES_AVISO { get; set; } = null!;

        public virtual CE_NOTAS COD_NOTANavigation { get; set; } = null!;
    }
}