// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class CE_NOTAS_PENDENCIAS_FORNECEDOR
    {
        public int COD_PENDENCIA_FORNECEDOR { get; set; }
        public int COD_NOTA { get; set; }
        public string? NUM_CNPJ_CPF { get; set; }
        public string? DES_NOME { get; set; }
        public string? NUM_IE { get; set; }
        public string? COD_CEP { get; set; }
        public int? COD_IBGE_CIDADE { get; set; }
        public string? DES_ENDERECO { get; set; }
        public string? DES_BAIRRO { get; set; }
        public int? NUM_ENDERECO { get; set; }
        public string? DES_EMAIL { get; set; }
        public string? NUM_TELEFONE { get; set; }
        public string? DES_COMPLEMENTO { get; set; }
        public string? DES_FANTASIA { get; set; }

        public virtual CE_NOTAS COD_NOTANavigation { get; set; } = null!;
    }
}