// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class CE_NOTAS_ITENS
    {
        public CE_NOTAS_ITENS()
        {
            CE_ITENS_NOTAS_ORDENS_ATENDIDAS = new HashSet<CE_ITENS_NOTAS_ORDENS_ATENDIDAS>();
            CE_NOTAS_PENDENCIAS_PRODUTOS = new HashSet<CE_NOTAS_PENDENCIAS_PRODUTOS>();
            FT_DEVOLUCOES = new HashSet<FT_DEVOLUCOES>();
        }

        public int COD_ITEM { get; set; }
        public int COD_NOTA { get; set; }
        public int COD_EMPRESA { get; set; }
        public int COD_ORGANIZACAO { get; set; }
        public int? NUM_SEQUENCIA { get; set; }
        public int? COD_PRODUTO { get; set; }
        public int? COD_UNIDADE_MEDIDA { get; set; }
        public int? COD_OPERACAO_FISCAL { get; set; }
        public decimal? QTD_PRODUTO { get; set; }
        public decimal? VLR_UNITARIO { get; set; }
        public decimal? VLR_MERCADORIA { get; set; }
        public decimal? VLR_TOTAL { get; set; }
        public decimal? VLR_DESCONTO { get; set; }
        public decimal? VLR_FRETE { get; set; }
        public decimal? VLR_SEGURO { get; set; }
        public decimal? VLR_DESPESAS { get; set; }
        public decimal? VLR_BASE_ST { get; set; }
        public decimal? VLR_ST { get; set; }
        public decimal? PER_MVA { get; set; }
        public decimal? VLR_BASE_ICMS { get; set; }
        public decimal? VLR_ICMS { get; set; }
        public decimal? PER_ICMS { get; set; }
        public decimal? VLR_BASE_IPI { get; set; }
        public decimal? VLR_IPI { get; set; }
        public decimal? PER_IPI { get; set; }
        public decimal? VLR_BASE_PIS { get; set; }
        public decimal? VLR_PIS { get; set; }
        public decimal? PER_PIS { get; set; }
        public decimal? VLR_BASE_COFINS { get; set; }
        public decimal? VLR_COFINS { get; set; }
        public decimal? PER_COFINS { get; set; }
        public decimal? VLR_FCP_ST { get; set; }
        public decimal? VLR_BASE_ST_RETIDO { get; set; }
        public decimal? PER_ST_RETIDO { get; set; }
        public decimal? VLR_ST_RETIDO { get; set; }
        public decimal? VLR_ICMS_SUBSTITUTO { get; set; }
        public decimal? VLR_ICMS_DESONERADO { get; set; }
        public int? COD_ALMOXARIFADO { get; set; }
        public int? COD_PRODUTO_ALMOXARIFADO { get; set; }
        public int? COD_MOVIMENTO_ESTOQUE { get; set; }
        public int? COD_UNIDADE_CONVERSAO { get; set; }
        public decimal? QTD_FATOR_CONVERSAO { get; set; }
        public int? IND_TIPO_FATOR { get; set; }
        public decimal? QTD_CONVERTIDA { get; set; }
        public string? DES_PRODUTO { get; set; }
        public decimal? PER_ICMS_INTERNO { get; set; }
        public decimal? PER_REDUCAO_BASE_ST { get; set; }
        public int? COD_CFOP { get; set; }
        public string? COD_PRODUTO_NO_FORNECEDOR { get; set; }
        public string? COD_SKU_XML { get; set; }
        public string? DES_PRODUTO_XML { get; set; }
        public string? DES_UN_PRODUTO_XML { get; set; }
        public decimal? QTD_PRODUTO_XML { get; set; }
        public decimal? VLR_UNITARIO_XML { get; set; }
        public decimal? VLR_TOTAL_XML { get; set; }
        public string? COD_NCM_XML { get; set; }
        public int? NUM_CFOP_XML { get; set; }
        public int? COD_NATUREZA_FRETE_CTE { get; set; }
        public decimal? VLR_NAO_TRIBUTADO { get; set; }
        public int? COD_CENTRO_CUSTO { get; set; }
        public int? COD_CONTA_CONTABIL { get; set; }
        public decimal? VLR_CUSTO_MEDIO { get; set; }
        public decimal? VLR_CUSTO_REAL { get; set; }
        public decimal? VLR_ST_CUSTO { get; set; }

        public virtual GE_ALMOXARIFADOS? COD_ALMOXARIFADONavigation { get; set; }
        public virtual GE_CENTRO_CUSTOS? COD_CENTRO_CUSTONavigation { get; set; }
        public virtual GE_CONTAS_CONTABEIS? COD_CONTA_CONTABILNavigation { get; set; }
        public virtual GE_EMPRESAS COD_EMPRESANavigation { get; set; } = null!;
        public virtual CE_MOVIMENTOS_ESTOQUES? COD_MOVIMENTO_ESTOQUENavigation { get; set; }
        public virtual SW_NATUREZA_FRETE_CTE? COD_NATUREZA_FRETE_CTENavigation { get; set; }
        public virtual CE_NOTAS COD_NOTANavigation { get; set; } = null!;
        public virtual GE_OPERACAO_FISCAL? COD_OPERACAO_FISCALNavigation { get; set; }
        public virtual GE_ORGANIZACAO COD_ORGANIZACAONavigation { get; set; } = null!;
        public virtual CE_PRODUTOS? COD_PRODUTONavigation { get; set; }
        public virtual CE_PRODUTO_ALMOXARIFADOS? COD_PRODUTO_ALMOXARIFADONavigation { get; set; }
        public virtual GE_UNIDADE_MEDIDA? COD_UNIDADE_CONVERSAONavigation { get; set; }
        public virtual GE_UNIDADE_MEDIDA? COD_UNIDADE_MEDIDANavigation { get; set; }
        public virtual ICollection<CE_ITENS_NOTAS_ORDENS_ATENDIDAS> CE_ITENS_NOTAS_ORDENS_ATENDIDAS { get; set; }
        public virtual ICollection<CE_NOTAS_PENDENCIAS_PRODUTOS> CE_NOTAS_PENDENCIAS_PRODUTOS { get; set; }
        public virtual ICollection<FT_DEVOLUCOES> FT_DEVOLUCOES { get; set; }
    }
}