// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class CE_PRODUTO_COMPOSICAO
    {
        public int COD_COMPOSICAO { get; set; }
        public int COD_PRODUTO { get; set; }
        public int COD_PRODUTO_COMPOSICAO { get; set; }
        public decimal? QTD_PRODUTO { get; set; }
        public int? COD_EMPRESA { get; set; }

        public virtual GE_EMPRESAS? COD_EMPRESANavigation { get; set; }
        public virtual CE_PRODUTOS COD_PRODUTONavigation { get; set; } = null!;
        public virtual CE_PRODUTOS COD_PRODUTO_COMPOSICAONavigation { get; set; } = null!;
    }
}