// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class CE_PRODUTOS_LOTES
    {
        public int COD_PRODUTO_LOTE { get; set; }
        public int COD_PRODUTO { get; set; }
        public int? COD_PRODUTO_CONFIGURADO { get; set; }
        public int COD_ALMOXARIFDO { get; set; }
        public string? NUM_LOTE { get; set; }
        public DateTime? DTA_VALIDADE { get; set; }
        public decimal? QTD_ESTOQUE { get; set; }

        public virtual GE_ALMOXARIFADOS COD_ALMOXARIFDONavigation { get; set; } = null!;
        public virtual CE_PRODUTOS COD_PRODUTONavigation { get; set; } = null!;
        public virtual CE_PRODUTOS_CONFIGURADOS? COD_PRODUTO_CONFIGURADONavigation { get; set; }
    }
}