// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class CE_PRODUTOS_CONFIGURADOS
    {
        public CE_PRODUTOS_CONFIGURADOS()
        {
            CE_PRODUTOS_IMAGENS = new HashSet<CE_PRODUTOS_IMAGENS>();
            CE_PRODUTOS_LOTES = new HashSet<CE_PRODUTOS_LOTES>();
            CE_PRODUTOS_SERIES = new HashSet<CE_PRODUTOS_SERIES>();
            CE_PRODUTO_ALMOXARIFADOS = new HashSet<CE_PRODUTO_ALMOXARIFADOS>();
            CE_PRODUTO_BARRAS = new HashSet<CE_PRODUTO_BARRAS>();
            CE_PRODUTO_CONVERSAO_UNIDADES = new HashSet<CE_PRODUTO_CONVERSAO_UNIDADES>();
        }

        public int COD_PRODUTO_CONFIGURADO { get; set; }
        public int? COD_PRODUTO { get; set; }
        public string? COD_CONFIGURADO { get; set; }
        public string? DES_CONFIGURADO { get; set; }
        public string? DES_HASH { get; set; }
        public int? COD_VERSAO { get; set; }
        public decimal? QTD_PESO_LIQUIDO { get; set; }
        public decimal? QTD_PESO_BRUTO { get; set; }
        public decimal? NUM_ALTURA { get; set; }
        public decimal? NUM_LARGURA { get; set; }
        public decimal? NUM_COMPRIMENTO { get; set; }
        public DateTime? DTA_DESATIVACAO { get; set; }
        public string? DES_MOTIVO_DESATIVACAO { get; set; }
        public string? DES_LINK_VIDEO { get; set; }
        public string? DES_LINK_EXTERNO { get; set; }

        public virtual CE_PRODUTOS? COD_PRODUTONavigation { get; set; }
        public virtual CE_CONFIGURADOR_VERSOES? COD_VERSAONavigation { get; set; }
        public virtual ICollection<CE_PRODUTOS_IMAGENS> CE_PRODUTOS_IMAGENS { get; set; }
        public virtual ICollection<CE_PRODUTOS_LOTES> CE_PRODUTOS_LOTES { get; set; }
        public virtual ICollection<CE_PRODUTOS_SERIES> CE_PRODUTOS_SERIES { get; set; }
        public virtual ICollection<CE_PRODUTO_ALMOXARIFADOS> CE_PRODUTO_ALMOXARIFADOS { get; set; }
        public virtual ICollection<CE_PRODUTO_BARRAS> CE_PRODUTO_BARRAS { get; set; }
        public virtual ICollection<CE_PRODUTO_CONVERSAO_UNIDADES> CE_PRODUTO_CONVERSAO_UNIDADES { get; set; }
    }
}