// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class CE_PRODUTO_ALMOXARIFADOS
    {
        public CE_PRODUTO_ALMOXARIFADOS()
        {
            CE_MOVIMENTOS_ESTOQUES = new HashSet<CE_MOVIMENTOS_ESTOQUES>();
            CE_NOTAS_ITENS = new HashSet<CE_NOTAS_ITENS>();
            CO_ORDENS_ITENS = new HashSet<CO_ORDENS_ITENS>();
            FT_NOTAS_ITENS = new HashSet<FT_NOTAS_ITENS>();
            FT_PEDIDOS_ITENS = new HashSet<FT_PEDIDOS_ITENS>();
        }

        public int COD_PRODUTO_ALMOXARIFADO { get; set; }
        public int COD_PRODUTO { get; set; }
        public int? COD_PRODUTO_CONFIGURADO { get; set; }
        public int? COD_ALMOXARIFADO { get; set; }
        public decimal? QTD_ESTOQUE { get; set; }
        public decimal? QTD_MINIMA { get; set; }
        public decimal? QTD_MAXIMA { get; set; }
        public string? DES_LOCALIZACAO { get; set; }
        public bool? TIP_PRINCIPAL { get; set; }
        public bool? TIP_NAO_DISPONIVEL { get; set; }
        public int? COD_EMPRESA { get; set; }
        public bool? TIP_EXCLUIDO { get; set; }

        public virtual GE_ALMOXARIFADOS? COD_ALMOXARIFADONavigation { get; set; }
        public virtual GE_EMPRESAS? COD_EMPRESANavigation { get; set; }
        public virtual CE_PRODUTOS COD_PRODUTONavigation { get; set; } = null!;
        public virtual CE_PRODUTOS_CONFIGURADOS? COD_PRODUTO_CONFIGURADONavigation { get; set; }
        public virtual ICollection<CE_MOVIMENTOS_ESTOQUES> CE_MOVIMENTOS_ESTOQUES { get; set; }
        public virtual ICollection<CE_NOTAS_ITENS> CE_NOTAS_ITENS { get; set; }
        public virtual ICollection<CO_ORDENS_ITENS> CO_ORDENS_ITENS { get; set; }
        public virtual ICollection<FT_NOTAS_ITENS> FT_NOTAS_ITENS { get; set; }
        public virtual ICollection<FT_PEDIDOS_ITENS> FT_PEDIDOS_ITENS { get; set; }
    }
}