// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class CE_PRODUTO_BARRAS
    {
        public int COD_PRODUTO_BARRAS { get; set; }
        public int COD_PRODUTO { get; set; }
        public int? COD_PRODUTO_CONFIGURADO { get; set; }
        public int COD_TIPO_BARRA { get; set; }
        public string? COD_BARRAS { get; set; }

        public virtual CE_PRODUTOS COD_PRODUTONavigation { get; set; } = null!;
        public virtual CE_PRODUTOS_CONFIGURADOS? COD_PRODUTO_CONFIGURADONavigation { get; set; }
        public virtual SW_TIPOS_BARRAS COD_TIPO_BARRANavigation { get; set; } = null!;
    }
}