// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class CE_PRODUTO_CONVERSAO_UNIDADES
    {
        public int COD_CONVERSAO { get; set; }
        public int COD_PRODUTO { get; set; }
        public int? COD_PRODUTO_CONFIGURADO { get; set; }
        public int COD_UNIDADE_CONVERSAO { get; set; }
        public decimal QTD_FATOR { get; set; }
        public int? COD_PESSOA { get; set; }
        public int? IND_TIPO_CONVERSAO { get; set; }
        public int? IND_TIPO_FATOR { get; set; }

        public virtual PS_PESSOAS? COD_PESSOANavigation { get; set; }
        public virtual CE_PRODUTOS COD_PRODUTONavigation { get; set; } = null!;
        public virtual CE_PRODUTOS_CONFIGURADOS? COD_PRODUTO_CONFIGURADONavigation { get; set; }
        public virtual GE_UNIDADE_MEDIDA COD_UNIDADE_CONVERSAONavigation { get; set; } = null!;
    }
}