// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class CE_PRODUTOS_FCI
    {
        public int COD_PRODUTO_FCI { get; set; }
        public int COD_PRODUTO { get; set; }
        public DateTime? DTA_EMISSAO { get; set; }
        public decimal? VLR_PRECO_VENDA { get; set; }
        public decimal? VLR_CONT_IMPORTACAO { get; set; }
        public decimal? VLR_PER_CONT_IMPORTACAO { get; set; }
        public string? NUM_FCI { get; set; }
        public bool? TIP_ATIVO { get; set; }
        public int COD_EMPRESA { get; set; }

        public virtual GE_EMPRESAS COD_EMPRESANavigation { get; set; } = null!;
        public virtual CE_PRODUTOS COD_PRODUTONavigation { get; set; } = null!;
    }
}