// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class CE_PRODUTOS_SERIES
    {
        public int COD_PRODUTO_SERIE { get; set; }
        public int COD_PRODUTO { get; set; }
        public int? COD_PRODUTO_CONFIGURADO { get; set; }
        public string? NUM_SERIE { get; set; }
        public int? IND_SITUACAO { get; set; }

        public virtual CE_PRODUTOS COD_PRODUTONavigation { get; set; } = null!;
        public virtual CE_PRODUTOS_CONFIGURADOS? COD_PRODUTO_CONFIGURADONavigation { get; set; }
    }
}