// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class CE_PRODUTOS_VALORES
    {
        public int COD_PRODUTO_VALOR { get; set; }
        public int COD_PRODUTO { get; set; }
        public int COD_EMPRESA { get; set; }
        public decimal VLR_CUSTO_REAL { get; set; }
        public decimal VLR_CUSTO_REAL_ANTERIOR { get; set; }
        public decimal VLR_CUSTO_MEDIO { get; set; }
        public decimal VLR_CUSTO_REPOSICAO { get; set; }
        public decimal VLR_PRECO_VENDA { get; set; }
        public decimal? PER_MARGEM_MINIMA_VENDA { get; set; }
        public decimal? PER_MARGEM_LUCRO { get; set; }
        public bool? IND_PRECO_MARKUP { get; set; }

        public virtual GE_EMPRESAS COD_EMPRESANavigation { get; set; } = null!;
        public virtual CE_PRODUTOS COD_PRODUTONavigation { get; set; } = null!;
    }
}