// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class CO_APROVADORES
    {
        public CO_APROVADORES()
        {
            CO_REGRAS_APROVADORES = new HashSet<CO_REGRAS_APROVADORES>();
            CO_REGRAS_APROVADORES_USUARIOS = new HashSet<CO_REGRAS_APROVADORES_USUARIOS>();
        }

        public int COD_APROVACAO { get; set; }
        public int COD_EMPRESA { get; set; }
        public string? DES_REGRA { get; set; }
        public int COD_USUARIO { get; set; }
        public DateTime DTA_CRIACAO { get; set; }
        public int NUM_SEQUENCIA { get; set; }

        public virtual GE_EMPRESAS COD_EMPRESANavigation { get; set; } = null!;
        public virtual GE_USUARIOS COD_USUARIONavigation { get; set; } = null!;
        public virtual ICollection<CO_REGRAS_APROVADORES> CO_REGRAS_APROVADORES { get; set; }
        public virtual ICollection<CO_REGRAS_APROVADORES_USUARIOS> CO_REGRAS_APROVADORES_USUARIOS { get; set; }
    }
}