// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class CO_LOGS_STATUS_ORDENS
    {
        public int COD_LOG { get; set; }
        public int COD_ORDEM { get; set; }
        public int COD_STATUS { get; set; }
        public DateTime DTA_STATUS { get; set; }
        public int COD_USUARIO { get; set; }
        public string? DES_OBSERVACAO { get; set; }
        public int COD_EMPRESA { get; set; }

        public virtual GE_EMPRESAS COD_EMPRESANavigation { get; set; } = null!;
        public virtual CO_ORDENS COD_ORDEMNavigation { get; set; } = null!;
        public virtual SW_STATUS_ORDENS COD_STATUSNavigation { get; set; } = null!;
        public virtual GE_USUARIOS COD_USUARIONavigation { get; set; } = null!;
    }
}