// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class CO_ORDENS_ITENS
    {
        public CO_ORDENS_ITENS()
        {
            CE_ITENS_NOTAS_ORDENS_ATENDIDAS = new HashSet<CE_ITENS_NOTAS_ORDENS_ATENDIDAS>();
        }

        public int COD_ITEM { get; set; }
        public int COD_ORDEM { get; set; }
        public int COD_PRODUTO { get; set; }
        public int COD_EMPRESA { get; set; }
        public int COD_ORGANIZACAO { get; set; }
        public int NUM_SEQUENCIA { get; set; }
        public int? COD_UNIDADE_MEDIDA { get; set; }
        public int? COD_OPERACAO_FISCAL { get; set; }
        public decimal? QTD_PRODUTO { get; set; }
        public decimal? VLR_UNITARIO { get; set; }
        public decimal? VLR_MERCADORIA { get; set; }
        public decimal? VLR_TOTAL { get; set; }
        public decimal? VLR_DESCONTO { get; set; }
        public decimal? VLR_FRETE { get; set; }
        public decimal? VLR_SEGURO { get; set; }
        public decimal? VLR_DESPESAS { get; set; }
        public decimal? VLR_BASE_ST { get; set; }
        public decimal? VLR_ST { get; set; }
        public decimal? PER_MVA { get; set; }
        public decimal? VLR_BASE_ICMS { get; set; }
        public decimal? VLR_ICMS { get; set; }
        public decimal? PER_ICMS { get; set; }
        public decimal? VLR_BASE_IPI { get; set; }
        public decimal? VLR_IPI { get; set; }
        public decimal? PER_IPI { get; set; }
        public decimal? VLR_BASE_PIS { get; set; }
        public decimal? VLR_PIS { get; set; }
        public decimal? PER_PIS { get; set; }
        public decimal? VLR_BASE_COFINS { get; set; }
        public decimal? VLR_COFINS { get; set; }
        public decimal? PER_COFINS { get; set; }
        public decimal? VLR_BASE_ST_RETIDO { get; set; }
        public decimal? PER_ST_RETIDO { get; set; }
        public decimal? VLR_ST_RETIDO { get; set; }
        public decimal? VLR_ICMS_SUBSTITUTO { get; set; }
        public decimal? VLR_ICMS_DESONERADO { get; set; }
        public int? COD_ALMOXARIFADO { get; set; }
        public int? COD_PRODUTO_ALMOXARIFADO { get; set; }
        public int? COD_UNIDADE_CONVERSAO { get; set; }
        public decimal? QTD_FATOR_CONVERSAO { get; set; }
        public int? IND_TIPO_FATOR { get; set; }
        public decimal? QTD_CONVERTIDA { get; set; }
        public string? DES_PRODUTO { get; set; }
        public decimal? PER_ICMS_INTERNO { get; set; }
        public decimal? PER_REDUCAO_BASE_ST { get; set; }
        public int? COD_CONTA_CONTABIL { get; set; }
        public int? COD_CENTRO_CUSTO { get; set; }
        public DateTime? DTA_CANCELAMENTO { get; set; }
        public string? DES_MOTIVO_CANCELAMENTO { get; set; }
        public int? COD_USUARIO_CANCELAMENTO { get; set; }
        public decimal? QTD_ATENDIDA { get; set; }

        public virtual GE_ALMOXARIFADOS? COD_ALMOXARIFADONavigation { get; set; }
        public virtual GE_CENTRO_CUSTOS? COD_CENTRO_CUSTONavigation { get; set; }
        public virtual GE_CONTAS_CONTABEIS? COD_CONTA_CONTABILNavigation { get; set; }
        public virtual GE_EMPRESAS COD_EMPRESANavigation { get; set; } = null!;
        public virtual GE_OPERACAO_FISCAL? COD_OPERACAO_FISCALNavigation { get; set; }
        public virtual CO_ORDENS COD_ORDEMNavigation { get; set; } = null!;
        public virtual GE_ORGANIZACAO COD_ORGANIZACAONavigation { get; set; } = null!;
        public virtual CE_PRODUTOS COD_PRODUTONavigation { get; set; } = null!;
        public virtual CE_PRODUTO_ALMOXARIFADOS? COD_PRODUTO_ALMOXARIFADONavigation { get; set; }
        public virtual GE_UNIDADE_MEDIDA? COD_UNIDADE_CONVERSAONavigation { get; set; }
        public virtual GE_UNIDADE_MEDIDA? COD_UNIDADE_MEDIDANavigation { get; set; }
        public virtual GE_USUARIOS? COD_USUARIO_CANCELAMENTONavigation { get; set; }
        public virtual ICollection<CE_ITENS_NOTAS_ORDENS_ATENDIDAS> CE_ITENS_NOTAS_ORDENS_ATENDIDAS { get; set; }
    }
}