// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class CO_ORDENS_MENSAGENS
    {
        public int COD_MENSAGEM { get; set; }
        public int COD_ORDEM { get; set; }
        public string DES_MENSAGEM { get; set; } = null!;
        public int COD_EMPRESA { get; set; }
        public int COD_ORGANIZACAO { get; set; }
        public bool? TIP_MENSAGEM_FISCO { get; set; }

        public virtual GE_EMPRESAS COD_EMPRESANavigation { get; set; } = null!;
        public virtual CO_ORDENS COD_ORDEMNavigation { get; set; } = null!;
        public virtual GE_ORGANIZACAO COD_ORGANIZACAONavigation { get; set; } = null!;
    }
}