// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class CO_ORDENS
    {
        public CO_ORDENS()
        {
            CO_LOGS_STATUS_ORDENS = new HashSet<CO_LOGS_STATUS_ORDENS>();
            CO_ORDENS_APROVADORES = new HashSet<CO_ORDENS_APROVADORES>();
            CO_ORDENS_ITENS = new HashSet<CO_ORDENS_ITENS>();
            CO_ORDENS_MENSAGENS = new HashSet<CO_ORDENS_MENSAGENS>();
            CO_ORDENS_PAGAMENTOS = new HashSet<CO_ORDENS_PAGAMENTOS>();
        }

        public int COD_ORDEM { get; set; }
        public int NUM_ORDEM { get; set; }
        public int COD_PESSOA { get; set; }
        public int COD_EMPRESA { get; set; }
        public int COD_ORGANIZACAO { get; set; }
        public DateTime DTA_ORDEM { get; set; }
        public DateTime DTA_ENTREGA { get; set; }
        public int COD_CONDICAO_PAGAMENTO { get; set; }
        public int? COD_OPERACAO_FISCAL { get; set; }
        public decimal? VLR_MERCADORIA { get; set; }
        public decimal? VLR_TOTAL { get; set; }
        public decimal? VLR_DESCONTO { get; set; }
        public decimal? VLR_FRETE { get; set; }
        public decimal? VLR_DESPESAS { get; set; }
        public decimal? VLR_SEGURO { get; set; }
        public decimal? VLR_BASE_ICMS { get; set; }
        public decimal? VLR_ICMS { get; set; }
        public decimal? VLR_BASE_IPI { get; set; }
        public decimal? VLR_IPI { get; set; }
        public decimal? VLR_BASE_ST { get; set; }
        public decimal? VLR_ST { get; set; }
        public int? COD_TRANSPORTADORA { get; set; }
        public string COD_MODALIDADE_FRETE { get; set; } = null!;
        public string? DES_COMPOSICAO_PAGAMENTO { get; set; }
        public DateTime? DTA_ENCERRAMENTO { get; set; }
        public DateTime? DTA_CANCELAMENTO { get; set; }
        public int? COD_USUARIO { get; set; }
        public int? COD_STATUS_ORDEM { get; set; }
        public string? DES_GUID_COMPARTILHAMENTO { get; set; }
        public int? IND_ORIGEM { get; set; }

        public virtual GE_CONDICAO_PAGAMENTO COD_CONDICAO_PAGAMENTONavigation { get; set; } = null!;
        public virtual GE_EMPRESAS COD_EMPRESANavigation { get; set; } = null!;
        public virtual SW_MODALIDADES_FRETE COD_MODALIDADE_FRETENavigation { get; set; } = null!;
        public virtual GE_OPERACAO_FISCAL? COD_OPERACAO_FISCALNavigation { get; set; }
        public virtual GE_ORGANIZACAO COD_ORGANIZACAONavigation { get; set; } = null!;
        public virtual PS_PESSOAS COD_PESSOANavigation { get; set; } = null!;
        public virtual SW_STATUS_ORDENS? COD_STATUS_ORDEMNavigation { get; set; }
        public virtual PS_PESSOAS? COD_TRANSPORTADORANavigation { get; set; }
        public virtual GE_USUARIOS? COD_USUARIONavigation { get; set; }
        public virtual ICollection<CO_LOGS_STATUS_ORDENS> CO_LOGS_STATUS_ORDENS { get; set; }
        public virtual ICollection<CO_ORDENS_APROVADORES> CO_ORDENS_APROVADORES { get; set; }
        public virtual ICollection<CO_ORDENS_ITENS> CO_ORDENS_ITENS { get; set; }
        public virtual ICollection<CO_ORDENS_MENSAGENS> CO_ORDENS_MENSAGENS { get; set; }
        public virtual ICollection<CO_ORDENS_PAGAMENTOS> CO_ORDENS_PAGAMENTOS { get; set; }
    }
}