// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class CO_PARAMETROS
    {
        public int COD_EMPRESA { get; set; }
        public bool? TIP_VISUALIZAR_ORDENS_USUARIOS { get; set; }
        public bool? TIP_APROVACAO { get; set; }
        public int? COD_STATUS_INICIAL { get; set; }
        public int? COD_STATUS_FINAL { get; set; }
        public int? COD_MODELO { get; set; }

        public virtual GE_EMPRESAS COD_EMPRESANavigation { get; set; } = null!;
        public virtual SW_STATUS_ORDENS? COD_STATUS_FINALNavigation { get; set; }
        public virtual SW_STATUS_ORDENS? COD_STATUS_INICIALNavigation { get; set; }
    }
}