// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class CO_REGRAS_APROVADORES
    {
        public CO_REGRAS_APROVADORES()
        {
            InverseCOD_REGRA_PAINavigation = new HashSet<CO_REGRAS_APROVADORES>();
        }

        public int COD_REGRA { get; set; }
        public int COD_APROVACAO { get; set; }
        public int NUM_SEQUENCIA { get; set; }
        public int COD_TIPO { get; set; }
        public string? DES_OPERADOR { get; set; }
        public decimal? VLR_VALOR { get; set; }
        public int? COD_RESPOSTA { get; set; }
        public int? COD_REGRA_PAI { get; set; }
        public string? DES_OPERADOR_LOGICO { get; set; }

        public virtual CO_APROVADORES COD_APROVACAONavigation { get; set; } = null!;
        public virtual CO_REGRAS_APROVADORES? COD_REGRA_PAINavigation { get; set; }
        public virtual SW_TIPOS_REGRAS_ORDENS COD_TIPONavigation { get; set; } = null!;
        public virtual ICollection<CO_REGRAS_APROVADORES> InverseCOD_REGRA_PAINavigation { get; set; }
    }
}