// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class CO_STATUS_CONFIGURACOES
    {
        public int COD_CONFIG_STATUS { get; set; }
        public int COD_STATUS { get; set; }
        public int COD_EMPRESA { get; set; }
        public string? DES_COR { get; set; }

        public virtual GE_EMPRESAS COD_EMPRESANavigation { get; set; } = null!;
        public virtual SW_STATUS_ORDENS COD_STATUSNavigation { get; set; } = null!;
    }
}