// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class CP_HISTORICO
    {
        public int COD_HISTORICO { get; set; }
        public int COD_TITULO { get; set; }
        public DateTime DTA_MOVIMENTO { get; set; }
        public decimal? VLR_MOVIMENTO { get; set; }
        public decimal? VLR_JUROS { get; set; }
        public decimal? VLR_DESCONTO { get; set; }
        public decimal? VLR_MULTA { get; set; }
        public decimal? VLR_ABATIMENTO { get; set; }
        public decimal? VLR_ACRESCIMO { get; set; }
        public int? COD_BANCO { get; set; }
        public int? COD_TIPO_PAGAMENTO { get; set; }
        public int? COD_ORGANIZACAO { get; set; }

        public virtual GE_BANCOS? COD_BANCONavigation { get; set; }
        public virtual GE_ORGANIZACAO? COD_ORGANIZACAONavigation { get; set; }
        public virtual GE_TIPO_PAGAMENTO? COD_TIPO_PAGAMENTONavigation { get; set; }
        public virtual CP_TITULOS COD_TITULONavigation { get; set; } = null!;
    }
}