// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class CP_PARAMETROS
    {
        public int COD_EMPRESA { get; set; }
        public int? NUM_ULTIMO_TITULO { get; set; }
        public int? COD_FORNECEDOR_GNRE { get; set; }
        public bool? TIP_NAO_ALTERA_SALDO_INICIAL_RELATORIO { get; set; }

        public virtual PS_PESSOAS? COD_FORNECEDOR_GNRENavigation { get; set; }
    }
}