// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class CR_CONVENIOS_BANCARIOS
    {
        public CR_CONVENIOS_BANCARIOS()
        {
            CR_TITULOS = new HashSet<CR_TITULOS>();
            FT_NOTAS = new HashSet<FT_NOTAS>();
            FT_PEDIDOS = new HashSet<FT_PEDIDOS>();
        }

        public int COD_CONVENIO_BANCARIO { get; set; }
        public int? COD_EMPRESA { get; set; }
        public int? COD_ORGANIZACAO { get; set; }
        public int COD_CONTA_BANCARIA { get; set; }
        public string NUM_CONVENIO { get; set; } = null!;
        public string? NUM_DV_CONVENIO { get; set; }
        public string IND_CARTEIRA { get; set; } = null!;
        public string IND_CNAB { get; set; } = null!;
        public int? NUM_REMESSA_ATUAL { get; set; }
        public int NUM_NOSSO_NUMERO { get; set; }
        public decimal PER_JUROS_MES { get; set; }
        public string? DES_MENSAGEM_01 { get; set; }
        public string? DES_MENSAGEM_02 { get; set; }
        public string? DES_MENSAGEM_03 { get; set; }
        public string? DES_MENSAGEM_04 { get; set; }
        public string? DES_MENSAGEM_05 { get; set; }
        public string? DES_MENSAGEM_06 { get; set; }
        public string? DES_MENSAGEM_07 { get; set; }
        public string? DES_MENSAGEM_08 { get; set; }
        public string? DES_MENSAGEM_09 { get; set; }
        public decimal VLR_MULTA { get; set; }
        public int IND_MULTA { get; set; }
        public int IND_PROTESTO { get; set; }
        public int IND_JUROS { get; set; }
        public int IND_EMISSAO_BOLETO { get; set; }
        public DateTime? DTA_DESATIVACAO { get; set; }
        public string DES_CONVENIO { get; set; } = null!;
        public decimal? PER_MULTA { get; set; }
        public string? COD_ID_INTEGRACAO { get; set; }
        public int? NUM_DIAS_PROTESTO { get; set; }
        public bool? TIP_OPENBANK { get; set; }
        public string? DES_API_KEY_OPENBANK { get; set; }
        public string? DES_USUARIO_OPENBANK { get; set; }
        public string? DES_SENHA_OPENBANK { get; set; }
        public int? IND_AMBIENTE { get; set; }
        public bool? IND_REGISTRO_AUTOMATICO_BOLETO { get; set; }
        public string? DES_CLIENT_ID { get; set; }
        public string? DES_CLIENT_SECRET { get; set; }
        public int? NUM_VARIACAO_CARTEIRA { get; set; }
        public int? NUM_DIAS_BAIXA { get; set; }
        public string? COD_COOPERATIVA_OPEN_BANK { get; set; }
        public string? COD_POSTO_OPEN_BANK { get; set; }
        public int? IND_ACEITE { get; set; }
        public bool? IND_ACEITE_VENCIDOS { get; set; }
        public int? NUM_DIAS_LIMITE_RECEBIMENTO { get; set; }
        public int? COD_CERTIFICADO { get; set; }
        public string? DES_TOKEN { get; set; }
        public DateTime? DTA_VALIDADE_TOKEN { get; set; }
        public bool? TIP_GERAR_QRCODE { get; set; }

        public virtual GE_CERTIFICADO_DIGITAL? COD_CERTIFICADONavigation { get; set; }
        public virtual CR_CONTAS_BANCARIAS COD_CONTA_BANCARIANavigation { get; set; } = null!;
        public virtual GE_EMPRESAS? COD_EMPRESANavigation { get; set; }
        public virtual GE_ORGANIZACAO? COD_ORGANIZACAONavigation { get; set; }
        public virtual ICollection<CR_TITULOS> CR_TITULOS { get; set; }
        public virtual ICollection<FT_NOTAS> FT_NOTAS { get; set; }
        public virtual ICollection<FT_PEDIDOS> FT_PEDIDOS { get; set; }
    }
}