// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class CR_CONTAS_BANCARIAS
    {
        public CR_CONTAS_BANCARIAS()
        {
            CR_CONVENIOS_BANCARIOS = new HashSet<CR_CONVENIOS_BANCARIOS>();
        }

        public int COD_CONTA_BANCARIA { get; set; }
        public int COD_EMPRESA { get; set; }
        public int COD_ORGANIZACAO { get; set; }
        public int? COD_EMPRESA_CEDENTE { get; set; }
        public string NUM_AGENCIA { get; set; } = null!;
        public string? NUM_DV_AGENCIA { get; set; }
        public string NUM_CONTA { get; set; } = null!;
        public string? NUM_DV_CONTA { get; set; }
        public int COD_BANCO_HOMOLOGADO { get; set; }
        public string COD_BENEFICIARIO { get; set; } = null!;
        public string? NUM_DV_BENEFICIARIO { get; set; }
        public int IND_TIPO_CONTA { get; set; }
        public string? COD_EMPRESA_ESCRITURAL { get; set; }
        public string? COD_ID_INTEGRACAO { get; set; }
        public bool? TIP_EMISSAO_BOLETO_BANCO { get; set; }
        public int? COD_BANCO { get; set; }

        public virtual SW_BANCOS_HOMOLOGADOS COD_BANCO_HOMOLOGADONavigation { get; set; } = null!;
        public virtual GE_EMPRESAS COD_EMPRESANavigation { get; set; } = null!;
        public virtual GE_EMPRESAS? COD_EMPRESA_CEDENTENavigation { get; set; }
        public virtual GE_ORGANIZACAO COD_ORGANIZACAONavigation { get; set; } = null!;
        public virtual ICollection<CR_CONVENIOS_BANCARIOS> CR_CONVENIOS_BANCARIOS { get; set; }
    }
}