// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class CR_REMESSA_OPEN_BANK
    {
        public int COD_REMESSA { get; set; }
        public int COD_EMPRESA { get; set; }
        public int COD_BANCO { get; set; }
        public int COD_USUARIO { get; set; }
        public DateTime DTA_REMESSA { get; set; }
        public string? DES_JSON { get; set; }

        public virtual GE_BANCOS COD_BANCONavigation { get; set; } = null!;
        public virtual GE_EMPRESAS COD_EMPRESANavigation { get; set; } = null!;
        public virtual GE_USUARIOS COD_USUARIONavigation { get; set; } = null!;
    }
}