// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class CR_RETORNO_HISTORICO
    {
        public int COD_RETORNO_HISTORICO { get; set; }
        public int? COD_ORGANIZACAO { get; set; }
        public int? COD_EMPRESA { get; set; }
        public int? COD_TITULO { get; set; }
        public int COD_OCORRENCIA { get; set; }
        public DateTime DTA_HISTORICO { get; set; }
        public string DES_MOTIVO { get; set; } = null!;
        public string? DES_ARQUIVO { get; set; }
        public bool TIP_REENVIADO { get; set; }
        public decimal VLR_DESPESA { get; set; }
        public DateTime? DTA_OCORRENCIA { get; set; }

        public virtual GE_EMPRESAS? COD_EMPRESANavigation { get; set; }
        public virtual SW_OCORRENCIAS_BANCARIAS COD_OCORRENCIANavigation { get; set; } = null!;
        public virtual GE_ORGANIZACAO? COD_ORGANIZACAONavigation { get; set; }
        public virtual CR_TITULOS? COD_TITULONavigation { get; set; }
    }
}