// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class CR_SALDOS
    {
        public int COD_SALDO { get; set; }
        public int COD_BANCO { get; set; }
        public DateTime DTA_SALDO { get; set; }
        public decimal VLR_SALDO { get; set; }
        public int COD_EMPRESA { get; set; }
        public int? COD_ORGANIZACAO { get; set; }

        public virtual GE_BANCOS COD_BANCONavigation { get; set; } = null!;
        public virtual GE_EMPRESAS COD_EMPRESANavigation { get; set; } = null!;
        public virtual GE_ORGANIZACAO? COD_ORGANIZACAONavigation { get; set; }
    }
}