// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class CR_TITULOS_LANCAMENTOS
    {
        public int COD_LANCAMENTO { get; set; }
        public int COD_TITULO { get; set; }
        public int? COD_CONTA_CONTABIL { get; set; }
        public int? COD_CENTRO_CUSTO { get; set; }
        public int COD_EMPRESA { get; set; }
        public decimal? VLR_LANCAMENTO { get; set; }

        public virtual GE_CENTRO_CUSTOS? COD_CENTRO_CUSTONavigation { get; set; }
        public virtual GE_CONTAS_CONTABEIS? COD_CONTA_CONTABILNavigation { get; set; }
        public virtual GE_EMPRESAS COD_EMPRESANavigation { get; set; } = null!;
        public virtual CR_TITULOS COD_TITULONavigation { get; set; } = null!;
    }
}