// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class CR_TITULOS_ALTERACAO_REMESSA
    {
        public int COD_ALTERACAO_TITULO_REMESSA { get; set; }
        public int COD_TITULO { get; set; }
        public int COD_OCORRENCIA { get; set; }
        public DateTime? DTA_OCORRENCIA { get; set; }

        public virtual CR_TITULOS COD_TITULONavigation { get; set; } = null!;
    }
}