// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class CR_TITULOS_COMISSOES
    {
        public int COD_COMISSAO { get; set; }
        public int COD_TITULO { get; set; }
        public int COD_PESSOA { get; set; }
        public decimal VLR_BASE_COMISSAO { get; set; }
        public decimal PER_COMISSAO { get; set; }
        public decimal VLR_COMISSAO { get; set; }
        public string? DES_GUID { get; set; }
        public int? IND_COMISSAO { get; set; }

        public virtual PS_PESSOAS COD_PESSOANavigation { get; set; } = null!;
        public virtual CR_TITULOS COD_TITULONavigation { get; set; } = null!;
    }
}