// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class CR_TITULOS
    {
        public CR_TITULOS()
        {
            CR_HISTORICOS = new HashSet<CR_HISTORICOS>();
            CR_RETORNO_HISTORICO = new HashSet<CR_RETORNO_HISTORICO>();
            CR_TITULOS_ALTERACAO_REMESSA = new HashSet<CR_TITULOS_ALTERACAO_REMESSA>();
            CR_TITULOS_BOLETOS = new HashSet<CR_TITULOS_BOLETOS>();
            CR_TITULOS_COMISSOES = new HashSet<CR_TITULOS_COMISSOES>();
            CR_TITULOS_LANCAMENTOS = new HashSet<CR_TITULOS_LANCAMENTOS>();
            FT_FATURA_TITULOS = new HashSet<FT_FATURA_TITULOS>();
        }

        public int COD_TITULO { get; set; }
        public int? COD_ORGANIZACAO { get; set; }
        public int COD_EMPRESA { get; set; }
        public int COD_PESSOA { get; set; }
        public int NUM_TITULO { get; set; }
        public int NUM_PARCELA { get; set; }
        public int? COD_NOTA { get; set; }
        public DateTime DTA_EMISSAO { get; set; }
        public DateTime? DTA_VENCIMENTO { get; set; }
        public DateTime? DTA_PAGAMENTO { get; set; }
        public int? COD_TIPO_PAGAMENTO { get; set; }
        public int? COD_BANCO { get; set; }
        public decimal? VLR_TITULO { get; set; }
        public decimal? VLR_PAGO { get; set; }
        public decimal? VLR_DESCONTO { get; set; }
        public decimal? VLR_JUROS { get; set; }
        public decimal? VLR_DESPESAS { get; set; }
        public int IND_SITUACAO { get; set; }
        public string? NUM_BOLETO { get; set; }
        public string? NUM_DIGITO_BOLETO { get; set; }
        public decimal? VLR_ABATIMENTO { get; set; }
        public decimal? VLR_MULTA { get; set; }
        public decimal? VLR_ACRESCIMO { get; set; }
        public decimal? VLR_SALDO { get; set; }
        public string? DES_OBSERVACAO { get; set; }
        public string? COD_ID_INTEGRACAO { get; set; }
        public string? DES_URL_BOLETO { get; set; }
        public int? COD_CONVENIO_BANCARIO { get; set; }
        public DateTime? DTA_REMESSA { get; set; }
        public int? COD_CONTA_CONTABIL { get; set; }
        public bool? TIP_HOMOLOGACAO { get; set; }
        public string? DES_GUID { get; set; }
        public string? DES_LINHA_DIGITAVEL { get; set; }
        public string? DES_CODIGO_BARRAS { get; set; }
        public bool? TIP_OPENBANK { get; set; }
        public bool? TIP_LANCTO_DESPESA { get; set; }
        public decimal? VLR_FATURADO { get; set; }
        public bool? TIP_TRANSFERENCIA_CONTA { get; set; }

        public virtual GE_BANCOS? COD_BANCONavigation { get; set; }
        public virtual GE_CONTAS_CONTABEIS? COD_CONTA_CONTABILNavigation { get; set; }
        public virtual CR_CONVENIOS_BANCARIOS? COD_CONVENIO_BANCARIONavigation { get; set; }
        public virtual GE_EMPRESAS COD_EMPRESANavigation { get; set; } = null!;
        public virtual FT_NOTAS? COD_NOTANavigation { get; set; }
        public virtual GE_ORGANIZACAO? COD_ORGANIZACAONavigation { get; set; }
        public virtual PS_PESSOAS COD_PESSOANavigation { get; set; } = null!;
        public virtual GE_TIPO_PAGAMENTO? COD_TIPO_PAGAMENTONavigation { get; set; }
        public virtual ICollection<CR_HISTORICOS> CR_HISTORICOS { get; set; }
        public virtual ICollection<CR_RETORNO_HISTORICO> CR_RETORNO_HISTORICO { get; set; }
        public virtual ICollection<CR_TITULOS_ALTERACAO_REMESSA> CR_TITULOS_ALTERACAO_REMESSA { get; set; }
        public virtual ICollection<CR_TITULOS_BOLETOS> CR_TITULOS_BOLETOS { get; set; }
        public virtual ICollection<CR_TITULOS_COMISSOES> CR_TITULOS_COMISSOES { get; set; }
        public virtual ICollection<CR_TITULOS_LANCAMENTOS> CR_TITULOS_LANCAMENTOS { get; set; }
        public virtual ICollection<FT_FATURA_TITULOS> FT_FATURA_TITULOS { get; set; }
    }
}