// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class CR_TITULOS_BOLETOS
    {
        public int COD_BOLETO { get; set; }
        public int? COD_TITULO { get; set; }
        public string? DES_HASH { get; set; }

        public virtual CR_TITULOS? COD_TITULONavigation { get; set; }
    }
}