// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class FT_FATURA_ITENS
    {
        public int COD_FATURA_ITENS { get; set; }
        public int COD_FATURA { get; set; }
        public int? IND_TIPO_ITEM { get; set; }
        public decimal? VLR_ITEM { get; set; }
        public int COD_EMPRESA { get; set; }
        public int COD_ORGANIZACAO { get; set; }
        public int? COD_LANCAMENTO { get; set; }
        public int? COD_CONTRATO_ITENS { get; set; }
        public int? HMS_FATURADOS { get; set; }
        public decimal? VLR_DESCONTO { get; set; }

        public virtual PS_CONTRATOS_ITENS? COD_CONTRATO_ITENSNavigation { get; set; }
        public virtual GE_EMPRESAS COD_EMPRESANavigation { get; set; } = null!;
        public virtual FT_FATURA COD_FATURANavigation { get; set; } = null!;
        public virtual PS_LANCAMENTOS? COD_LANCAMENTONavigation { get; set; }
        public virtual GE_ORGANIZACAO COD_ORGANIZACAONavigation { get; set; } = null!;
    }
}