// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class FT_FATURA
    {
        public FT_FATURA()
        {
            FT_FATURA_ITENS = new HashSet<FT_FATURA_ITENS>();
            FT_FATURA_TITULOS = new HashSet<FT_FATURA_TITULOS>();
        }

        public int COD_FATURA { get; set; }
        public int COD_PESSOA { get; set; }
        public DateTime DTA_FATURA { get; set; }
        public int? COD_USUARIO { get; set; }
        public bool? TIP_EXCLUIDO { get; set; }
        public int COD_EMPRESA { get; set; }
        public int COD_ORGANIZACAO { get; set; }
        public decimal? VLR_FATURA { get; set; }
        public DateTime? DTA_GERACAO { get; set; }
        public DateTime DTA_ANALISE_INICIAL { get; set; }
        public DateTime DTA_ANALISE_FINAL { get; set; }
        public string? DES_RELATORIO_DESCRITIVO { get; set; }
        public decimal? VLR_DESCONTO { get; set; }

        public virtual GE_EMPRESAS COD_EMPRESANavigation { get; set; } = null!;
        public virtual GE_ORGANIZACAO COD_ORGANIZACAONavigation { get; set; } = null!;
        public virtual PS_PESSOAS COD_PESSOANavigation { get; set; } = null!;
        public virtual GE_USUARIOS? COD_USUARIONavigation { get; set; }
        public virtual ICollection<FT_FATURA_ITENS> FT_FATURA_ITENS { get; set; }
        public virtual ICollection<FT_FATURA_TITULOS> FT_FATURA_TITULOS { get; set; }
    }
}