// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class FT_FATURA_TITULOS
    {
        public int COD_FATURA_TITULO { get; set; }
        public int COD_FATURA { get; set; }
        public int COD_TITULO { get; set; }

        public virtual FT_FATURA COD_FATURANavigation { get; set; } = null!;
        public virtual CR_TITULOS COD_TITULONavigation { get; set; } = null!;
    }
}