// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class FT_FATURAS_NAO_GERADAS
    {
        public int COD_FATURA_NAO_GERADA { get; set; }
        public int COD_EMPRESA { get; set; }
        public int COD_ORGANIZACAO { get; set; }
        public int COD_CONTRATO { get; set; }
        public DateTime DTA_FATURA { get; set; }
        public bool? TIP_NAO_GERAR { get; set; }

        public virtual PS_CONTRATOS COD_CONTRATONavigation { get; set; } = null!;
        public virtual GE_EMPRESAS COD_EMPRESANavigation { get; set; } = null!;
        public virtual GE_ORGANIZACAO COD_ORGANIZACAONavigation { get; set; } = null!;
    }
}