// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class FT_MANIFESTO_DESTINATARIO
    {
        public int COD_MANIFESTO { get; set; }
        public int? COD_EMPRESA { get; set; }
        public string? NUM_CNPJ { get; set; }
        public int? NUM_NSU { get; set; }
        public string? DES_CHAVE_ACESSO { get; set; }
        public string? DES_RAZAO_SOCIAL { get; set; }
        public DateTime? DTA_EMISSAO { get; set; }
        public decimal? VLR_NOTA { get; set; }
        public DateTime? DTA_RECEBIMENTO { get; set; }
        public int? IND_MANIFESTO { get; set; }
        public string? DES_XML { get; set; }
        public string? DES_OBSERVACAO_OPERACAO { get; set; }
        public DateTime? DTA_EVENTO { get; set; }
        public int? IND_SITUACAO_NOTA { get; set; }
        public int? NUM_NOTA { get; set; }
        public string? DES_SERIE { get; set; }
        public bool? TIP_ALERTA_CONSULTA { get; set; }
        public DateTime? DTA_ALERTA_CONSULTA { get; set; }
        public bool? TIP_ALERTA_CONFIRMACAO_OPERACAO { get; set; }
        public DateTime? DTA_ALERTA_CONFIRMACAO_OPERACAO { get; set; }

        public virtual GE_EMPRESAS? COD_EMPRESANavigation { get; set; }
    }
}