// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class FT_MDFE_SEGURO_CARGA
    {
        public int COD_MDFE_SEGURO_CARGA { get; set; }
        public int COD_MDFE { get; set; }
        public int COD_EMPRESA { get; set; }
        public int COD_ORGANIZACAO { get; set; }
        public int? IND_RESPONSAVEL_SEGURO { get; set; }
        public string? NUM_CPF_CNPJ_RESPONSAVEL { get; set; }
        public string? NUM_APOLICE { get; set; }
        public string? NUM_AVERBACAO { get; set; }
        public int? COD_SEGURADORA { get; set; }

        public virtual GE_EMPRESAS COD_EMPRESANavigation { get; set; } = null!;
        public virtual FT_MDFE COD_MDFENavigation { get; set; } = null!;
        public virtual GE_ORGANIZACAO COD_ORGANIZACAONavigation { get; set; } = null!;
        public virtual GE_SEGURADORAS? COD_SEGURADORANavigation { get; set; }
    }
}