// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class FT_MDFE
    {
        public FT_MDFE()
        {
            FT_MDFE_CARREGAMENTOS = new HashSet<FT_MDFE_CARREGAMENTOS>();
            FT_MDFE_CONDUTOR = new HashSet<FT_MDFE_CONDUTOR>();
            FT_MDFE_EVENTOS = new HashSet<FT_MDFE_EVENTOS>();
            FT_MDFE_NFE = new HashSet<FT_MDFE_NFE>();
            FT_MDFE_PERCURSO = new HashSet<FT_MDFE_PERCURSO>();
            FT_MDFE_REBOQUE = new HashSet<FT_MDFE_REBOQUE>();
            FT_MDFE_SEGURO_CARGA = new HashSet<FT_MDFE_SEGURO_CARGA>();
            FT_MDFE_XML_ENVIADAS = new HashSet<FT_MDFE_XML_ENVIADAS>();
        }

        public int COD_MDFE { get; set; }
        public int COD_EMPRESA { get; set; }
        public int COD_ORGANIZACAO { get; set; }
        public int NUM_MDFE { get; set; }
        public string? NUM_SERIE { get; set; }
        public int? IND_TIPO_EMITENTE { get; set; }
        public int? COD_TIPO_TRANSPORTADOR { get; set; }
        public string? COD_MODELO_NOTA { get; set; }
        public DateTime? DTA_EMISSAO { get; set; }
        public string? DES_CHAVE_ACESSO { get; set; }
        public string? COD_CHAVE { get; set; }
        public string? NUM_DIGITO_CHAVE { get; set; }
        public int? COD_UF_CARREGAMENTO { get; set; }
        public int? COD_UF_DESCARREGAMENTO { get; set; }
        public decimal? VLR_TOTAL { get; set; }
        public int? IND_UNIDADE_MEDIDA_PESO { get; set; }
        public decimal? QTD_PESO_BRUTO { get; set; }
        public string? DES_MENSAGEM_FISCO { get; set; }
        public string? DES_MENSAGEM { get; set; }
        public int? COD_VEICULO { get; set; }
        public string? NUM_PLACA { get; set; }
        public string? NUM_RENAVAM { get; set; }
        public int? NUM_TARA_KG { get; set; }
        public int? NUM_CAPACIDADE_KG { get; set; }
        public int? NUM_CAPACIDADE_M3 { get; set; }
        public string? COD_TIPO_RODADO { get; set; }
        public string? COD_TIPO_CARROCERIA { get; set; }
        public int? COD_UF_LICENCIADO { get; set; }
        public string? NUM_REGISTRO_ANTT { get; set; }
        public string? COD_PROTOCOLO { get; set; }
        public DateTime? DTA_AUTORIZACAO { get; set; }
        public DateTime? DTA_CANCELAMENTO { get; set; }
        public string? COD_PROTOCOLO_CANCELAMENTO { get; set; }
        public DateTime? DTA_ENCERRAMENTO { get; set; }
        public string? COD_PROTOCOLO_ENCERRAMENTO { get; set; }
        public DateTime? DTA_SAIDA { get; set; }
        public string? HMS_SAIDA { get; set; }
        public int? COD_PROPRIETARIO_VEICULO { get; set; }
        public string? NUM_CPF_PROPRIETARO_VEICULO { get; set; }
        public string? NUM_CNPJ_PROPRIETARO_VEICULO { get; set; }
        public string? NUM_RNTRC_PROPRIETARIO_VEICULO { get; set; }
        public string? DES_PROPRIETARIO_VEICULO { get; set; }
        public string? NUM_IE_PROPRIETARIO_VEICULO { get; set; }
        public int? COD_UF_PROPRIETARIO_VEICULO { get; set; }
        public string? COD_TIPO_PROPRIETARIO_VEICULO { get; set; }
        public int? COD_USUARIO { get; set; }
        public string? COD_APLICACAO_EXTERNA { get; set; }

        public virtual GE_EMPRESAS COD_EMPRESANavigation { get; set; } = null!;
        public virtual SW_MODELO_NOTA? COD_MODELO_NOTANavigation { get; set; }
        public virtual GE_ORGANIZACAO COD_ORGANIZACAONavigation { get; set; } = null!;
        public virtual GE_PROPRIETARIO_VEICULOS? COD_PROPRIETARIO_VEICULONavigation { get; set; }
        public virtual SW_TIPO_CARROCERIA? COD_TIPO_CARROCERIANavigation { get; set; }
        public virtual SW_TIPO_PROPRIETARIO? COD_TIPO_PROPRIETARIO_VEICULONavigation { get; set; }
        public virtual SW_TIPO_RODADO? COD_TIPO_RODADONavigation { get; set; }
        public virtual SW_TIPO_TRANSPORTADOR? COD_TIPO_TRANSPORTADORNavigation { get; set; }
        public virtual SW_UF? COD_UF_CARREGAMENTONavigation { get; set; }
        public virtual SW_UF? COD_UF_DESCARREGAMENTONavigation { get; set; }
        public virtual SW_UF? COD_UF_LICENCIADONavigation { get; set; }
        public virtual SW_UF? COD_UF_PROPRIETARIO_VEICULONavigation { get; set; }
        public virtual GE_USUARIOS? COD_USUARIONavigation { get; set; }
        public virtual GE_VEICULOS? COD_VEICULONavigation { get; set; }
        public virtual ICollection<FT_MDFE_CARREGAMENTOS> FT_MDFE_CARREGAMENTOS { get; set; }
        public virtual ICollection<FT_MDFE_CONDUTOR> FT_MDFE_CONDUTOR { get; set; }
        public virtual ICollection<FT_MDFE_EVENTOS> FT_MDFE_EVENTOS { get; set; }
        public virtual ICollection<FT_MDFE_NFE> FT_MDFE_NFE { get; set; }
        public virtual ICollection<FT_MDFE_PERCURSO> FT_MDFE_PERCURSO { get; set; }
        public virtual ICollection<FT_MDFE_REBOQUE> FT_MDFE_REBOQUE { get; set; }
        public virtual ICollection<FT_MDFE_SEGURO_CARGA> FT_MDFE_SEGURO_CARGA { get; set; }
        public virtual ICollection<FT_MDFE_XML_ENVIADAS> FT_MDFE_XML_ENVIADAS { get; set; }
    }
}