// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class FT_MDFE_CONDUTOR
    {
        public int COD_MDFE_CONDUTOR { get; set; }
        public int COD_MDFE { get; set; }
        public int COD_EMPRESA { get; set; }
        public int COD_ORGANIZACAO { get; set; }
        public string? DES_CONDUTOR { get; set; }
        public string? NUM_CPF { get; set; }
        public int? COD_CONDUTOR { get; set; }

        public virtual GE_CONDUTORES? COD_CONDUTORNavigation { get; set; }
        public virtual GE_EMPRESAS COD_EMPRESANavigation { get; set; } = null!;
        public virtual FT_MDFE COD_MDFENavigation { get; set; } = null!;
        public virtual GE_ORGANIZACAO COD_ORGANIZACAONavigation { get; set; } = null!;
    }
}