// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class FT_MDFE_REBOQUE
    {
        public int COD_MDFE_REBOQUE { get; set; }
        public int COD_MDFE { get; set; }
        public int COD_EMPRESA { get; set; }
        public int COD_ORGANIZACAO { get; set; }
        public int? COD_VEICULO { get; set; }
        public string? NUM_PLACA { get; set; }
        public string? COD_RENAVAM { get; set; }
        public int? NUM_TARA_KG { get; set; }
        public int? NUM_CAPACIDADE_KG { get; set; }
        public int? NUM_CAPACIDADE_M3 { get; set; }
        public int? COD_PROPRIETARIO_REBOQUE { get; set; }
        public string? NUM_CPF_PROPRIETARO_REBOQUE { get; set; }
        public string? NUM_CNPJ_PROPRIETARO_REBOQUE { get; set; }
        public string? NUM_RNTRC_PROPRIETARIO_REBOQUE { get; set; }
        public string? DES_PROPRIETARIO_REBOQUE { get; set; }
        public string? NUM_IE_PROPRIETARIO_REBOQUE { get; set; }
        public int? COD_UF_PROPRIETARIO_REBOQUE { get; set; }
        public string? COD_TIPO_PROPRIETARIO_REBOQUE { get; set; }
        public string? COD_TIPO_CARROCERIA_REBOQUE { get; set; }
        public int? COD_UF_LICENCIAMENTO_REBOQUE { get; set; }

        public virtual GE_EMPRESAS COD_EMPRESANavigation { get; set; } = null!;
        public virtual FT_MDFE COD_MDFENavigation { get; set; } = null!;
        public virtual GE_ORGANIZACAO COD_ORGANIZACAONavigation { get; set; } = null!;
        public virtual GE_PROPRIETARIO_VEICULOS? COD_PROPRIETARIO_REBOQUENavigation { get; set; }
        public virtual SW_TIPO_CARROCERIA? COD_TIPO_CARROCERIA_REBOQUENavigation { get; set; }
        public virtual SW_TIPO_PROPRIETARIO? COD_TIPO_PROPRIETARIO_REBOQUENavigation { get; set; }
        public virtual SW_UF? COD_UF_LICENCIAMENTO_REBOQUENavigation { get; set; }
        public virtual SW_UF? COD_UF_PROPRIETARIO_REBOQUENavigation { get; set; }
        public virtual GE_VEICULOS? COD_VEICULONavigation { get; set; }
    }
}