// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class FT_MDFE_EVENTOS
    {
        public int COD_MDFE_EVENTOS { get; set; }
        public int COD_MDFE { get; set; }
        public string? COD_TIPO_EVENTO { get; set; }
        public string? DES_TIPO_EVENTO { get; set; }
        public string? DES_NOME_ARQUIVO { get; set; }
        public DateTime? DTA_EVENTO { get; set; }
        public string? COD_PROTOCOLO { get; set; }
        public string? DES_ARQUIVO_XML { get; set; }
        public int? COD_USUARIO { get; set; }

        public virtual FT_MDFE COD_MDFENavigation { get; set; } = null!;
        public virtual GE_USUARIOS? COD_USUARIONavigation { get; set; }
    }
}