// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class FT_NUMERO_NOTAS
    {
        public int COD_NUMERO_NOTA { get; set; }
        public int COD_EMPRESA { get; set; }
        public int COD_ORGANIZACAO { get; set; }
        public int? NUM_NOTA { get; set; }
        public string DES_SERIE { get; set; } = null!;
        public int IND_TIPO_NOTA { get; set; }
        public bool TIP_PRINCIPAL { get; set; }

        public virtual GE_EMPRESAS COD_EMPRESANavigation { get; set; } = null!;
        public virtual GE_ORGANIZACAO COD_ORGANIZACAONavigation { get; set; } = null!;
    }
}