// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class FT_NOTAS_REFERENCIADAS
    {
        public int COD_NOTA_REFERENCIADA { get; set; }
        public int COD_NOTA { get; set; }
        public int? COD_EMPRESA { get; set; }
        public int COD_ORGANIZACAO { get; set; }
        public string? COD_MODELO_NOTA { get; set; }
        public string? DES_CHAVE_ACESSO { get; set; }
        public int? COD_IBGE_UF { get; set; }
        public DateTime? DTA_EMISSAO { get; set; }
        public string? NUM_CPF_CNPJ { get; set; }
        public string? DES_SERIE { get; set; }
        public int? NUM_NOTA { get; set; }
        public int? IND_TIPO_PESSOA { get; set; }
        public string? NUM_IE { get; set; }
        public string? DES_CHAVE_ACESSO_CTE { get; set; }
        public string? NUM_ECF { get; set; }
        public int? NUM_COO { get; set; }

        public virtual GE_EMPRESAS? COD_EMPRESANavigation { get; set; }
        public virtual SW_UF? COD_IBGE_UFNavigation { get; set; }
        public virtual SW_MODELO_NOTA? COD_MODELO_NOTANavigation { get; set; }
        public virtual FT_NOTAS COD_NOTANavigation { get; set; } = null!;
        public virtual GE_ORGANIZACAO COD_ORGANIZACAONavigation { get; set; } = null!;
    }
}