// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class FT_NOTAS_XML
    {
        public int COD_NOTA_XML { get; set; }
        public int? COD_NOTA { get; set; }
        public DateTime? DTA_EVENTO { get; set; }
        public string? DES_NOME_ARQUIVO { get; set; }
        public string? DES_XML { get; set; }
        public string? DES_OBSERVACAO { get; set; }
        public int? COD_USUARIO { get; set; }
        public string? DES_GUID { get; set; }

        public virtual GE_USUARIOS? COD_USUARIONavigation { get; set; }
    }
}