// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class FT_NOTAS_INUTILIZADAS
    {
        public int COD_INUTILIZACAO { get; set; }
        public int COD_EMPRESA { get; set; }
        public int COD_ORGANIZACAO { get; set; }
        public string DES_SERIE { get; set; } = null!;
        public int NUM_INICIAL { get; set; }
        public int NUM_FINAL { get; set; }
        public string? DES_MOTIVO { get; set; }
        public DateTime DTA_INUTILIZACAO { get; set; }
        public int IND_TIPO_NOTA { get; set; }
        public int? COD_USUARIO { get; set; }
        public string? DES_GUID { get; set; }

        public virtual GE_EMPRESAS COD_EMPRESANavigation { get; set; } = null!;
        public virtual GE_ORGANIZACAO COD_ORGANIZACAONavigation { get; set; } = null!;
        public virtual GE_USUARIOS? COD_USUARIONavigation { get; set; }
    }
}