// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class FT_NOTAS_ITENS_IMPORTACAO_ADICAO
    {
        public int COD_NOTA_ITEM_IMPORTACAO_ADICAO { get; set; }
        public int COD_EMPRESA { get; set; }
        public int COD_ORGANIZACAO { get; set; }
        public int COD_NOTA_ITEM_IMPORTACAO { get; set; }
        public int? NUM_ADICAO { get; set; }
        public int? NUM_SEQUENCIAL { get; set; }
        public string? COD_FABRICANTE { get; set; }
        public decimal? VLR_DESCONTO { get; set; }
        public string? NUM_DRAWBACK { get; set; }

        public virtual GE_EMPRESAS COD_EMPRESANavigation { get; set; } = null!;
        public virtual FT_NOTAS_ITENS_IMPORTACAO COD_NOTA_ITEM_IMPORTACAONavigation { get; set; } = null!;
        public virtual GE_ORGANIZACAO COD_ORGANIZACAONavigation { get; set; } = null!;
    }
}