// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class FT_NOTAS_MENSAGENS
    {
        public int COD_MENSAGEM { get; set; }
        public int? COD_NOTA { get; set; }
        public string? DES_MENSAGEM { get; set; }
        public int? COD_ORGANIZACAO { get; set; }
        public bool? TIP_MENSAGEM_FISCO { get; set; }
        public bool? TIP_SISTEMA { get; set; }
        public bool? TIP_IMPORTACAO { get; set; }
        public string? DES_GUID { get; set; }

        public virtual FT_NOTAS? COD_NOTANavigation { get; set; }
        public virtual GE_ORGANIZACAO? COD_ORGANIZACAONavigation { get; set; }
    }
}