// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class FT_NOTAS_PAGAMENTOS
    {
        public int COD_NOTA_PAGAMENTO { get; set; }
        public int COD_NOTA { get; set; }
        public int COD_EMPRESA { get; set; }
        public int COD_ORGANIZACAO { get; set; }
        public DateTime? DTA_VENCIMENTO { get; set; }
        public string? NUM_FATURA { get; set; }
        public decimal? VLR_FATURA { get; set; }
        public int? COD_TIPO_PAGAMENTO { get; set; }
        public int? COD_CONDICAO_PAGAMENTO { get; set; }
        public decimal? VLR_TROCO { get; set; }
        public int? COD_OPERADORA { get; set; }
        public string? DES_GUID { get; set; }
        public int? NUM_PARCELAS_CARTAO { get; set; }
        public decimal? VLR_TAXA_OPERADORA { get; set; }
        public string? NUM_AUTORIZACAO_CARTAO { get; set; }
        public string? DES_BANDEIRA { get; set; }
        public string? DES_REDE { get; set; }
        public string? DES_NUM_NSU { get; set; }
        public string? DES_NUM_CARTAO_MASK { get; set; }
        public bool? TIP_VENDA_TEF { get; set; }
        public string? DES_CNPJ_CREDENCIADORA { get; set; }

        public virtual GE_CONDICAO_PAGAMENTO? COD_CONDICAO_PAGAMENTONavigation { get; set; }
        public virtual GE_EMPRESAS COD_EMPRESANavigation { get; set; } = null!;
        public virtual FT_NOTAS COD_NOTANavigation { get; set; } = null!;
        public virtual GE_OPERADORAS_CARTAO? COD_OPERADORANavigation { get; set; }
        public virtual GE_ORGANIZACAO COD_ORGANIZACAONavigation { get; set; } = null!;
        public virtual GE_TIPO_PAGAMENTO? COD_TIPO_PAGAMENTONavigation { get; set; }
    }
}