// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class FT_NFSE_XML_ENVIADAS
    {
        public int COD_XML { get; set; }
        public DateTime DTA_EVENTO { get; set; }
        public int? COD_NOTA { get; set; }
        public string DES_NOME_ARQUIVO { get; set; } = null!;
        public string DES_XML { get; set; } = null!;
        public int? TIP_ARQUIVO { get; set; }

        public virtual FT_NOTAS? COD_NOTANavigation { get; set; }
    }
}