// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class FT_NOTAS_ITENS_EXPORTACAO
    {
        public int COD_NOTA_ITEM_EXPORTACAO { get; set; }
        public int COD_NOTA_ITEM { get; set; }
        public string? NUM_DRAWBACK { get; set; }
        public string? NUM_REGISTRO_EXPORTACAO { get; set; }
        public string? NUM_CHAVE_ACESSO { get; set; }
        public decimal? QTD_EXPORTACAO { get; set; }
        public int COD_EMPRESA { get; set; }
        public int COD_ORGANIZACAO { get; set; }

        public virtual GE_EMPRESAS COD_EMPRESANavigation { get; set; } = null!;
        public virtual FT_NOTAS_ITENS COD_NOTA_ITEMNavigation { get; set; } = null!;
        public virtual GE_ORGANIZACAO COD_ORGANIZACAONavigation { get; set; } = null!;
    }
}