// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class FT_NOTAS_ITENS_COMISSAO
    {
        public int COD_COMISSAO { get; set; }
        public int COD_ITEM { get; set; }
        public int COD_REPRESENTANTE { get; set; }
        public decimal PER_COMISSAO { get; set; }
        public decimal VLR_BASE_COMISSAO { get; set; }
        public decimal? VLR_COMISSAO { get; set; }
        public decimal VLR_DEVOLUCAO { get; set; }
        public string? DES_GUID { get; set; }

        public virtual FT_NOTAS_ITENS COD_ITEMNavigation { get; set; } = null!;
        public virtual PS_PESSOAS COD_REPRESENTANTENavigation { get; set; } = null!;
    }
}