// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class FT_PEDIDOS_ITENS
    {
        public FT_PEDIDOS_ITENS()
        {
            FT_LIBERACAO_MARGEM_MINIMA = new HashSet<FT_LIBERACAO_MARGEM_MINIMA>();
            FT_PEDIDOS_ITENS_COMISSAO = new HashSet<FT_PEDIDOS_ITENS_COMISSAO>();
        }

        public int COD_ITEM { get; set; }
        public int? COD_PEDIDO { get; set; }
        public int? COD_ORGANIZACAO { get; set; }
        public int NUM_SEQUENCIA { get; set; }
        public int? COD_PRODUTO { get; set; }
        public string? DES_PRODUTO { get; set; }
        public int COD_UNIDADE_MEDIDA { get; set; }
        public int? COD_CLASSIFICACAO_FISCAL { get; set; }
        public int COD_OPERACAO_FISCAL { get; set; }
        public decimal? QTD_PRODUTO { get; set; }
        public decimal? VLR_UNITARIO { get; set; }
        public decimal? VLR_MERCADORIA { get; set; }
        public decimal? VLR_TOTAL { get; set; }
        public decimal? PER_DESCONTO { get; set; }
        public decimal? VLR_DESCONTO { get; set; }
        public decimal? VLR_BASE_PIS { get; set; }
        public decimal? PER_PIS { get; set; }
        public decimal? VLR_PIS { get; set; }
        public decimal? VLR_BASE_COFINS { get; set; }
        public decimal? PER_COFINS { get; set; }
        public decimal? VLR_COFINS { get; set; }
        public decimal? VLR_BASE_ISS { get; set; }
        public decimal? PER_ISS { get; set; }
        public decimal? VLR_ISS { get; set; }
        public decimal? VLR_BASE_IR { get; set; }
        public decimal? PER_IR { get; set; }
        public decimal? VLR_IR { get; set; }
        public decimal? VLR_BASE_CSLL { get; set; }
        public decimal? PER_CSLL { get; set; }
        public decimal? VLR_CSLL { get; set; }
        public decimal? VLR_BASE_INSS { get; set; }
        public decimal? PER_INSS { get; set; }
        public decimal? VLR_INSS { get; set; }
        public decimal? VLR_BASE_ICMS { get; set; }
        public decimal? PER_ICMS { get; set; }
        public decimal? VLR_ICMS { get; set; }
        public decimal? VLR_ICMS_DIFERIDO { get; set; }
        public decimal? VLR_ICMS_OPERACAO_DIFERIMENTO { get; set; }
        public decimal? VLR_BASE_IPI { get; set; }
        public decimal? PER_IPI { get; set; }
        public decimal? VLR_IPI { get; set; }
        public string? DES_INFORMACAO_ADICIONAL { get; set; }
        public decimal? VLR_FRETE { get; set; }
        public decimal? VLR_DESPESAS { get; set; }
        public decimal? VLR_SEGURO { get; set; }
        public decimal? VLR_BASE_PIS_ST { get; set; }
        public decimal? VLR_PIS_ST { get; set; }
        public decimal? PER_PIS_ST { get; set; }
        public decimal? VLR_BASE_COFINS_ST { get; set; }
        public decimal? VLR_COFINS_ST { get; set; }
        public decimal? PER_COFINS_ST { get; set; }
        public decimal? VLR_BASE_ST { get; set; }
        public decimal? VLR_ST { get; set; }
        public decimal? PER_MVA { get; set; }
        public decimal? PER_ICMS_INTERNO { get; set; }
        public decimal? PER_REDUCAO_BASE_ST { get; set; }
        public decimal? VLR_BASE_FUNDO_COMBATE_POBREZA { get; set; }
        public decimal? PER_FUNDO_COMBATE_POBREZA { get; set; }
        public decimal? VLR_FUNDO_COMBATE_POBREZA { get; set; }
        public decimal? PER_ICMS_INTERESTADUAL { get; set; }
        public decimal? PER_ICMS_PARTILHA { get; set; }
        public decimal? VLR_ICMS_INTERESTADUAL_ORIGEM { get; set; }
        public decimal? VLR_ICMS_INTERESTADUAL_DESTINO { get; set; }
        public decimal? VLR_BASE_ICMS_DESTINO { get; set; }
        public int? COD_ALMOXARIFADO { get; set; }
        public int? COD_PRODUTO_ALMOXARIFADO { get; set; }
        public decimal? VLR_BASE_IMPOSTO_IMPORTACAO { get; set; }
        public decimal? VLR_IMPOSTO_IMPORTACAO { get; set; }
        public decimal? PER_IMPOSTO_IMPORTACAO { get; set; }
        public decimal? VLR_DESPESAS_ADUANEIRAS { get; set; }
        public decimal? VLR_BASE_ST_RETIDO { get; set; }
        public decimal? VLR_ST_RETIDO { get; set; }
        public decimal? PER_ICMS_ST_RETIDO { get; set; }
        public decimal? VLR_ICMS_SUBSTITUTO { get; set; }
        public decimal? VLR_BASE_FUNDO_COMBATE_POBREZA_ST { get; set; }
        public decimal? VLR_FUNDO_COMBATE_POBREZA_ST { get; set; }
        public string? NUM_CST_ICMS { get; set; }
        public string? COD_ORIGEM_MERCADORIA { get; set; }
        public int? COD_CFOP { get; set; }
        public decimal? VLR_BASE_ICMS_SIMPLES_ST { get; set; }
        public decimal? VLR_ICMS_SIMPLES_ST { get; set; }
        public decimal? PER_ICMS_SIMPLES_ST { get; set; }
        public decimal? VLR_BASE_ICMS_EFETIVA { get; set; }
        public decimal? PER_ICMS_EFETIVA { get; set; }
        public decimal? VLR_ICMS_EFETIVA { get; set; }
        public decimal? PER_IMPOSTO_FEDERAL { get; set; }
        public decimal? VLR_IMPOSTO_FEDERAL { get; set; }
        public decimal? PER_IMPOSTO_ESTADUAL { get; set; }
        public decimal? VLR_IMPOSTO_ESTADUAL { get; set; }
        public decimal? PER_IMPOSTO_MUNICIPAL { get; set; }
        public decimal? VLR_IMPOSTO_MUNICIPAL { get; set; }
        public decimal? PER_REDUCAO_BASE_EFETIVA { get; set; }
        public string? NUM_PEDIDO_COMPRA { get; set; }
        public int? NUM_SEQUENCIA_PEDIDO_COMPRA { get; set; }
        public decimal? QTD_ATENDIDA { get; set; }
        public string? NUM_FCI { get; set; }
        public int? COD_PROMOCAO_ITEM { get; set; }
        public int? IND_TABELA_PROMOCAO { get; set; }
        public decimal? QTD_CONVERTIDA { get; set; }
        public int? COD_UNIDADE_CONVERSAO { get; set; }
        public int? IND_TIPO_FATOR { get; set; }
        public decimal? QTD_FATOR_CONVERSAO { get; set; }
        public int? COD_CONTA_CONTABIL { get; set; }
        public int? COD_CENTRO_CUSTO { get; set; }
        public string? DES_GUID { get; set; }
        public string? COD_UNIDADE_MEDIDA_TRIBUTAVEL { get; set; }
        public decimal? VLR_FATOR_CONVERSAO_TRIBUTAVEL { get; set; }
        public decimal? VLR_ICMS_DESONERADO { get; set; }
        public decimal? VLR_PIS_DESONERADO { get; set; }
        public decimal? VLR_COFINS_DESONERADO { get; set; }

        public virtual GE_ALMOXARIFADOS? COD_ALMOXARIFADONavigation { get; set; }
        public virtual GE_CENTRO_CUSTOS? COD_CENTRO_CUSTONavigation { get; set; }
        public virtual GE_CLASSIFICACAO_FISCAL? COD_CLASSIFICACAO_FISCALNavigation { get; set; }
        public virtual GE_CONTAS_CONTABEIS? COD_CONTA_CONTABILNavigation { get; set; }
        public virtual GE_OPERACAO_FISCAL COD_OPERACAO_FISCALNavigation { get; set; } = null!;
        public virtual SW_ORIGEM_MERCADORIAS? COD_ORIGEM_MERCADORIANavigation { get; set; }
        public virtual FT_PEDIDOS? COD_PEDIDONavigation { get; set; }
        public virtual CE_PRODUTOS? COD_PRODUTONavigation { get; set; }
        public virtual CE_PRODUTO_ALMOXARIFADOS? COD_PRODUTO_ALMOXARIFADONavigation { get; set; }
        public virtual GE_UNIDADE_MEDIDA? COD_UNIDADE_CONVERSAONavigation { get; set; }
        public virtual GE_UNIDADE_MEDIDA COD_UNIDADE_MEDIDANavigation { get; set; } = null!;
        public virtual ICollection<FT_LIBERACAO_MARGEM_MINIMA> FT_LIBERACAO_MARGEM_MINIMA { get; set; }
        public virtual ICollection<FT_PEDIDOS_ITENS_COMISSAO> FT_PEDIDOS_ITENS_COMISSAO { get; set; }
    }
}