// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class FT_PEDIDOS_HISTORICOS
    {
        public int COD_HISTORICO { get; set; }
        public int COD_PEDIDO { get; set; }
        public int COD_USUARIO { get; set; }
        public DateTime DTA_HISTORICO { get; set; }
        public int? COD_NOTA { get; set; }
        public int IND_ACAO { get; set; }
        public string? DES_OBSERVACAO { get; set; }

        public virtual FT_NOTAS? COD_NOTANavigation { get; set; }
        public virtual FT_PEDIDOS COD_PEDIDONavigation { get; set; } = null!;
        public virtual GE_USUARIOS COD_USUARIONavigation { get; set; } = null!;
    }
}