// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class FT_PEDIDOS_REPRESENTANTES
    {
        public int COD_PEDIDO_REPRESENTANTE { get; set; }
        public int COD_PEDIDO { get; set; }
        public int COD_PESSOA { get; set; }
        public decimal? VLR_BASE_COMISSAO { get; set; }
        public decimal? PER_COMISSAO { get; set; }
        public decimal? VLR_COMISSAO { get; set; }
        public bool? TIP_REPRESENTE_PRINCIPAL_CLIENTE { get; set; }
        public int? NUM_SEQUENCIA_PREPOSTO { get; set; }
        public int? NUM_SEQUENCIA { get; set; }
        public string? DES_GUID { get; set; }

        public virtual FT_PEDIDOS COD_PEDIDONavigation { get; set; } = null!;
        public virtual PS_PESSOAS COD_PESSOANavigation { get; set; } = null!;
    }
}