// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class FT_PEDIDOS_NOTAS
    {
        public int COD_PEDIDO_NOTA { get; set; }
        public int COD_PEDIDO { get; set; }
        public int COD_NOTA { get; set; }
        public string? DES_GUID { get; set; }

        public virtual FT_NOTAS COD_NOTANavigation { get; set; } = null!;
        public virtual FT_PEDIDOS COD_PEDIDONavigation { get; set; } = null!;
    }
}