// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class FT_PARAMETROS_FORNECEDORES_MANIFESTO
    {
        public int COD_PARAMETRO_FORNECEDOR_MANIFESTO { get; set; }
        public int COD_PESSOA { get; set; }
        public int COD_EMPRESA { get; set; }
        public int COD_PARAMETRO { get; set; }

        public virtual GE_EMPRESAS COD_EMPRESANavigation { get; set; } = null!;
        public virtual FT_PARAMETROS COD_PARAMETRONavigation { get; set; } = null!;
        public virtual PS_PESSOAS COD_PESSOANavigation { get; set; } = null!;
    }
}