// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class FT_PEDIDOS_PAGAMENTOS
    {
        public int COD_PEDIDO_PAGAMENTO { get; set; }
        public int COD_PEDIDO { get; set; }
        public int COD_EMPRESA { get; set; }
        public int COD_ORGANIZACAO { get; set; }
        public DateTime? DTA_VENCIMENTO { get; set; }
        public decimal? VLR_FATURA { get; set; }
        public int? COD_TIPO_PAGAMENTO { get; set; }
        public int? COD_CONDICAO_PAGAMENTO { get; set; }
        public string? DES_OBSERVACAO { get; set; }
        public int? COD_BANCO { get; set; }
        public string? DES_GUID { get; set; }

        public virtual GE_BANCOS? COD_BANCONavigation { get; set; }
        public virtual GE_CONDICAO_PAGAMENTO? COD_CONDICAO_PAGAMENTONavigation { get; set; }
        public virtual GE_EMPRESAS COD_EMPRESANavigation { get; set; } = null!;
        public virtual GE_ORGANIZACAO COD_ORGANIZACAONavigation { get; set; } = null!;
        public virtual FT_PEDIDOS COD_PEDIDONavigation { get; set; } = null!;
        public virtual GE_TIPO_PAGAMENTO? COD_TIPO_PAGAMENTONavigation { get; set; }
    }
}