// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class FT_PARAMETROS
    {
        public FT_PARAMETROS()
        {
            FT_PARAMETROS_FORNECEDORES_MANIFESTO = new HashSet<FT_PARAMETROS_FORNECEDORES_MANIFESTO>();
        }

        public int COD_EMPRESA { get; set; }
        public int COD_ORGANIZACAO { get; set; }
        public decimal? VLR_RETER_IR { get; set; }
        public decimal? VLR_RETER_PIS { get; set; }
        public int? IND_RETER_IR { get; set; }
        public int? IND_RETER_PIS { get; set; }
        public int? IND_AMBIENTE_NFSE { get; set; }
        public decimal VLR_HORA_SERVICO { get; set; }
        public decimal? PER_ICMS_PARTILHA { get; set; }
        public decimal? PER_ICMS_SIMPLES_NACIONAL { get; set; }
        public int? NUM_ULTIMO_MDFE { get; set; }
        public string? NUM_SERIE_MDFE { get; set; }
        public int? IND_AMBIENTE_MDFE { get; set; }
        public int? NUM_LOTE_MDFE { get; set; }
        public int? COD_PESSOA_NAO_IDENTIFICADA { get; set; }
        public int? IND_AMBIENTE_NFCE { get; set; }
        public int? NUM_LOTE_NOTAS { get; set; }
        public string? DES_TOKEN_ID { get; set; }
        public string? DES_TOKEN { get; set; }
        public int? IND_IMPRESSAO_NFCE { get; set; }
        public int? IND_AMBIENTE_NFE { get; set; }
        public int? NUM_LOTE_NFSE { get; set; }
        public int? NUM_RPS_NFSE { get; set; }
        public string? DES_SERIE_RPS_NFSE { get; set; }
        public bool? TIP_VERIFICAR_AUTOMATICAMENTE_CONSULTA_MANIFESTO_DESTINARIO { get; set; }
        public decimal? VLR_MAXIMO_GERAL_CONFIRMACAO_AUTOMATICA { get; set; }
        public bool? TIP_CONFIRMAR_OPERACAO_IMPORTAR_MANIFESTACAO_AUTOMATICA { get; set; }
        public int? NUM_NSU_INICIAL_MANIFESTO_DESTINATARIO { get; set; }
        public decimal? PER_DESCONTO_MAXIMO { get; set; }
        public bool? TIP_NAO_VALIDAR_ESTOQUE_PEDIDO { get; set; }
        public int? NUM_ULTIMA_NOTA_FATURA_SERVICO { get; set; }
        public string? DES_OBSERVACAO_NOTA_FATURA_SERVICO { get; set; }
        public DateTime? DTA_ULTIMA_CONSULTA_MANIFESTO { get; set; }
        public int? NUM_ULTIMO_NSU_MANIFESTO { get; set; }
        public int? NUM_MAXIMO_NSU_MANIFESTO { get; set; }
        public decimal? PER_MARGEM_LUCRO { get; set; }
        public decimal? PER_MARGEM_VENDA_MINIMA { get; set; }
        public int? IND_COMPORTAMENTO_MARGEM { get; set; }
        public bool? TIP_ATUALIZA_PRECO_SUGERIDO { get; set; }
        public bool? TIP_ATUALIZA_PRECO_VENDA { get; set; }
        public int? COD_PRODUTO_SERVICO_FRANQUIAS { get; set; }
        public int? COD_MODELO_PEDIDO { get; set; }
        public int? COD_CANAL_VENDAS_NFCE { get; set; }
        public bool? TIP_OBRIGAR_REPRESENTANTE_PDV { get; set; }
        public string? DES_RODAPE_PEDIDO { get; set; }
        public bool? TIP_OBRIGAR_CANAL_VENDAS { get; set; }
        public bool? TIP_BLOBQUEAR_VALOR_UNITARIO_NFCE { get; set; }
        public int? IND_CONTINGENCIA_NFE { get; set; }
        public DateTime? DTA_CONTINGENCIA { get; set; }
        public string? DES_MOTIVO_CONTINGENCIA { get; set; }
        public bool TIP_IMPRIME_REFERENCIA_PRODUTO { get; set; }
        public bool? TIP_DESCONTO_TITULO { get; set; }
        public bool? TIP_TITULO_ABERTO_GERA_TITULO { get; set; }
        public bool? TIP_TITULO_PAGO_GERA_TITULO { get; set; }
        public bool? TIP_GERA_QRCODE { get; set; }
        public int? COD_MODELO_PEDIDO_RESUMIDA { get; set; }
        public int? IND_COMPORTAMENTO_DESCONTO { get; set; }
        public bool? TIP_CENTRALIZAR_LOGO { get; set; }
        public int? NUM_NSU_INICIAL_CONHECIMENTO_TRANSPORTE { get; set; }
        public DateTime? DTA_ULTIMA_CONSULTA_CONHECIMENTO_TRANSPORTE { get; set; }
        public int? NUM_ULTIMO_NSU_CONHECIMENTO_TRANSPORTE { get; set; }
        public int? NUM_MAXIMO_NSU_CONHECIMENTO_TRANSPORTE { get; set; }
        public bool? TIP_NAO_IMPRIMIR_ENDERECO_ENTREGA_CAMPO_PROPRIO { get; set; }
        public bool? TIP_CONFIRMAR_OPERACAO_CTE_AUTOMATICA { get; set; }
        public decimal? VLR_MAXIMO_GERAL_CONFIRMACAO_AUTOMATICA_CTE { get; set; }
        public bool? TIP_VERIFICAR_AUTOMATICAMENTE_CONSULTA_CTE { get; set; }
        public int? IND_CONTROLA_APROVACAO_FINANCEIRA { get; set; }
        public bool? TIP_VERIFICAR_AUTOMATICAMENTE_CONSULTA_MANIFESTO_SERVICO { get; set; }
        public bool? TIP_CONFIRMAR_OPERACAO_MANIFESTO_SERVICO_AUTOMATICA { get; set; }
        public decimal? VLR_MAXIMO_GERAL_CONFIRMACAO_AUTOMATICA_MANIFESTO_SERVICO { get; set; }
        public int? NUM_ULTIMO_NSU_MANIFESTO_SERVICO { get; set; }
        public DateTime? DTA_ULTIMA_CONSULTA_MANIFESTO_SERVICO { get; set; }
        public int? NUM_NSU_INICIAL_MANIFESTO_SERVICO { get; set; }
        public int? NUM_MAXIMO_NSU_MANIFESTO_SERVICO { get; set; }
        public bool? TIP_NAO_ATUALIZA_DATA_TITULOS { get; set; }
        public int? IND_LAYOUT_RELATORIO { get; set; }

        public virtual PS_CANAL_VENDAS? COD_CANAL_VENDAS_NFCENavigation { get; set; }
        public virtual GE_EMPRESAS COD_EMPRESANavigation { get; set; } = null!;
        public virtual SW_MODELO_PEDIDO? COD_MODELO_PEDIDONavigation { get; set; }
        public virtual GE_ORGANIZACAO COD_ORGANIZACAONavigation { get; set; } = null!;
        public virtual PS_PESSOAS? COD_PESSOA_NAO_IDENTIFICADANavigation { get; set; }
        public virtual CE_PRODUTOS? COD_PRODUTO_SERVICO_FRANQUIASNavigation { get; set; }
        public virtual ICollection<FT_PARAMETROS_FORNECEDORES_MANIFESTO> FT_PARAMETROS_FORNECEDORES_MANIFESTO { get; set; }
    }
}