// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class FT_PEDIDOS
    {
        public FT_PEDIDOS()
        {
            FT_NOTAS_PEDIDOS_REFERENCIADAS = new HashSet<FT_NOTAS_PEDIDOS_REFERENCIADAS>();
            FT_PEDIDOS_HISTORICOS = new HashSet<FT_PEDIDOS_HISTORICOS>();
            FT_PEDIDOS_ITENS = new HashSet<FT_PEDIDOS_ITENS>();
            FT_PEDIDOS_MENSAGENS = new HashSet<FT_PEDIDOS_MENSAGENS>();
            FT_PEDIDOS_NOTAS = new HashSet<FT_PEDIDOS_NOTAS>();
            FT_PEDIDOS_PAGAMENTOS = new HashSet<FT_PEDIDOS_PAGAMENTOS>();
            FT_PEDIDOS_REPRESENTANTES = new HashSet<FT_PEDIDOS_REPRESENTANTES>();
            SW_PEDIDOS_ISET = new HashSet<SW_PEDIDOS_ISET>();
            SW_PEDIDOS_TRAY = new HashSet<SW_PEDIDOS_TRAY>();
        }

        public int COD_PEDIDO { get; set; }
        public int? COD_ORGANIZACAO { get; set; }
        public int COD_EMPRESA { get; set; }
        public int NUM_PEDIDO { get; set; }
        public int? COD_PESSOA { get; set; }
        public DateTime DTA_EMISSAO { get; set; }
        public int? COD_CONDICAO_PAGAMENTO { get; set; }
        public int? COD_TIPO_PAGAMENTO { get; set; }
        public int? COD_BANCO { get; set; }
        public int? COD_OPERACAO_FISCAL { get; set; }
        public decimal? VLR_MERCADORIA { get; set; }
        public decimal? VLR_TOTAL { get; set; }
        public decimal? PER_DESCONTO { get; set; }
        public decimal? VLR_DESCONTO { get; set; }
        public decimal? VLR_BASE_ISS { get; set; }
        public decimal? VLR_BASE_IR { get; set; }
        public decimal? VLR_BASE_PIS { get; set; }
        public decimal? VLR_BASE_COFINS { get; set; }
        public decimal? VLR_BASE_CSLL { get; set; }
        public decimal? VLR_BASE_INSS { get; set; }
        public decimal? VLR_ISS { get; set; }
        public decimal? VLR_IR { get; set; }
        public decimal? VLR_PIS { get; set; }
        public decimal? VLR_COFINS { get; set; }
        public decimal? VLR_CSLL { get; set; }
        public decimal? VLR_INSS { get; set; }
        public int? COD_CONVENIO { get; set; }
        public decimal VLR_BASE_ISS_RETIDO { get; set; }
        public decimal VLR_ISS_RETIDO { get; set; }
        public bool? TIP_CONSUMIDOR_FINAL { get; set; }
        public string? COD_PRESENCA_COMPRADOR { get; set; }
        public decimal? VLR_BASE_ICMS { get; set; }
        public decimal? VLR_ICMS { get; set; }
        public decimal? VLR_BASE_ST { get; set; }
        public decimal? VLR_ST { get; set; }
        public int? COD_TRANSPORTADORA { get; set; }
        public decimal? VLR_BASE_IPI { get; set; }
        public decimal? VLR_IPI { get; set; }
        public decimal? VLR_FRETE { get; set; }
        public decimal? VLR_SEGURO { get; set; }
        public decimal? VLR_DESPESA { get; set; }
        public string? COD_MODALIDADE_FRETE { get; set; }
        public string? DES_PLACA_VEICULO { get; set; }
        public string? DES_MARCA { get; set; }
        public string? DES_ESPECIE { get; set; }
        public int? QTD_VOLUMES { get; set; }
        public decimal? QTD_PESO_LIQUIDO { get; set; }
        public decimal? QTD_PESO_BRUTO { get; set; }
        public decimal? VLR_BASE_FUNDO_COMBATE_POBREZA { get; set; }
        public decimal? VLR_FUNDO_COMBATE_POBREZA { get; set; }
        public decimal? VLR_ICMS_INTERESTADUAL_ORIGEM { get; set; }
        public decimal? VLR_ICMS_INTERESTADUAL_DESTINO { get; set; }
        public int? COD_UF_EMBARQUE { get; set; }
        public string? DES_LOCAL_EMBARQUE { get; set; }
        public string? COD_LOCAL_DESTINO { get; set; }
        public bool? TIP_CALCULO_AUTOMATICO { get; set; }
        public decimal? VLR_BASE_IMPOSTO_IMPORTACAO { get; set; }
        public decimal? VLR_IMPOSTO_IMPORTACAO { get; set; }
        public decimal? VLR_BASE_FUNDO_COMBATE_POBREZA_ST { get; set; }
        public decimal? VLR_FUNDO_COMBATE_POBREZA_ST { get; set; }
        public string? DES_PESSOA { get; set; }
        public string? NUM_CPF_CNPJ { get; set; }
        public int? COD_USUARIO_EMISSAO { get; set; }
        public decimal? VLR_BASE_ICMS_SIMPLES_ST { get; set; }
        public decimal? VLR_ICMS_SIMPLES_ST { get; set; }
        public decimal? VLR_BASE_IMPOSTO { get; set; }
        public decimal? PER_IMPOSTO_FEDERAL { get; set; }
        public decimal? VLR_IMPOSTO_FEDERAL { get; set; }
        public decimal? PER_IMPOSTO_ESTADUAL { get; set; }
        public decimal? VLR_IMPOSTO_ESTADUAL { get; set; }
        public decimal? PER_IMPOSTO_MUNICIPAL { get; set; }
        public decimal? VLR_IMPOSTO_MUNICIPAL { get; set; }
        public int? IND_PEDIDO { get; set; }
        public DateTime? DTA_ENTREGA { get; set; }
        public int? COD_STATUS { get; set; }
        public string? DES_COMPOSICAO_PAGAMENTO { get; set; }
        public string? DES_OBSERVACAO { get; set; }
        public int? COD_INTERMEDIADOR { get; set; }
        public int? COD_ORIGEM { get; set; }
        public int? COD_TRANSPORTADORA_REDESPACHO { get; set; }
        public int? COD_CANAL_VENDAS { get; set; }
        public DateTime? DTA_CRIACAO { get; set; }
        public DateTime? DTA_CONVERSAO_PEDIDO { get; set; }
        public string? DES_GUID { get; set; }
        public decimal? VLR_ICMS_DESONERADO { get; set; }
        public decimal? VLR_PIS_DESONERADO { get; set; }
        public decimal? VLR_COFINS_DESONERADO { get; set; }
        public int? COD_USUARIO_APROVACAO { get; set; }
        public DateTime? DTA_APROVACAO { get; set; }
        public DateTime? DTA_APROVACAO_CLIENTE { get; set; }
        public int? COD_LISTA_PRECO { get; set; }

        public virtual GE_BANCOS? COD_BANCONavigation { get; set; }
        public virtual PS_CANAL_VENDAS? COD_CANAL_VENDASNavigation { get; set; }
        public virtual GE_CONDICAO_PAGAMENTO? COD_CONDICAO_PAGAMENTONavigation { get; set; }
        public virtual CR_CONVENIOS_BANCARIOS? COD_CONVENIONavigation { get; set; }
        public virtual GE_EMPRESAS COD_EMPRESANavigation { get; set; } = null!;
        public virtual GE_INTERMEDIADOR? COD_INTERMEDIADORNavigation { get; set; }
        public virtual SW_LOCAL_DESTINO_OPERACAO? COD_LOCAL_DESTINONavigation { get; set; }
        public virtual SW_MODALIDADES_FRETE? COD_MODALIDADE_FRETENavigation { get; set; }
        public virtual GE_OPERACAO_FISCAL? COD_OPERACAO_FISCALNavigation { get; set; }
        public virtual GE_ORGANIZACAO? COD_ORGANIZACAONavigation { get; set; }
        public virtual SW_ORIGEM_PEDIDO? COD_ORIGEMNavigation { get; set; }
        public virtual PS_PESSOAS? COD_PESSOANavigation { get; set; }
        public virtual SW_PRESENCA_COMPRADOR? COD_PRESENCA_COMPRADORNavigation { get; set; }
        public virtual SW_STATUS_PEDIDO? COD_STATUSNavigation { get; set; }
        public virtual GE_TIPO_PAGAMENTO? COD_TIPO_PAGAMENTONavigation { get; set; }
        public virtual PS_PESSOAS? COD_TRANSPORTADORANavigation { get; set; }
        public virtual PS_PESSOAS? COD_TRANSPORTADORA_REDESPACHONavigation { get; set; }
        public virtual SW_UF? COD_UF_EMBARQUENavigation { get; set; }
        public virtual GE_USUARIOS? COD_USUARIO_APROVACAONavigation { get; set; }
        public virtual GE_USUARIOS? COD_USUARIO_EMISSAONavigation { get; set; }
        public virtual ICollection<FT_NOTAS_PEDIDOS_REFERENCIADAS> FT_NOTAS_PEDIDOS_REFERENCIADAS { get; set; }
        public virtual ICollection<FT_PEDIDOS_HISTORICOS> FT_PEDIDOS_HISTORICOS { get; set; }
        public virtual ICollection<FT_PEDIDOS_ITENS> FT_PEDIDOS_ITENS { get; set; }
        public virtual ICollection<FT_PEDIDOS_MENSAGENS> FT_PEDIDOS_MENSAGENS { get; set; }
        public virtual ICollection<FT_PEDIDOS_NOTAS> FT_PEDIDOS_NOTAS { get; set; }
        public virtual ICollection<FT_PEDIDOS_PAGAMENTOS> FT_PEDIDOS_PAGAMENTOS { get; set; }
        public virtual ICollection<FT_PEDIDOS_REPRESENTANTES> FT_PEDIDOS_REPRESENTANTES { get; set; }
        public virtual ICollection<SW_PEDIDOS_ISET> SW_PEDIDOS_ISET { get; set; }
        public virtual ICollection<SW_PEDIDOS_TRAY> SW_PEDIDOS_TRAY { get; set; }
    }
}