// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class FT_RETENCAO_IR
    {
        public int COD_RETENCAO_IR { get; set; }
        public int COD_NOTA { get; set; }
        public int COD_NOTA_RETIDA { get; set; }

        public virtual FT_NOTAS COD_NOTANavigation { get; set; } = null!;
        public virtual FT_NOTAS COD_NOTA_RETIDANavigation { get; set; } = null!;
    }
}