// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class GE_ALERTAS_PROCESSOS_PESSOAS
    {
        public int COD_ALERTA_PROCESSOS_PESSOA { get; set; }
        public int COD_ALERTA_PROCESSO { get; set; }
        public int COD_PESSOA { get; set; }

        public virtual GE_ALERTAS_PROCESSOS COD_ALERTA_PROCESSONavigation { get; set; } = null!;
        public virtual PS_PESSOAS COD_PESSOANavigation { get; set; } = null!;
    }
}