// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class GE_ALERTAS
    {
        public int COD_ALERTA { get; set; }
        public int? COD_TIPO_ALERTA { get; set; }
        public int? COD_USUARIO_DESTINO { get; set; }
        public DateTime? DTA_CRIACAO { get; set; }
        public string? DES_NOME { get; set; }
        public string? DES_ALERTA { get; set; }
        public DateTime? DTA_LEITURA { get; set; }
        public bool? TIP_VISUALIZACAO { get; set; }
        public int? NUM_ORDEM { get; set; }
        public int COD_ORGANIZACAO { get; set; }
        public string? COD_CHAVE_ENTIDADE { get; set; }

        public virtual GE_ORGANIZACAO COD_ORGANIZACAONavigation { get; set; } = null!;
        public virtual GE_TIPOS_ALERTA? COD_TIPO_ALERTANavigation { get; set; }
        public virtual GE_USUARIOS? COD_USUARIO_DESTINONavigation { get; set; }
    }
}