// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class GE_ALERTAS_USUARIO
    {
        public int COD_TIPO_ALERTA { get; set; }
        public int COD_USUARIO { get; set; }
        public bool? TIP_CONECTADO { get; set; }
        public bool? TIP_EMAIL { get; set; }
        public int COD_ORGANIZACAO { get; set; }

        public virtual GE_ORGANIZACAO COD_ORGANIZACAONavigation { get; set; } = null!;
        public virtual GE_TIPOS_ALERTA COD_TIPO_ALERTANavigation { get; set; } = null!;
        public virtual GE_USUARIOS COD_USUARIONavigation { get; set; } = null!;
    }
}