// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class GE_ALMOXARIFADOS
    {
        public GE_ALMOXARIFADOS()
        {
            CE_INVENTARIOS_PRODUTOS = new HashSet<CE_INVENTARIOS_PRODUTOS>();
            CE_NOTAS_ITENS = new HashSet<CE_NOTAS_ITENS>();
            CE_PRODUTOS_LOTES = new HashSet<CE_PRODUTOS_LOTES>();
            CE_PRODUTO_ALMOXARIFADOS = new HashSet<CE_PRODUTO_ALMOXARIFADOS>();
            CO_ORDENS_ITENS = new HashSet<CO_ORDENS_ITENS>();
            FT_NOTAS_ITENS = new HashSet<FT_NOTAS_ITENS>();
            FT_PEDIDOS_ITENS = new HashSet<FT_PEDIDOS_ITENS>();
            GE_CONFIGURACAO_ALMOXARIFADOS_TRAY = new HashSet<GE_CONFIGURACAO_ALMOXARIFADOS_TRAY>();
            GE_CONFIGURACAO_ALMOXARIFADO_ISET = new HashSet<GE_CONFIGURACAO_ALMOXARIFADO_ISET>();
        }

        public int COD_ALMOXARIFADO { get; set; }
        public string? DES_ALMOXARIFADO { get; set; }
        public bool? TIP_CONSIDERAR_VENDA { get; set; }
        public int COD_EMPRESA { get; set; }
        public int COD_ORGANIZACAO { get; set; }
        public bool? TIP_INCLUIR_NOVO_PRODUTO { get; set; }
        public bool? TIP_CONSIDERAR_COMPRA { get; set; }
        public bool? TIP_NAO_LISTAR_INVENTARIO { get; set; }

        public virtual GE_EMPRESAS COD_EMPRESANavigation { get; set; } = null!;
        public virtual GE_ORGANIZACAO COD_ORGANIZACAONavigation { get; set; } = null!;
        public virtual ICollection<CE_INVENTARIOS_PRODUTOS> CE_INVENTARIOS_PRODUTOS { get; set; }
        public virtual ICollection<CE_NOTAS_ITENS> CE_NOTAS_ITENS { get; set; }
        public virtual ICollection<CE_PRODUTOS_LOTES> CE_PRODUTOS_LOTES { get; set; }
        public virtual ICollection<CE_PRODUTO_ALMOXARIFADOS> CE_PRODUTO_ALMOXARIFADOS { get; set; }
        public virtual ICollection<CO_ORDENS_ITENS> CO_ORDENS_ITENS { get; set; }
        public virtual ICollection<FT_NOTAS_ITENS> FT_NOTAS_ITENS { get; set; }
        public virtual ICollection<FT_PEDIDOS_ITENS> FT_PEDIDOS_ITENS { get; set; }
        public virtual ICollection<GE_CONFIGURACAO_ALMOXARIFADOS_TRAY> GE_CONFIGURACAO_ALMOXARIFADOS_TRAY { get; set; }
        public virtual ICollection<GE_CONFIGURACAO_ALMOXARIFADO_ISET> GE_CONFIGURACAO_ALMOXARIFADO_ISET { get; set; }
    }
}