// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class GE_ALERTAS_PROCESSOS_HISTORICOS
    {
        public int COD_ALERTA_PROCESSOS_HISTORICO { get; set; }
        public int COD_ALERTA_PROCESSOS { get; set; }
        public DateTime DTA_ALERTA { get; set; }
        public bool? TIP_SUCESSO { get; set; }
        public bool? TIP_ERRO { get; set; }
        public string? DES_OBS { get; set; }

        public virtual GE_ALERTAS_PROCESSOS COD_ALERTA_PROCESSOSNavigation { get; set; } = null!;
    }
}