// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class GE_ANEXOS
    {
        public int COD_ANEXO { get; set; }
        public int COD_ORGANIZACAO { get; set; }
        public int COD_EMPRESA { get; set; }
        public int COD_ENTIDADE { get; set; }
        public int COD_REGISTRO { get; set; }
        public string DES_ARQUIVO { get; set; } = null!;
        public int COD_USUARIO { get; set; }
        public DateTime DTA_ANEXO { get; set; }

        public virtual GE_EMPRESAS COD_EMPRESANavigation { get; set; } = null!;
        public virtual SW_ENTIDADES COD_ENTIDADENavigation { get; set; } = null!;
        public virtual GE_ORGANIZACAO COD_ORGANIZACAONavigation { get; set; } = null!;
        public virtual GE_USUARIOS COD_USUARIONavigation { get; set; } = null!;
    }
}