// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class GE_ALERTAS_PROCESSOS
    {
        public GE_ALERTAS_PROCESSOS()
        {
            GE_ALERTAS_PROCESSOS_EMAILS = new HashSet<GE_ALERTAS_PROCESSOS_EMAILS>();
            GE_ALERTAS_PROCESSOS_HISTORICOS = new HashSet<GE_ALERTAS_PROCESSOS_HISTORICOS>();
            GE_ALERTAS_PROCESSOS_PESSOAS = new HashSet<GE_ALERTAS_PROCESSOS_PESSOAS>();
            GE_CONSULTAS = new HashSet<GE_CONSULTAS>();
            GE__ALERTAS_PROCESSOS_FILTROS = new HashSet<GE__ALERTAS_PROCESSOS_FILTROS>();
        }

        public int COD_ALERTA_PROCESSOS { get; set; }
        public int COD_CONTA_PROCESSO { get; set; }
        public bool? TIP_ATIVO { get; set; }
        public int COD_TIPO_ALERTA { get; set; }
        public int? NUM_DIAS { get; set; }
        public int? NUM_SEMANAS { get; set; }
        public int? NUM_MES { get; set; }
        public bool? TIP_SEGUNDA { get; set; }
        public bool? TIP_TERCA { get; set; }
        public bool? TIP_QUARTA { get; set; }
        public bool? TIP_QUINTA { get; set; }
        public bool? TIP_SEXTA { get; set; }
        public bool? TIP_SABADO { get; set; }
        public bool? TIP_DOMINGO { get; set; }
        public string? HMS_HORA { get; set; }
        public DateTime? DTA_ULTIMA_EXECUCAO { get; set; }
        public DateTime? DTA_CRIACAO { get; set; }
        public int COD_USUARIO { get; set; }
        public bool? TIP_EXCEL { get; set; }
        public bool? TIP_PDF { get; set; }
        public string? DES_CRON { get; set; }
        public string? DES_NOME { get; set; }
        public string? COD_HANGFIRE { get; set; }

        public virtual GE_CONTA_EMAIL_PROCESSOS COD_CONTA_PROCESSONavigation { get; set; } = null!;
        public virtual SW_TIPOS_ALERTAS_PROCESSOS COD_TIPO_ALERTANavigation { get; set; } = null!;
        public virtual GE_USUARIOS COD_USUARIONavigation { get; set; } = null!;
        public virtual ICollection<GE_ALERTAS_PROCESSOS_EMAILS> GE_ALERTAS_PROCESSOS_EMAILS { get; set; }
        public virtual ICollection<GE_ALERTAS_PROCESSOS_HISTORICOS> GE_ALERTAS_PROCESSOS_HISTORICOS { get; set; }
        public virtual ICollection<GE_ALERTAS_PROCESSOS_PESSOAS> GE_ALERTAS_PROCESSOS_PESSOAS { get; set; }
        public virtual ICollection<GE_CONSULTAS> GE_CONSULTAS { get; set; }
        public virtual ICollection<GE__ALERTAS_PROCESSOS_FILTROS> GE__ALERTAS_PROCESSOS_FILTROS { get; set; }
    }
}