// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class GE_ANEXOS_EMAIL
    {
        public int COD_ANEXO { get; set; }
        public int COD_ORGANIZACAO { get; set; }
        public int COD_EMAIL { get; set; }
        public string? DES_ANEXO { get; set; }
        public int? COD_EMPRESA { get; set; }
        public string? DES_GUID { get; set; }

        public virtual GE_EMAILS_ENVIADOS COD_EMAILNavigation { get; set; } = null!;
        public virtual GE_EMPRESAS? COD_EMPRESANavigation { get; set; }
        public virtual GE_ORGANIZACAO COD_ORGANIZACAONavigation { get; set; } = null!;
    }
}