// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class GE_ADMINISTRADORES_ORGANIZACAO
    {
        public GE_ADMINISTRADORES_ORGANIZACAO()
        {
            GE_ADMINISTRADORES_ORGANIZACAO_EMPRESAS = new HashSet<GE_ADMINISTRADORES_ORGANIZACAO_EMPRESAS>();
        }

        public int COD_ADMINISTRADOR { get; set; }
        public int COD_USUARIO { get; set; }
        public int COD_ORGANIZACAO { get; set; }

        public virtual GE_ORGANIZACAO COD_ORGANIZACAONavigation { get; set; } = null!;
        public virtual GE_USUARIOS COD_USUARIONavigation { get; set; } = null!;
        public virtual ICollection<GE_ADMINISTRADORES_ORGANIZACAO_EMPRESAS> GE_ADMINISTRADORES_ORGANIZACAO_EMPRESAS { get; set; }
    }
}