// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class GE_APLICACAO_EXTERNA
    {
        public int COD_COD_APLICACAO_EXTERNA { get; set; }
        public string? DES_APLICACAO_EXTERNA { get; set; }
        public string? DES_EMPRESA { get; set; }
        public string? DES_KEY { get; set; }
        public string? OBSERVACAO { get; set; }
        public bool? TIP_ATIVA { get; set; }
        public int COD_ORGANIZACAO { get; set; }
        public int COD_EMPRESA { get; set; }
        public bool? TIP_CONECTADO { get; set; }

        public virtual GE_EMPRESAS COD_EMPRESANavigation { get; set; } = null!;
        public virtual GE_ORGANIZACAO COD_ORGANIZACAONavigation { get; set; } = null!;
    }
}