// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class GE_ALERTAS_PROCESSOS_EMAILS
    {
        public int COD_ALERTA_EMAILS { get; set; }
        public int? COD_ALERTA_PROCESSO { get; set; }
        public string? DES_EMAIL { get; set; }

        public virtual GE_ALERTAS_PROCESSOS? COD_ALERTA_PROCESSONavigation { get; set; }
    }
}