// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class GE_BANCOS
    {
        public GE_BANCOS()
        {
            CO_ORDENS_PAGAMENTOS = new HashSet<CO_ORDENS_PAGAMENTOS>();
            CP_HISTORICO = new HashSet<CP_HISTORICO>();
            CP_TITULOS = new HashSet<CP_TITULOS>();
            CR_HISTORICOS = new HashSet<CR_HISTORICOS>();
            CR_REMESSA_OPEN_BANK = new HashSet<CR_REMESSA_OPEN_BANK>();
            CR_SALDOS = new HashSet<CR_SALDOS>();
            CR_TITULOS = new HashSet<CR_TITULOS>();
            FT_NOTAS = new HashSet<FT_NOTAS>();
            FT_PEDIDOS = new HashSet<FT_PEDIDOS>();
            FT_PEDIDOS_PAGAMENTOS = new HashSet<FT_PEDIDOS_PAGAMENTOS>();
            PS_PESSOAS = new HashSet<PS_PESSOAS>();
        }

        public int COD_BANCO { get; set; }
        public int COD_EMPRESA { get; set; }
        public string DES_BANCO { get; set; } = null!;
        public int? COD_BANCO_HOMOLOGADO { get; set; }
        public int? COD_ORGANIZACAO { get; set; }
        public string? COD_BANCO_COMPE { get; set; }

        public virtual SW_BANCOS_HOMOLOGADOS? COD_BANCO_HOMOLOGADONavigation { get; set; }
        public virtual GE_EMPRESAS COD_EMPRESANavigation { get; set; } = null!;
        public virtual GE_ORGANIZACAO? COD_ORGANIZACAONavigation { get; set; }
        public virtual ICollection<CO_ORDENS_PAGAMENTOS> CO_ORDENS_PAGAMENTOS { get; set; }
        public virtual ICollection<CP_HISTORICO> CP_HISTORICO { get; set; }
        public virtual ICollection<CP_TITULOS> CP_TITULOS { get; set; }
        public virtual ICollection<CR_HISTORICOS> CR_HISTORICOS { get; set; }
        public virtual ICollection<CR_REMESSA_OPEN_BANK> CR_REMESSA_OPEN_BANK { get; set; }
        public virtual ICollection<CR_SALDOS> CR_SALDOS { get; set; }
        public virtual ICollection<CR_TITULOS> CR_TITULOS { get; set; }
        public virtual ICollection<FT_NOTAS> FT_NOTAS { get; set; }
        public virtual ICollection<FT_PEDIDOS> FT_PEDIDOS { get; set; }
        public virtual ICollection<FT_PEDIDOS_PAGAMENTOS> FT_PEDIDOS_PAGAMENTOS { get; set; }
        public virtual ICollection<PS_PESSOAS> PS_PESSOAS { get; set; }
    }
}