// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class GE_CADASTRO_FRENTE_CAIXA
    {
        public GE_CADASTRO_FRENTE_CAIXA()
        {
            CA_ABERTURA_FECHAMENTO = new HashSet<CA_ABERTURA_FECHAMENTO>();
            FT_NOTAS = new HashSet<FT_NOTAS>();
        }

        public int COD_FRENTE_CAIXA { get; set; }
        public int COD_EMPRESA { get; set; }
        public int COD_ORGANIZACAO { get; set; }
        public int COD_USUARIO { get; set; }
        public DateTime DTA_CRIACAO { get; set; }
        public string DES_HASH { get; set; } = null!;
        public DateTime? DTA_ATIVACAO { get; set; }
        public string? DES_NOME { get; set; }
        public DateTime? DTA_DESATIVACAO { get; set; }
        public int? COD_USUARIO_DESATIVACAO { get; set; }
        public string? DES_VERSAO { get; set; }
        public bool? TIP_SISTEMA { get; set; }

        public virtual GE_EMPRESAS COD_EMPRESANavigation { get; set; } = null!;
        public virtual GE_ORGANIZACAO COD_ORGANIZACAONavigation { get; set; } = null!;
        public virtual GE_USUARIOS COD_USUARIONavigation { get; set; } = null!;
        public virtual GE_USUARIOS? COD_USUARIO_DESATIVACAONavigation { get; set; }
        public virtual ICollection<CA_ABERTURA_FECHAMENTO> CA_ABERTURA_FECHAMENTO { get; set; }
        public virtual ICollection<FT_NOTAS> FT_NOTAS { get; set; }
    }
}