// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class GE_CONFIG_PAG_PIX
    {
        public int COD_INTEGRACAO { get; set; }
        public int COD_EMPRESA { get; set; }
        public string? COD_CONTA { get; set; }

        public virtual GE_EMPRESAS COD_EMPRESANavigation { get; set; } = null!;
    }
}