// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class GE_CONDUTORES
    {
        public GE_CONDUTORES()
        {
            FT_MDFE_CONDUTOR = new HashSet<FT_MDFE_CONDUTOR>();
        }

        public int COD_CONDUTOR { get; set; }
        public int COD_EMPRESA { get; set; }
        public int COD_ORGANIZACAO { get; set; }
        public string? DES_CONDUTOR { get; set; }
        public string? NUM_CPF_CONDUTOR { get; set; }

        public virtual GE_EMPRESAS COD_EMPRESANavigation { get; set; } = null!;
        public virtual GE_ORGANIZACAO COD_ORGANIZACAONavigation { get; set; } = null!;
        public virtual ICollection<FT_MDFE_CONDUTOR> FT_MDFE_CONDUTOR { get; set; }
    }
}