// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class GE_CONSULTAS_CONFIGURADAS
    {
        public GE_CONSULTAS_CONFIGURADAS()
        {
            GE_CONSULTAS_CONFIGURADAS_CAMPOS = new HashSet<GE_CONSULTAS_CONFIGURADAS_CAMPOS>();
        }

        public int COD_CONSULTA { get; set; }
        public string DES_NOME { get; set; } = null!;
        public string? DES_OBSERVACAO { get; set; }
        public int COD_FUNCAO { get; set; }
        public DateTime DTA_CRIACAO { get; set; }
        public int COD_USUARIO { get; set; }
        public int? COD_USUARIO_ALTERACAO { get; set; }
        public DateTime? DTA_ALTERACAO { get; set; }
        public int COD_ENTIDADE { get; set; }
        public int COD_EMPRESA { get; set; }

        public virtual GE_EMPRESAS COD_EMPRESANavigation { get; set; } = null!;
        public virtual SW_ENTIDADES COD_ENTIDADENavigation { get; set; } = null!;
        public virtual SW_FUNCOES COD_FUNCAONavigation { get; set; } = null!;
        public virtual GE_USUARIOS COD_USUARIONavigation { get; set; } = null!;
        public virtual GE_USUARIOS? COD_USUARIO_ALTERACAONavigation { get; set; }
        public virtual ICollection<GE_CONSULTAS_CONFIGURADAS_CAMPOS> GE_CONSULTAS_CONFIGURADAS_CAMPOS { get; set; }
    }
}