// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class GE_CONFIG_INTEGRACAO_TRAY
    {
        public int COD_INTEGRACAO { get; set; }
        public string? DES_URL_INTEGRACAO { get; set; }
        public string? DES_REFRESH_TOKEN { get; set; }
        public DateTime? DTA_ATIVACAO { get; set; }
        public DateTime? DTA_EXPIRACAO_TOKEN { get; set; }
        public string? DES_TOKEN { get; set; }
        public bool? TIP_ATIVO { get; set; }
        public int COD_EMPRESA { get; set; }
        public DateTime? DTA_EXPIRACAO_REFRESH_TOKEN { get; set; }
        public string? DES_COD_AUTH { get; set; }
        public string? COD_STORE_ID { get; set; }
        public bool? TIP_ATUALIZAR_NAO_ESTOQUE { get; set; }
        public bool? TIP_ATUALIZAR_NAO_DESCRICAO { get; set; }
        public bool? TIP_ATUALIZAR_NAO_PRECO { get; set; }
        public int? COD_REPRESENTATE { get; set; }
        public decimal? VLR_PER_ESTOQUE_DISPONIVEL { get; set; }
        public int? COD_LISTA_PRECOS { get; set; }
        public int? COD_CANAL_VENDAS { get; set; }
        public DateTime? DTA_ATIVACAO_EVENTOS { get; set; }
        public bool? TIP_INTEGRAR_PEDIDO { get; set; }
        public bool? TIP_CONTROLA_PESO_VARIACAO { get; set; }
        public bool? TIP_DESATIVAR_ATIVAR_PRODUTO { get; set; }
        public bool? TIP_DESCONTO_IPI { get; set; }
        public bool? TIP_NAO_ABATER_TAXA_CARTAO { get; set; }

        public virtual PS_CANAL_VENDAS? COD_CANAL_VENDASNavigation { get; set; }
        public virtual GE_EMPRESAS COD_EMPRESANavigation { get; set; } = null!;
        public virtual GE_LISTA_PRECOS? COD_LISTA_PRECOSNavigation { get; set; }
        public virtual PS_PESSOAS? COD_REPRESENTATENavigation { get; set; }
    }
}