// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class GE_CATEGORIAS_CONSULTAS
    {
        public GE_CATEGORIAS_CONSULTAS()
        {
            GE_CONSULTAS = new HashSet<GE_CONSULTAS>();
            InverseCOD_CATEGORIA_PAINavigation = new HashSet<GE_CATEGORIAS_CONSULTAS>();
        }

        public int COD_CATEGORIA { get; set; }
        public string? DES_CATEGORIA { get; set; }
        public int? COD_ORGANIZACAO { get; set; }
        public int? COD_CATEGORIA_PAI { get; set; }

        public virtual GE_CATEGORIAS_CONSULTAS? COD_CATEGORIA_PAINavigation { get; set; }
        public virtual GE_ORGANIZACAO? COD_ORGANIZACAONavigation { get; set; }
        public virtual ICollection<GE_CONSULTAS> GE_CONSULTAS { get; set; }
        public virtual ICollection<GE_CATEGORIAS_CONSULTAS> InverseCOD_CATEGORIA_PAINavigation { get; set; }
    }
}