// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class GE_CONSULTAS
    {
        public int COD_CONSULTA { get; set; }
        public string? DES_CONSULTA { get; set; }
        public string? DES_OBSERVACAO { get; set; }
        public int? COD_USUARIO { get; set; }
        public int? COD_CATEGORIA { get; set; }
        public int? COD_ORGANIZACAO { get; set; }
        public DateTime? DTA_CRIACAO { get; set; }
        public string? DES_JSON { get; set; }
        public string? DES_SQL { get; set; }
        public int COD_TIPO { get; set; }
        public string? DES_GUID_STORE { get; set; }
        public string? DES_GUID_VERSAO_STORE { get; set; }
        public string? DES_GUID_CONSULTA_EXTERNA { get; set; }
        public int? COD_ALERTA_PROCESSOS { get; set; }

        public virtual GE_ALERTAS_PROCESSOS? COD_ALERTA_PROCESSOSNavigation { get; set; }
        public virtual GE_CATEGORIAS_CONSULTAS? COD_CATEGORIANavigation { get; set; }
        public virtual GE_ORGANIZACAO? COD_ORGANIZACAONavigation { get; set; }
        public virtual SW_TIPO_DE_CONSULTAS COD_TIPONavigation { get; set; } = null!;
        public virtual GE_USUARIOS? COD_USUARIONavigation { get; set; }
    }
}