// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class GE_CIDADES
    {
        public GE_CIDADES()
        {
            CE_NOTAS = new HashSet<CE_NOTAS>();
            FT_MDFE_CARREGAMENTOS = new HashSet<FT_MDFE_CARREGAMENTOS>();
            FT_MDFE_NFE = new HashSet<FT_MDFE_NFE>();
            FT_NOTAS = new HashSet<FT_NOTAS>();
            GE_EMPRESAS = new HashSet<GE_EMPRESAS>();
            PS_ENDERECOS = new HashSet<PS_ENDERECOS>();
        }

        public int COD_CIDADE { get; set; }
        public string? DES_CIDADE { get; set; }
        public int COD_IBGE_CIDADE { get; set; }
        public int COD_IBGE_UF { get; set; }
        public int? COD_ORGANIZACAO { get; set; }

        public virtual SW_UF COD_IBGE_UFNavigation { get; set; } = null!;
        public virtual GE_ORGANIZACAO? COD_ORGANIZACAONavigation { get; set; }
        public virtual ICollection<CE_NOTAS> CE_NOTAS { get; set; }
        public virtual ICollection<FT_MDFE_CARREGAMENTOS> FT_MDFE_CARREGAMENTOS { get; set; }
        public virtual ICollection<FT_MDFE_NFE> FT_MDFE_NFE { get; set; }
        public virtual ICollection<FT_NOTAS> FT_NOTAS { get; set; }
        public virtual ICollection<GE_EMPRESAS> GE_EMPRESAS { get; set; }
        public virtual ICollection<PS_ENDERECOS> PS_ENDERECOS { get; set; }
    }
}