// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class GE_CONTA_EMAIL_PROCESSOS
    {
        public GE_CONTA_EMAIL_PROCESSOS()
        {
            GE_ALERTAS_PROCESSOS = new HashSet<GE_ALERTAS_PROCESSOS>();
        }

        public int COD_CONTA_PROCESSO { get; set; }
        public int? COD_CONTA_EMAIL { get; set; }
        public int? COD_PROCESSO { get; set; }
        public string DES_ASSUNTO { get; set; } = null!;
        public string DES_EMAIL { get; set; } = null!;
        public int COD_EMPRESA { get; set; }
        public int COD_ORGANIZACAO { get; set; }
        public string? DES_MODELO { get; set; }

        public virtual GE_CONTAS_EMAIL? COD_CONTA_EMAILNavigation { get; set; }
        public virtual GE_EMPRESAS COD_EMPRESANavigation { get; set; } = null!;
        public virtual GE_ORGANIZACAO COD_ORGANIZACAONavigation { get; set; } = null!;
        public virtual SW_PROCESSOS? COD_PROCESSONavigation { get; set; }
        public virtual ICollection<GE_ALERTAS_PROCESSOS> GE_ALERTAS_PROCESSOS { get; set; }
    }
}