// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class GE_CHAT
    {
        public long COD_MENSAGEM { get; set; }
        public DateTime? DTA_MENSAGEM { get; set; }
        public int? COD_USUARIO_REMETENTE { get; set; }
        public int? COD_USUARIO_DESTINATARIO { get; set; }
        public string? DES_MENSAGEM { get; set; }
        public DateTime? DTA_LEITURA { get; set; }
        public int COD_ORGANIZACAO { get; set; }

        public virtual GE_ORGANIZACAO COD_ORGANIZACAONavigation { get; set; } = null!;
        public virtual GE_USUARIOS? COD_USUARIO_DESTINATARIONavigation { get; set; }
        public virtual GE_USUARIOS? COD_USUARIO_REMETENTENavigation { get; set; }
    }
}