// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class GE_CLASSIFICACAO_COMPONENTES_DASHBOARD
    {
        public GE_CLASSIFICACAO_COMPONENTES_DASHBOARD()
        {
            GE_COMPONENTES_DASHBOARD = new HashSet<GE_COMPONENTES_DASHBOARD>();
        }

        public int COD_CLASSIFICACAO { get; set; }
        public string DES_CLASSIFICACAO { get; set; } = null!;
        public int COD_EMPRESA { get; set; }
        public int COD_USUARIO { get; set; }
        public DateTime DTA_CRIACAO { get; set; }

        public virtual GE_EMPRESAS COD_EMPRESANavigation { get; set; } = null!;
        public virtual GE_USUARIOS COD_USUARIONavigation { get; set; } = null!;
        public virtual ICollection<GE_COMPONENTES_DASHBOARD> GE_COMPONENTES_DASHBOARD { get; set; }
    }
}