// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class GE_COLABORACAO_DESTINATARIO
    {
        public int COD_COLABORACAO { get; set; }
        public int COD_USUARIO_DESTINATARIO { get; set; }
        public string? DES_EMAIL { get; set; }
        public int COD_ORGANIZACAO { get; set; }

        public virtual GE_ORGANIZACAO COD_ORGANIZACAONavigation { get; set; } = null!;
        public virtual GE_USUARIOS COD_USUARIO_DESTINATARIONavigation { get; set; } = null!;
    }
}