// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class GE_CALENDARIO_FERIADO
    {
        public int COD_FERIADO { get; set; }
        public DateTime DTA_FERIADOSTR { get; set; }
        public int COD_CALENDARIO { get; set; }
        public string? DES_FERIADO { get; set; }
        public int? COD_ORGANIZACAO { get; set; }

        public virtual GE_CALENDARIO COD_CALENDARIONavigation { get; set; } = null!;
        public virtual GE_ORGANIZACAO? COD_ORGANIZACAONavigation { get; set; }
    }
}