// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class GE_COMPARTILHAMENTOS
    {
        public int COD_COMPARTILHAMENTO { get; set; }
        public string NUM_CNPJ_CPF_ORIGEM { get; set; } = null!;
        public string NUM_CNPJ_CPF_DESTINO { get; set; } = null!;
        public int COD_APLICACAO { get; set; }
        public string? DES_COMPARTILHAMENTO { get; set; }
        public DateTime DTA_COMPARTILHAMENTO { get; set; }
        public string DES_USUARIO { get; set; } = null!;
        public string? DES_EMAIL_USUARIO { get; set; }
        public string? DES_OBS { get; set; }
        public int COD_TIPO { get; set; }
        public string? DES_XML { get; set; }
        public string? DES_JSON { get; set; }
        public DateTime? DTA_ALERTA_RECEBIDO { get; set; }
        public bool? TIP_NAO_ALERTAR { get; set; }
        public string DES_GUID { get; set; } = null!;
        public int COD_EMPRESA { get; set; }
        public string? DES_BASE_64 { get; set; }
        public string? DES_TELEFONE { get; set; }
        public string? DES_EMPRESA_EMITENTE { get; set; }
        public DateTime? DTA_DESCARTE { get; set; }
        public int? COD_USUARIO_DESCARTE { get; set; }
        public DateTime? DTA_IMPORTACAO { get; set; }
        public int? COD_USUARIO_IMPORTACAO { get; set; }
        public int? IND_SITUACAO { get; set; }
        public int? NUM_DOCUMENTO_COMPARTILHADO { get; set; }

        public virtual GE_EMPRESAS COD_EMPRESANavigation { get; set; } = null!;
        public virtual GE_TIPO_COMPARTILHAMENTOS COD_TIPONavigation { get; set; } = null!;
        public virtual GE_USUARIOS? COD_USUARIO_DESCARTENavigation { get; set; }
        public virtual GE_USUARIOS? COD_USUARIO_IMPORTACAONavigation { get; set; }
    }
}