// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class GE_CLASSIFICACOES_PRODUTOS
    {
        public GE_CLASSIFICACOES_PRODUTOS()
        {
            CE_PRODUTOS = new HashSet<CE_PRODUTOS>();
            GE_PROMOCOES_CLASSIFICACOES = new HashSet<GE_PROMOCOES_CLASSIFICACOES>();
            InverseCOD_CLASSIFICACAO_PAINavigation = new HashSet<GE_CLASSIFICACOES_PRODUTOS>();
        }

        public int COD_CLASSIFICACAO { get; set; }
        public string? DES_CLASSIFICACAO { get; set; }
        public int? COD_CLASSIFICACAO_PAI { get; set; }
        public int? COD_CATEGORIA { get; set; }
        public int COD_EMPRESA { get; set; }
        public int COD_ORGANIZACAO { get; set; }
        public bool? TIP_VENDER_SEM_ESTOQUE { get; set; }
        public bool? TIP_NAO_LISTAR_INVENTARIO { get; set; }

        public virtual GE_CATEGORIAS_PRODUTOS? COD_CATEGORIANavigation { get; set; }
        public virtual GE_CLASSIFICACOES_PRODUTOS? COD_CLASSIFICACAO_PAINavigation { get; set; }
        public virtual GE_EMPRESAS COD_EMPRESANavigation { get; set; } = null!;
        public virtual GE_ORGANIZACAO COD_ORGANIZACAONavigation { get; set; } = null!;
        public virtual ICollection<CE_PRODUTOS> CE_PRODUTOS { get; set; }
        public virtual ICollection<GE_PROMOCOES_CLASSIFICACOES> GE_PROMOCOES_CLASSIFICACOES { get; set; }
        public virtual ICollection<GE_CLASSIFICACOES_PRODUTOS> InverseCOD_CLASSIFICACAO_PAINavigation { get; set; }
    }
}