// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class GE_CATEGORIAS_PRODUTOS
    {
        public GE_CATEGORIAS_PRODUTOS()
        {
            CE_PRODUTOS = new HashSet<CE_PRODUTOS>();
            GE_CLASSIFICACOES_PRODUTOS = new HashSet<GE_CLASSIFICACOES_PRODUTOS>();
            GE_PROMOCOES_CATEGORIAS = new HashSet<GE_PROMOCOES_CATEGORIAS>();
        }

        public int COD_CATEGORIA { get; set; }
        public string? DES_CATEGORIA { get; set; }
        public int COD_EMPRESA { get; set; }
        public int COD_ORGANIZACAO { get; set; }
        public bool? TIP_VENDER_SEM_ESTOQUE { get; set; }
        public bool? TIP_NAO_LISTAR_INVENTARIO { get; set; }
        public decimal? PER_MARGEM_MINIMA_VENDA { get; set; }
        public decimal? PER_MARGEM_LUCRO { get; set; }
        public int? COD_CATEGORIA_TRAY { get; set; }
        public int? COD_CATEGORIA_ISET { get; set; }
        public int? COD_CATEGORIA_NUVEMSHOP { get; set; }

        public virtual GE_EMPRESAS COD_EMPRESANavigation { get; set; } = null!;
        public virtual GE_ORGANIZACAO COD_ORGANIZACAONavigation { get; set; } = null!;
        public virtual ICollection<CE_PRODUTOS> CE_PRODUTOS { get; set; }
        public virtual ICollection<GE_CLASSIFICACOES_PRODUTOS> GE_CLASSIFICACOES_PRODUTOS { get; set; }
        public virtual ICollection<GE_PROMOCOES_CATEGORIAS> GE_PROMOCOES_CATEGORIAS { get; set; }
    }
}