// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class GE_CONSULTAS_CONFIGURADAS_CAMPOS
    {
        public int COD_CONSULTA_CAMPOS { get; set; }
        public int COD_CONSULTA { get; set; }
        public int COD_ATRIBUTO { get; set; }
        public string DES_CAMINHO_VIRTUAL { get; set; } = null!;
        public string DES_TITULO { get; set; } = null!;
        public int NUM_ORDEM { get; set; }

        public virtual SW_ENTIDADES_ATRIBUTOS COD_ATRIBUTONavigation { get; set; } = null!;
        public virtual GE_CONSULTAS_CONFIGURADAS COD_CONSULTANavigation { get; set; } = null!;
    }
}