// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class GE_CONDICAO_PAGAMENTO
    {
        public GE_CONDICAO_PAGAMENTO()
        {
            CE_NOTAS = new HashSet<CE_NOTAS>();
            CO_ORDENS = new HashSet<CO_ORDENS>();
            CO_ORDENS_PAGAMENTOS = new HashSet<CO_ORDENS_PAGAMENTOS>();
            FT_NOTAS = new HashSet<FT_NOTAS>();
            FT_NOTAS_PAGAMENTOS = new HashSet<FT_NOTAS_PAGAMENTOS>();
            FT_PEDIDOS = new HashSet<FT_PEDIDOS>();
            FT_PEDIDOS_PAGAMENTOS = new HashSet<FT_PEDIDOS_PAGAMENTOS>();
            GE_CONDICAO_PAGAMENTO_ITENS = new HashSet<GE_CONDICAO_PAGAMENTO_ITENS>();
            GE_TIPOS_PAGAMENTOS_CONDICOES_PAGAMENTOS = new HashSet<GE_TIPOS_PAGAMENTOS_CONDICOES_PAGAMENTOS>();
            PS_CLIENTES = new HashSet<PS_CLIENTES>();
            SW_RELACAO_PAGAMENTO_ISET = new HashSet<SW_RELACAO_PAGAMENTO_ISET>();
            SW_RELACAO_PAGAMENTO_TRAY = new HashSet<SW_RELACAO_PAGAMENTO_TRAY>();
        }

        public int COD_CONDICAO_PAGAMENTO { get; set; }
        public string DES_CONDICAO_PAGAMENTO { get; set; } = null!;
        public int COD_EMPRESA { get; set; }
        public int? COD_ORGANIZACAO { get; set; }
        public int? IND_GERAR_TITULOS { get; set; }
        public bool? TIP_PERSONALIZADA { get; set; }
        public string? DES_OBSERVACAO { get; set; }
        public int? IND_TIPO_PARCELA_TEF { get; set; }
        public int? IND_TIPO_PAGAMENTO_TEF { get; set; }

        public virtual GE_EMPRESAS COD_EMPRESANavigation { get; set; } = null!;
        public virtual GE_ORGANIZACAO? COD_ORGANIZACAONavigation { get; set; }
        public virtual ICollection<CE_NOTAS> CE_NOTAS { get; set; }
        public virtual ICollection<CO_ORDENS> CO_ORDENS { get; set; }
        public virtual ICollection<CO_ORDENS_PAGAMENTOS> CO_ORDENS_PAGAMENTOS { get; set; }
        public virtual ICollection<FT_NOTAS> FT_NOTAS { get; set; }
        public virtual ICollection<FT_NOTAS_PAGAMENTOS> FT_NOTAS_PAGAMENTOS { get; set; }
        public virtual ICollection<FT_PEDIDOS> FT_PEDIDOS { get; set; }
        public virtual ICollection<FT_PEDIDOS_PAGAMENTOS> FT_PEDIDOS_PAGAMENTOS { get; set; }
        public virtual ICollection<GE_CONDICAO_PAGAMENTO_ITENS> GE_CONDICAO_PAGAMENTO_ITENS { get; set; }
        public virtual ICollection<GE_TIPOS_PAGAMENTOS_CONDICOES_PAGAMENTOS> GE_TIPOS_PAGAMENTOS_CONDICOES_PAGAMENTOS { get; set; }
        public virtual ICollection<PS_CLIENTES> PS_CLIENTES { get; set; }
        public virtual ICollection<SW_RELACAO_PAGAMENTO_ISET> SW_RELACAO_PAGAMENTO_ISET { get; set; }
        public virtual ICollection<SW_RELACAO_PAGAMENTO_TRAY> SW_RELACAO_PAGAMENTO_TRAY { get; set; }
    }
}