// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class GE_COMPONENTES_DASHBOARD
    {
        public GE_COMPONENTES_DASHBOARD()
        {
            GE_COMPONENTES_PERMISSOES = new HashSet<GE_COMPONENTES_PERMISSOES>();
        }

        public int COD_COMPONENTE { get; set; }
        public string DES_COMPONENTE { get; set; } = null!;
        public string? DES_IFRAME { get; set; }
        public int COD_CLASSIFICACAO { get; set; }
        public int COD_USUARIO { get; set; }
        public DateTime DTA_CRIACAO { get; set; }
        public int COD_TIPO { get; set; }
        public int COD_EMPRESA { get; set; }
        public bool TIP_PUBLICO { get; set; }

        public virtual GE_CLASSIFICACAO_COMPONENTES_DASHBOARD COD_CLASSIFICACAONavigation { get; set; } = null!;
        public virtual GE_EMPRESAS COD_EMPRESANavigation { get; set; } = null!;
        public virtual SW_TIPO_COMPONENTES COD_TIPONavigation { get; set; } = null!;
        public virtual GE_USUARIOS COD_USUARIONavigation { get; set; } = null!;
        public virtual ICollection<GE_COMPONENTES_PERMISSOES> GE_COMPONENTES_PERMISSOES { get; set; }
    }
}