// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class GE_CLASSIFICACAO_FISCAL
    {
        public GE_CLASSIFICACAO_FISCAL()
        {
            CE_PRODUTOS = new HashSet<CE_PRODUTOS>();
            FT_NOTAS_ITENS = new HashSet<FT_NOTAS_ITENS>();
            FT_PEDIDOS_ITENS = new HashSet<FT_PEDIDOS_ITENS>();
            GE_REGRAS_TRIBUTACAO = new HashSet<GE_REGRAS_TRIBUTACAO>();
        }

        public int COD_CLASSIFICACAO_FISCAL { get; set; }
        public string DES_CLASSIFICACAO_FISCAL { get; set; } = null!;
        public string COD_NCM { get; set; } = null!;
        public int COD_EMPRESA { get; set; }
        public int? COD_ORGANIZACAO { get; set; }
        public string? COD_CEST { get; set; }
        public decimal? PER_IPI { get; set; }
        public string? COD_APLICACAO_EXTERNA { get; set; }
        public string? COD_CBENF { get; set; }

        public virtual SW_CEST? COD_CESTNavigation { get; set; }
        public virtual GE_EMPRESAS COD_EMPRESANavigation { get; set; } = null!;
        public virtual GE_ORGANIZACAO? COD_ORGANIZACAONavigation { get; set; }
        public virtual ICollection<CE_PRODUTOS> CE_PRODUTOS { get; set; }
        public virtual ICollection<FT_NOTAS_ITENS> FT_NOTAS_ITENS { get; set; }
        public virtual ICollection<FT_PEDIDOS_ITENS> FT_PEDIDOS_ITENS { get; set; }
        public virtual ICollection<GE_REGRAS_TRIBUTACAO> GE_REGRAS_TRIBUTACAO { get; set; }
    }
}