// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class GE_CALENDARIO
    {
        public GE_CALENDARIO()
        {
            GE_CALENDARIO_FERIADO = new HashSet<GE_CALENDARIO_FERIADO>();
            GE_EMPRESAS = new HashSet<GE_EMPRESAS>();
            GE_ORGANIZACAO = new HashSet<GE_ORGANIZACAO>();
        }

        public int COD_CALENDARIO { get; set; }
        public string? DES_CALENDARIO { get; set; }
        public DateTime? DTA_CRIACAO { get; set; }
        public int? COD_ORGANIZACAO { get; set; }

        public virtual GE_ORGANIZACAO? COD_ORGANIZACAONavigation { get; set; }
        public virtual ICollection<GE_CALENDARIO_FERIADO> GE_CALENDARIO_FERIADO { get; set; }
        public virtual ICollection<GE_EMPRESAS> GE_EMPRESAS { get; set; }
        public virtual ICollection<GE_ORGANIZACAO> GE_ORGANIZACAO { get; set; }
    }
}