// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class GE_COLABORACAO_CURTIDAS
    {
        public int COD_COLABORACAO_CURTIDAS { get; set; }
        public int COD_COLABORACAO { get; set; }
        public int COD_USUARIO { get; set; }
        public DateTime? DTA_CRIACAO { get; set; }
        public bool TIP_PONTUA { get; set; }
        public int COD_ORGANIZACAO { get; set; }

        public virtual GE_COLABORACAO COD_COLABORACAONavigation { get; set; } = null!;
        public virtual GE_ORGANIZACAO COD_ORGANIZACAONavigation { get; set; } = null!;
        public virtual GE_USUARIOS COD_USUARIONavigation { get; set; } = null!;
    }
}