// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class GE_DASHBOARD_CONFIGURACAO
    {
        public int COD_CONFIGURACAO { get; set; }
        public int COD_DASHBOARD { get; set; }
        public string? DES_JSON { get; set; }

        public virtual GE_DASHBOARD COD_DASHBOARDNavigation { get; set; } = null!;
    }
}