// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class GE_DRE
    {
        public GE_DRE()
        {
            GE_CONTAS_CONTABEIS = new HashSet<GE_CONTAS_CONTABEIS>();
        }

        public int COD_DRE { get; set; }
        public int COD_EMPRESA { get; set; }
        public string DES_DRE { get; set; } = null!;
        public int? COD_DRE_PAI { get; set; }
        public bool TIP_SISTEMA { get; set; }
        public int? COD_CONTA_DRE { get; set; }
        public virtual SW_CONTAS_DRE? COD_CONTA_DRENavigation { get; set; }
        public virtual GE_EMPRESAS COD_EMPRESANavigation { get; set; } = null!;
        public virtual ICollection<GE_CONTAS_CONTABEIS> GE_CONTAS_CONTABEIS { get; set; }
    }
}