// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class GE_DASHBOARD
    {
        public GE_DASHBOARD()
        {
            GE_DASHBOARD_CONFIGURACAO = new HashSet<GE_DASHBOARD_CONFIGURACAO>();
        }

        public int COD_DASHBOARD { get; set; }
        public string DES_DASHBOARD { get; set; } = null!;
        public int COD_USUARIO { get; set; }
        public DateTime DTA_CRIACAO { get; set; }
        public bool TIP_DEFAULT { get; set; }
        public int COD_EMPRESA { get; set; }
        public bool TIP_SISTEMA { get; set; }

        public virtual GE_EMPRESAS COD_EMPRESANavigation { get; set; } = null!;
        public virtual GE_USUARIOS COD_USUARIONavigation { get; set; } = null!;
        public virtual ICollection<GE_DASHBOARD_CONFIGURACAO> GE_DASHBOARD_CONFIGURACAO { get; set; }
    }
}