// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class GE_EMPRESAS
    {
        public GE_EMPRESAS()
        {
            APP_IFOOD_AUTORIZACAO = new HashSet<APP_IFOOD_AUTORIZACAO>();
            APP_IFOOD_EVENTOS = new HashSet<APP_IFOOD_EVENTOS>();
            APP_IFOOD_PEDIDOS = new HashSet<APP_IFOOD_PEDIDOS>();
            CA_ABERTURA_FECHAMENTO = new HashSet<CA_ABERTURA_FECHAMENTO>();
            CA_MOVIMENTOS = new HashSet<CA_MOVIMENTOS>();
            CA_TIPOS_MOVIMENTOS = new HashSet<CA_TIPOS_MOVIMENTOS>();
            CE_INVENTARIOS = new HashSet<CE_INVENTARIOS>();
            CE_INVENTARIO_SPED = new HashSet<CE_INVENTARIO_SPED>();
            CE_MOVIMENTOS_ESTOQUES = new HashSet<CE_MOVIMENTOS_ESTOQUES>();
            CE_NOTAS = new HashSet<CE_NOTAS>();
            CE_NOTAS_ITENS = new HashSet<CE_NOTAS_ITENS>();
            CE_NOTAS_MENSAGENS = new HashSet<CE_NOTAS_MENSAGENS>();
            CE_PRODUTOS = new HashSet<CE_PRODUTOS>();
            CE_PRODUTOS_FCI = new HashSet<CE_PRODUTOS_FCI>();
            CE_PRODUTOS_FORNECEDORES = new HashSet<CE_PRODUTOS_FORNECEDORES>();
            CE_PRODUTOS_ISET = new HashSet<CE_PRODUTOS_ISET>();
            CE_PRODUTOS_TRAY = new HashSet<CE_PRODUTOS_TRAY>();
            CE_PRODUTOS_VALORES = new HashSet<CE_PRODUTOS_VALORES>();
            CE_PRODUTOS_VENDAS_EMPRESAS = new HashSet<CE_PRODUTOS_VENDAS_EMPRESAS>();
            CE_PRODUTO_ALMOXARIFADOS = new HashSet<CE_PRODUTO_ALMOXARIFADOS>();
            CE_PRODUTO_COMPOSICAO = new HashSet<CE_PRODUTO_COMPOSICAO>();
            CE_PRODUTO_TRIBUTACAO = new HashSet<CE_PRODUTO_TRIBUTACAO>();
            CO_APROVADORES = new HashSet<CO_APROVADORES>();
            CO_LOGS_STATUS_ORDENS = new HashSet<CO_LOGS_STATUS_ORDENS>();
            CO_ORDENS = new HashSet<CO_ORDENS>();
            CO_ORDENS_ITENS = new HashSet<CO_ORDENS_ITENS>();
            CO_ORDENS_MENSAGENS = new HashSet<CO_ORDENS_MENSAGENS>();
            CO_ORDENS_PAGAMENTOS = new HashSet<CO_ORDENS_PAGAMENTOS>();
            CO_STATUS_CONFIGURACOES = new HashSet<CO_STATUS_CONFIGURACOES>();
            CP_TITULOS = new HashSet<CP_TITULOS>();
            CP_TITULOS_LANCAMENTOS = new HashSet<CP_TITULOS_LANCAMENTOS>();
            CR_CONTAS_BANCARIASCOD_EMPRESANavigation = new HashSet<CR_CONTAS_BANCARIAS>();
            CR_CONTAS_BANCARIASCOD_EMPRESA_CEDENTENavigation = new HashSet<CR_CONTAS_BANCARIAS>();
            CR_CONVENIOS_BANCARIOS = new HashSet<CR_CONVENIOS_BANCARIOS>();
            CR_PARAMETROS = new HashSet<CR_PARAMETROS>();
            CR_REMESSA_OPEN_BANK = new HashSet<CR_REMESSA_OPEN_BANK>();
            CR_RETORNO_HISTORICO = new HashSet<CR_RETORNO_HISTORICO>();
            CR_SALDOS = new HashSet<CR_SALDOS>();
            CR_TITULOS = new HashSet<CR_TITULOS>();
            CR_TITULOS_LANCAMENTOS = new HashSet<CR_TITULOS_LANCAMENTOS>();
            FT_FATURA = new HashSet<FT_FATURA>();
            FT_FATURAS_NAO_GERADAS = new HashSet<FT_FATURAS_NAO_GERADAS>();
            FT_FATURA_ITENS = new HashSet<FT_FATURA_ITENS>();
            FT_MANIFESTO_DESTINATARIO = new HashSet<FT_MANIFESTO_DESTINATARIO>();
            FT_MDFE = new HashSet<FT_MDFE>();
            FT_MDFE_CARREGAMENTOS = new HashSet<FT_MDFE_CARREGAMENTOS>();
            FT_MDFE_CONDUTOR = new HashSet<FT_MDFE_CONDUTOR>();
            FT_MDFE_NFE = new HashSet<FT_MDFE_NFE>();
            FT_MDFE_PERCURSO = new HashSet<FT_MDFE_PERCURSO>();
            FT_MDFE_REBOQUE = new HashSet<FT_MDFE_REBOQUE>();
            FT_MDFE_SEGURO_CARGA = new HashSet<FT_MDFE_SEGURO_CARGA>();
            FT_NOTAS = new HashSet<FT_NOTAS>();
            FT_NOTAS_INUTILIZADAS = new HashSet<FT_NOTAS_INUTILIZADAS>();
            FT_NOTAS_ITENS_EXPORTACAO = new HashSet<FT_NOTAS_ITENS_EXPORTACAO>();
            FT_NOTAS_ITENS_IMPORTACAO = new HashSet<FT_NOTAS_ITENS_IMPORTACAO>();
            FT_NOTAS_ITENS_IMPORTACAO_ADICAO = new HashSet<FT_NOTAS_ITENS_IMPORTACAO_ADICAO>();
            FT_NOTAS_PAGAMENTOS = new HashSet<FT_NOTAS_PAGAMENTOS>();
            FT_NOTAS_PEDIDOS_REFERENCIADAS = new HashSet<FT_NOTAS_PEDIDOS_REFERENCIADAS>();
            FT_NOTAS_REFERENCIADAS = new HashSet<FT_NOTAS_REFERENCIADAS>();
            FT_NUMERO_NOTAS = new HashSet<FT_NUMERO_NOTAS>();
            FT_PARAMETROS_FORNECEDORES_MANIFESTO = new HashSet<FT_PARAMETROS_FORNECEDORES_MANIFESTO>();
            FT_PEDIDOS = new HashSet<FT_PEDIDOS>();
            FT_PEDIDOS_PAGAMENTOS = new HashSet<FT_PEDIDOS_PAGAMENTOS>();
            GE_ADMINISTRADORES_ORGANIZACAO_EMPRESAS = new HashSet<GE_ADMINISTRADORES_ORGANIZACAO_EMPRESAS>();
            GE_ALMOXARIFADOS = new HashSet<GE_ALMOXARIFADOS>();
            GE_ANEXOS = new HashSet<GE_ANEXOS>();
            GE_ANEXOS_EMAIL = new HashSet<GE_ANEXOS_EMAIL>();
            GE_ANOTACOES = new HashSet<GE_ANOTACOES>();
            GE_ANOTACOES_ANEXO = new HashSet<GE_ANOTACOES_ANEXO>();
            GE_ANOTACOES_USUARIO = new HashSet<GE_ANOTACOES_USUARIO>();
            GE_APLICACAO_EXTERNA = new HashSet<GE_APLICACAO_EXTERNA>();
            GE_BANCOS = new HashSet<GE_BANCOS>();
            GE_CADASTRO_FRENTE_CAIXA = new HashSet<GE_CADASTRO_FRENTE_CAIXA>();
            GE_CARGOS = new HashSet<GE_CARGOS>();
            GE_CATEGORIAS_PRODUTOS = new HashSet<GE_CATEGORIAS_PRODUTOS>();
            GE_CENTRO_CUSTOS = new HashSet<GE_CENTRO_CUSTOS>();
            GE_CERTIFICADO_DIGITAL = new HashSet<GE_CERTIFICADO_DIGITAL>();
            GE_CLASSIFICACAO_COMPONENTES_DASHBOARD = new HashSet<GE_CLASSIFICACAO_COMPONENTES_DASHBOARD>();
            GE_CLASSIFICACAO_FISCAL = new HashSet<GE_CLASSIFICACAO_FISCAL>();
            GE_CLASSIFICACOES_PRODUTOS = new HashSet<GE_CLASSIFICACOES_PRODUTOS>();
            GE_COMENTARIOS = new HashSet<GE_COMENTARIOS>();
            GE_COMPARTILHAMENTOS = new HashSet<GE_COMPARTILHAMENTOS>();
            GE_COMPONENTES_DASHBOARD = new HashSet<GE_COMPONENTES_DASHBOARD>();
            GE_CONDICAO_PAGAMENTO = new HashSet<GE_CONDICAO_PAGAMENTO>();
            GE_CONDUTORES = new HashSet<GE_CONDUTORES>();
            GE_CONFIGURACAO_ALMOXARIFADOS_TRAY = new HashSet<GE_CONFIGURACAO_ALMOXARIFADOS_TRAY>();
            GE_CONFIGURACAO_ALMOXARIFADO_ISET = new HashSet<GE_CONFIGURACAO_ALMOXARIFADO_ISET>();
            GE_CONFIGURACAO_MODELO_PEDIDO = new HashSet<GE_CONFIGURACAO_MODELO_PEDIDO>();
            GE_CONFIG_INTEGRACAO_BIMACHINE = new HashSet<GE_CONFIG_INTEGRACAO_BIMACHINE>();
            GE_CONFIG_INTEGRACAO_ISET = new HashSet<GE_CONFIG_INTEGRACAO_ISET>();
            GE_CONFIG_INTEGRACAO_TRAY = new HashSet<GE_CONFIG_INTEGRACAO_TRAY>();
            GE_CONFIG_PAG_PIX = new HashSet<GE_CONFIG_PAG_PIX>();
            GE_CONFIG_SERVICOS_TRAY = new HashSet<GE_CONFIG_SERVICOS_TRAY>();
            GE_CONSULTAS_CONFIGURADAS = new HashSet<GE_CONSULTAS_CONFIGURADAS>();
            GE_CONTAS_CONTABEIS = new HashSet<GE_CONTAS_CONTABEIS>();
            GE_CONTAS_EMAIL = new HashSet<GE_CONTAS_EMAIL>();
            GE_CONTA_EMAIL_PROCESSOS = new HashSet<GE_CONTA_EMAIL_PROCESSOS>();
            GE_DASHBOARD = new HashSet<GE_DASHBOARD>();
            GE_DRE = new HashSet<GE_DRE>();
            GE_EMAILS_ENVIADOS = new HashSet<GE_EMAILS_ENVIADOS>();
            GE_EMAILS_SPED_FISCAL = new HashSet<GE_EMAILS_SPED_FISCAL>();
            GE_EMPRESAS_PADRAOCOD_EMPRESA_IBPTNavigation = new HashSet<GE_EMPRESAS_PADRAO>();
            GE_EMPRESAS_PADRAOCOD_EMPRESA_IFOODNavigation = new HashSet<GE_EMPRESAS_PADRAO>();
            GE_EMPRESAS_PADRAOCOD_EMP_ALMOXARIFADOSNavigation = new HashSet<GE_EMPRESAS_PADRAO>();
            GE_EMPRESAS_PADRAOCOD_EMP_BANCOSNavigation = new HashSet<GE_EMPRESAS_PADRAO>();
            GE_EMPRESAS_PADRAOCOD_EMP_CANAL_VENDASNavigation = new HashSet<GE_EMPRESAS_PADRAO>();
            GE_EMPRESAS_PADRAOCOD_EMP_CATEGORIAS_PRODUTOSNavigation = new HashSet<GE_EMPRESAS_PADRAO>();
            GE_EMPRESAS_PADRAOCOD_EMP_CENTRO_CUSTONavigation = new HashSet<GE_EMPRESAS_PADRAO>();
            GE_EMPRESAS_PADRAOCOD_EMP_CLASSIFICACAO_FISCALNavigation = new HashSet<GE_EMPRESAS_PADRAO>();
            GE_EMPRESAS_PADRAOCOD_EMP_CLASSIFICACOES_PRODUTOSNavigation = new HashSet<GE_EMPRESAS_PADRAO>();
            GE_EMPRESAS_PADRAOCOD_EMP_CONDICAO_PAGAMENTONavigation = new HashSet<GE_EMPRESAS_PADRAO>();
            GE_EMPRESAS_PADRAOCOD_EMP_CONTAS_CONTABEISNavigation = new HashSet<GE_EMPRESAS_PADRAO>();
            GE_EMPRESAS_PADRAOCOD_EMP_GRUPO_COMISSOESNavigation = new HashSet<GE_EMPRESAS_PADRAO>();
            GE_EMPRESAS_PADRAOCOD_EMP_INDICENavigation = new HashSet<GE_EMPRESAS_PADRAO>();
            GE_EMPRESAS_PADRAOCOD_EMP_LISTA_PRECONavigation = new HashSet<GE_EMPRESAS_PADRAO>();
            GE_EMPRESAS_PADRAOCOD_EMP_MARCASNavigation = new HashSet<GE_EMPRESAS_PADRAO>();
            GE_EMPRESAS_PADRAOCOD_EMP_MENSAGENSNavigation = new HashSet<GE_EMPRESAS_PADRAO>();
            GE_EMPRESAS_PADRAOCOD_EMP_OPERACAO_FISCALNavigation = new HashSet<GE_EMPRESAS_PADRAO>();
            GE_EMPRESAS_PADRAOCOD_EMP_OPERADORAS_CARTAONavigation = new HashSet<GE_EMPRESAS_PADRAO>();
            GE_EMPRESAS_PADRAOCOD_EMP_PESSOASNavigation = new HashSet<GE_EMPRESAS_PADRAO>();
            GE_EMPRESAS_PADRAOCOD_EMP_PRODUTOSNavigation = new HashSet<GE_EMPRESAS_PADRAO>();
            GE_EMPRESAS_PADRAOCOD_EMP_PRODUTOS_VALORESNavigation = new HashSet<GE_EMPRESAS_PADRAO>();
            GE_EMPRESAS_PADRAOCOD_EMP_PRODUTO_ALMOXARIFADOSNavigation = new HashSet<GE_EMPRESAS_PADRAO>();
            GE_EMPRESAS_PADRAOCOD_EMP_PRODUTO_COMPOSICAONavigation = new HashSet<GE_EMPRESAS_PADRAO>();
            GE_EMPRESAS_PADRAOCOD_EMP_PROGRAMA_FIDELIDADENavigation = new HashSet<GE_EMPRESAS_PADRAO>();
            GE_EMPRESAS_PADRAOCOD_EMP_PROMOCOESNavigation = new HashSet<GE_EMPRESAS_PADRAO>();
            GE_EMPRESAS_PADRAOCOD_EMP_REGRA_TRIBUTACAONavigation = new HashSet<GE_EMPRESAS_PADRAO>();
            GE_EMPRESAS_PADRAOCOD_EMP_STATUS_ORDEMNavigation = new HashSet<GE_EMPRESAS_PADRAO>();
            GE_EMPRESAS_PADRAOCOD_EMP_TECNICO_ORDEMNavigation = new HashSet<GE_EMPRESAS_PADRAO>();
            GE_EMPRESAS_PADRAOCOD_EMP_TIPOS_ORDEMNavigation = new HashSet<GE_EMPRESAS_PADRAO>();
            GE_EMPRESAS_PADRAOCOD_EMP_TIPOS_PAGAMENTOS_CONDICOES_PAGAMENTOSNavigation = new HashSet<GE_EMPRESAS_PADRAO>();
            GE_EMPRESAS_PADRAOCOD_EMP_TIPO_MOVIMENTOS_CAIXANavigation = new HashSet<GE_EMPRESAS_PADRAO>();
            GE_EMPRESAS_PADRAOCOD_EMP_TIPO_PAGAMENTONavigation = new HashSet<GE_EMPRESAS_PADRAO>();
            GE_EMPRESAS_PADRAOCOD_EMP_TIPO_TITULONavigation = new HashSet<GE_EMPRESAS_PADRAO>();
            GE_EMPRESAS_PADRAOCOD_EMP_UNIDADE_MEDIDANavigation = new HashSet<GE_EMPRESAS_PADRAO>();
            GE_EMPRESAS_UF = new HashSet<GE_EMPRESAS_UF>();
            GE_ETIQUETAS = new HashSet<GE_ETIQUETAS>();
            GE_FILA_SPED_FISCAL = new HashSet<GE_FILA_SPED_FISCAL>();
            GE_GESTAO_COMPARTILHAMENTOS = new HashSet<GE_GESTAO_COMPARTILHAMENTOS>();
            GE_GESTAO_COMPARTILHAMENTOS_PROCESSOS_PERMISSOES = new HashSet<GE_GESTAO_COMPARTILHAMENTOS_PROCESSOS_PERMISSOES>();
            GE_IBPT = new HashSet<GE_IBPT>();
            GE_INDICES = new HashSet<GE_INDICES>();
            GE_INTERMEDIADOR = new HashSet<GE_INTERMEDIADOR>();
            GE_INTREGRACAO_WHATSAPP = new HashSet<GE_INTREGRACAO_WHATSAPP>();
            GE_LISTA_PRECOS = new HashSet<GE_LISTA_PRECOS>();
            GE_LOGS_COMPARTILHAMENTOS = new HashSet<GE_LOGS_COMPARTILHAMENTOS>();
            GE_MARCAS = new HashSet<GE_MARCAS>();
            GE_MENSAGEM_PADRAO = new HashSet<GE_MENSAGEM_PADRAO>();
            GE_MENSAGENS = new HashSet<GE_MENSAGENS>();
            GE_OPERACAO_FISCAL = new HashSet<GE_OPERACAO_FISCAL>();
            GE_OPERADORAS_CARTAO = new HashSet<GE_OPERADORAS_CARTAO>();
            GE_POSICAO = new HashSet<GE_POSICAO>();
            GE_PROGRAMA_FIDELIDADE = new HashSet<GE_PROGRAMA_FIDELIDADE>();
            GE_PROPRIETARIO_VEICULOS = new HashSet<GE_PROPRIETARIO_VEICULOS>();
            GE_REGRAS_TRIBUTACAO = new HashSet<GE_REGRAS_TRIBUTACAO>();
            GE_REGRAS_TRIBUTACAO_XML_ENTRADA = new HashSet<GE_REGRAS_TRIBUTACAO_XML_ENTRADA>();
            GE_RELACOES_LISTAS_PRECOS = new HashSet<GE_RELACOES_LISTAS_PRECOS>();
            GE_SEGURADORAS = new HashSet<GE_SEGURADORAS>();
            GE_TIPOS_PAGAMENTOS_CONDICOES_PAGAMENTOS = new HashSet<GE_TIPOS_PAGAMENTOS_CONDICOES_PAGAMENTOS>();
            GE_TIPO_ENDERECO = new HashSet<GE_TIPO_ENDERECO>();
            GE_TIPO_PAGAMENTO = new HashSet<GE_TIPO_PAGAMENTO>();
            GE_TIPO_TELEFONE = new HashSet<GE_TIPO_TELEFONE>();
            GE_TIPO_TITULO = new HashSet<GE_TIPO_TITULO>();
            GE_UNIDADE_MEDIDA = new HashSet<GE_UNIDADE_MEDIDA>();
            GE_USUARIOS = new HashSet<GE_USUARIOS>();
            GE_VEICULOS = new HashSet<GE_VEICULOS>();
            InverseCOD_EMPRESA_MATRIZNavigation = new HashSet<GE_EMPRESAS>();
            OS_ORDEM = new HashSet<OS_ORDEM>();
            OS_ORDEM_MATERIAIS = new HashSet<OS_ORDEM_MATERIAIS>();
            OS_ORDEM_SERVICO = new HashSet<OS_ORDEM_SERVICO>();
            OS_PARAMETROS = new HashSet<OS_PARAMETROS>();
            PS_CANAL_VENDAS = new HashSet<PS_CANAL_VENDAS>();
            PS_CLIENTES_VENCIMENTOS = new HashSet<PS_CLIENTES_VENCIMENTOS>();
            PS_CONTRATOS = new HashSet<PS_CONTRATOS>();
            PS_CONTRATOS_ITENS = new HashSet<PS_CONTRATOS_ITENS>();
            PS_CONTRATOS_REAJUSTES = new HashSet<PS_CONTRATOS_REAJUSTES>();
            PS_LANCAMENTOS = new HashSet<PS_LANCAMENTOS>();
            PS_LANCAMENTOS_ITENS = new HashSet<PS_LANCAMENTOS_ITENS>();
            PS_LANCAMENTOS_VENCIMENTO = new HashSet<PS_LANCAMENTOS_VENCIMENTO>();
            PS_PESSOASCOD_EMPRESANavigation = new HashSet<PS_PESSOAS>();
            PS_PESSOASCOD_EMPRESA_ORIGEMNavigation = new HashSet<PS_PESSOAS>();
            PS_RAMOS_ATIVIDADES = new HashSet<PS_RAMOS_ATIVIDADES>();
            SW_CLIENTES_PEDIDOS_ISET = new HashSet<SW_CLIENTES_PEDIDOS_ISET>();
            SW_CLIENTES_PEDIDOS_TRAY = new HashSet<SW_CLIENTES_PEDIDOS_TRAY>();
            SW_EMAILS_ALERTAS_ISET = new HashSet<SW_EMAILS_ALERTAS_ISET>();
            SW_EMAILS_ALERTAS_TRAY = new HashSet<SW_EMAILS_ALERTAS_TRAY>();
            SW_ERROS_APLICACAO = new HashSet<SW_ERROS_APLICACAO>();
            SW_LOG_REGISTROS = new HashSet<SW_LOG_REGISTROS>();
            SW_PAGAMENTOS_PEDIDOS_ISET = new HashSet<SW_PAGAMENTOS_PEDIDOS_ISET>();
            SW_PAGAMENTOS_PEDIDOS_TRAY = new HashSet<SW_PAGAMENTOS_PEDIDOS_TRAY>();
            SW_PEDIDOS_ISET = new HashSet<SW_PEDIDOS_ISET>();
            SW_PEDIDOS_ISET_ITENS = new HashSet<SW_PEDIDOS_ISET_ITENS>();
            SW_PEDIDOS_TRAY = new HashSet<SW_PEDIDOS_TRAY>();
            SW_PEDIDOS_TRAY_ITENS = new HashSet<SW_PEDIDOS_TRAY_ITENS>();
            SW_PROCESSOS_FIFO = new HashSet<SW_PROCESSOS_FIFO>();
            SW_RELACAO_PAGAMENTO_ISET = new HashSet<SW_RELACAO_PAGAMENTO_ISET>();
            SW_RELACAO_PAGAMENTO_TRAY = new HashSet<SW_RELACAO_PAGAMENTO_TRAY>();
            SW_RELACAO_TIPO_PAGAMENTO_TRAY = new HashSet<SW_RELACAO_TIPO_PAGAMENTO_TRAY>();
            SW_USUARIOS_LOGADOS = new HashSet<SW_USUARIOS_LOGADOS>();
            COD_USUARIO = new HashSet<GE_USUARIOS>();
        }

        public int COD_EMPRESA { get; set; }
        public string? DES_NOME { get; set; }
        public string? DES_FANTASIA { get; set; }
        public DateTime? DTA_CRIACAO { get; set; }
        public int COD_ORGANIZACAO { get; set; }
        public int? COD_CALENDARIO { get; set; }
        public int? COD_HORARIO_TRABALHO { get; set; }
        public int? COD_LINGUAGEM { get; set; }
        public int? COD_LOCALIZACAO { get; set; }
        public string? NUM_CNPJ { get; set; }
        public string? NUM_INSCRICAO_ESTADUAL { get; set; }
        public string? NUM_FONE { get; set; }
        public string? DES_ENDERECO { get; set; }
        public string? DES_BAIRRO { get; set; }
        public int? COD_CIDADE { get; set; }
        public string? NUM_ENDERECO { get; set; }
        public int? COD_CEP { get; set; }
        public string? DES_EMAIL { get; set; }
        public string? DES_COMPLEMENTO { get; set; }
        public string? NUM_INSCRICAO_MUNICIPAL { get; set; }
        public bool? TIP_SIMPLES_NACIONAL { get; set; }
        public int? IND_REGIME_ESPECIAL { get; set; }
        public string? COD_CNAE { get; set; }
        public string? DES_RESUMIDA { get; set; }
        public string? DES_LOGO { get; set; }
        public int? COD_CLIENTE_CONECTA { get; set; }
        public string? DES_GUID { get; set; }
        public int? COD_EMPRESA_MATRIZ { get; set; }
        public bool? TIP_EXCESSO_SUBLIMITE { get; set; }
        public string? DES_SITE { get; set; }
        public string? DES_WHATS { get; set; }
        public string? DES_FACEBOOK { get; set; }
        public string? DES_INSTAGRAM { get; set; }
        public string? DES_LINKEDIN { get; set; }
        public string? DES_TIKTOK { get; set; }
        public string? DES_TWITTER { get; set; }

        public virtual GE_CALENDARIO? COD_CALENDARIONavigation { get; set; }
        public virtual GE_CIDADES? COD_CIDADENavigation { get; set; }
        public virtual SW_CNAE? COD_CNAENavigation { get; set; }
        public virtual GE_EMPRESAS? COD_EMPRESA_MATRIZNavigation { get; set; }
        public virtual GE_HORARIO_TRABALHO? COD_HORARIO_TRABALHONavigation { get; set; }
        public virtual SW_LINGUAGEM? COD_LINGUAGEMNavigation { get; set; }
        public virtual GE_LOCALIZACAO? COD_LOCALIZACAONavigation { get; set; }
        public virtual GE_ORGANIZACAO COD_ORGANIZACAONavigation { get; set; } = null!;
        public virtual CO_PARAMETROS? CO_PARAMETROS { get; set; }
        public virtual FT_PARAMETROS? FT_PARAMETROS { get; set; }
        public virtual GE_EMPRESAS_PADRAO? GE_EMPRESAS_PADRAOCOD_EMPRESANavigation { get; set; }
        public virtual ICollection<APP_IFOOD_AUTORIZACAO> APP_IFOOD_AUTORIZACAO { get; set; }
        public virtual ICollection<APP_IFOOD_EVENTOS> APP_IFOOD_EVENTOS { get; set; }
        public virtual ICollection<APP_IFOOD_PEDIDOS> APP_IFOOD_PEDIDOS { get; set; }
        public virtual ICollection<CA_ABERTURA_FECHAMENTO> CA_ABERTURA_FECHAMENTO { get; set; }
        public virtual ICollection<CA_MOVIMENTOS> CA_MOVIMENTOS { get; set; }
        public virtual ICollection<CA_TIPOS_MOVIMENTOS> CA_TIPOS_MOVIMENTOS { get; set; }
        public virtual ICollection<CE_INVENTARIOS> CE_INVENTARIOS { get; set; }
        public virtual ICollection<CE_INVENTARIO_SPED> CE_INVENTARIO_SPED { get; set; }
        public virtual ICollection<CE_MOVIMENTOS_ESTOQUES> CE_MOVIMENTOS_ESTOQUES { get; set; }
        public virtual ICollection<CE_NOTAS> CE_NOTAS { get; set; }
        public virtual ICollection<CE_NOTAS_ITENS> CE_NOTAS_ITENS { get; set; }
        public virtual ICollection<CE_NOTAS_MENSAGENS> CE_NOTAS_MENSAGENS { get; set; }
        public virtual ICollection<CE_PRODUTOS> CE_PRODUTOS { get; set; }
        public virtual ICollection<CE_PRODUTOS_FCI> CE_PRODUTOS_FCI { get; set; }
        public virtual ICollection<CE_PRODUTOS_FORNECEDORES> CE_PRODUTOS_FORNECEDORES { get; set; }
        public virtual ICollection<CE_PRODUTOS_ISET> CE_PRODUTOS_ISET { get; set; }
        public virtual ICollection<CE_PRODUTOS_TRAY> CE_PRODUTOS_TRAY { get; set; }
        public virtual ICollection<CE_PRODUTOS_VALORES> CE_PRODUTOS_VALORES { get; set; }
        public virtual ICollection<CE_PRODUTOS_VENDAS_EMPRESAS> CE_PRODUTOS_VENDAS_EMPRESAS { get; set; }
        public virtual ICollection<CE_PRODUTO_ALMOXARIFADOS> CE_PRODUTO_ALMOXARIFADOS { get; set; }
        public virtual ICollection<CE_PRODUTO_COMPOSICAO> CE_PRODUTO_COMPOSICAO { get; set; }
        public virtual ICollection<CE_PRODUTO_TRIBUTACAO> CE_PRODUTO_TRIBUTACAO { get; set; }
        public virtual ICollection<CO_APROVADORES> CO_APROVADORES { get; set; }
        public virtual ICollection<CO_LOGS_STATUS_ORDENS> CO_LOGS_STATUS_ORDENS { get; set; }
        public virtual ICollection<CO_ORDENS> CO_ORDENS { get; set; }
        public virtual ICollection<CO_ORDENS_ITENS> CO_ORDENS_ITENS { get; set; }
        public virtual ICollection<CO_ORDENS_MENSAGENS> CO_ORDENS_MENSAGENS { get; set; }
        public virtual ICollection<CO_ORDENS_PAGAMENTOS> CO_ORDENS_PAGAMENTOS { get; set; }
        public virtual ICollection<CO_STATUS_CONFIGURACOES> CO_STATUS_CONFIGURACOES { get; set; }
        public virtual ICollection<CP_TITULOS> CP_TITULOS { get; set; }
        public virtual ICollection<CP_TITULOS_LANCAMENTOS> CP_TITULOS_LANCAMENTOS { get; set; }
        public virtual ICollection<CR_CONTAS_BANCARIAS> CR_CONTAS_BANCARIASCOD_EMPRESANavigation { get; set; }
        public virtual ICollection<CR_CONTAS_BANCARIAS> CR_CONTAS_BANCARIASCOD_EMPRESA_CEDENTENavigation { get; set; }
        public virtual ICollection<CR_CONVENIOS_BANCARIOS> CR_CONVENIOS_BANCARIOS { get; set; }
        public virtual ICollection<CR_PARAMETROS> CR_PARAMETROS { get; set; }
        public virtual ICollection<CR_REMESSA_OPEN_BANK> CR_REMESSA_OPEN_BANK { get; set; }
        public virtual ICollection<CR_RETORNO_HISTORICO> CR_RETORNO_HISTORICO { get; set; }
        public virtual ICollection<CR_SALDOS> CR_SALDOS { get; set; }
        public virtual ICollection<CR_TITULOS> CR_TITULOS { get; set; }
        public virtual ICollection<CR_TITULOS_LANCAMENTOS> CR_TITULOS_LANCAMENTOS { get; set; }
        public virtual ICollection<FT_FATURA> FT_FATURA { get; set; }
        public virtual ICollection<FT_FATURAS_NAO_GERADAS> FT_FATURAS_NAO_GERADAS { get; set; }
        public virtual ICollection<FT_FATURA_ITENS> FT_FATURA_ITENS { get; set; }
        public virtual ICollection<FT_MANIFESTO_DESTINATARIO> FT_MANIFESTO_DESTINATARIO { get; set; }
        public virtual ICollection<FT_MDFE> FT_MDFE { get; set; }
        public virtual ICollection<FT_MDFE_CARREGAMENTOS> FT_MDFE_CARREGAMENTOS { get; set; }
        public virtual ICollection<FT_MDFE_CONDUTOR> FT_MDFE_CONDUTOR { get; set; }
        public virtual ICollection<FT_MDFE_NFE> FT_MDFE_NFE { get; set; }
        public virtual ICollection<FT_MDFE_PERCURSO> FT_MDFE_PERCURSO { get; set; }
        public virtual ICollection<FT_MDFE_REBOQUE> FT_MDFE_REBOQUE { get; set; }
        public virtual ICollection<FT_MDFE_SEGURO_CARGA> FT_MDFE_SEGURO_CARGA { get; set; }
        public virtual ICollection<FT_NOTAS> FT_NOTAS { get; set; }
        public virtual ICollection<FT_NOTAS_INUTILIZADAS> FT_NOTAS_INUTILIZADAS { get; set; }
        public virtual ICollection<FT_NOTAS_ITENS_EXPORTACAO> FT_NOTAS_ITENS_EXPORTACAO { get; set; }
        public virtual ICollection<FT_NOTAS_ITENS_IMPORTACAO> FT_NOTAS_ITENS_IMPORTACAO { get; set; }
        public virtual ICollection<FT_NOTAS_ITENS_IMPORTACAO_ADICAO> FT_NOTAS_ITENS_IMPORTACAO_ADICAO { get; set; }
        public virtual ICollection<FT_NOTAS_PAGAMENTOS> FT_NOTAS_PAGAMENTOS { get; set; }
        public virtual ICollection<FT_NOTAS_PEDIDOS_REFERENCIADAS> FT_NOTAS_PEDIDOS_REFERENCIADAS { get; set; }
        public virtual ICollection<FT_NOTAS_REFERENCIADAS> FT_NOTAS_REFERENCIADAS { get; set; }
        public virtual ICollection<FT_NUMERO_NOTAS> FT_NUMERO_NOTAS { get; set; }
        public virtual ICollection<FT_PARAMETROS_FORNECEDORES_MANIFESTO> FT_PARAMETROS_FORNECEDORES_MANIFESTO { get; set; }
        public virtual ICollection<FT_PEDIDOS> FT_PEDIDOS { get; set; }
        public virtual ICollection<FT_PEDIDOS_PAGAMENTOS> FT_PEDIDOS_PAGAMENTOS { get; set; }
        public virtual ICollection<GE_ADMINISTRADORES_ORGANIZACAO_EMPRESAS> GE_ADMINISTRADORES_ORGANIZACAO_EMPRESAS { get; set; }
        public virtual ICollection<GE_ALMOXARIFADOS> GE_ALMOXARIFADOS { get; set; }
        public virtual ICollection<GE_ANEXOS> GE_ANEXOS { get; set; }
        public virtual ICollection<GE_ANEXOS_EMAIL> GE_ANEXOS_EMAIL { get; set; }
        public virtual ICollection<GE_ANOTACOES> GE_ANOTACOES { get; set; }
        public virtual ICollection<GE_ANOTACOES_ANEXO> GE_ANOTACOES_ANEXO { get; set; }
        public virtual ICollection<GE_ANOTACOES_USUARIO> GE_ANOTACOES_USUARIO { get; set; }
        public virtual ICollection<GE_APLICACAO_EXTERNA> GE_APLICACAO_EXTERNA { get; set; }
        public virtual ICollection<GE_BANCOS> GE_BANCOS { get; set; }
        public virtual ICollection<GE_CADASTRO_FRENTE_CAIXA> GE_CADASTRO_FRENTE_CAIXA { get; set; }
        public virtual ICollection<GE_CARGOS> GE_CARGOS { get; set; }
        public virtual ICollection<GE_CATEGORIAS_PRODUTOS> GE_CATEGORIAS_PRODUTOS { get; set; }
        public virtual ICollection<GE_CENTRO_CUSTOS> GE_CENTRO_CUSTOS { get; set; }
        public virtual ICollection<GE_CERTIFICADO_DIGITAL> GE_CERTIFICADO_DIGITAL { get; set; }
        public virtual ICollection<GE_CLASSIFICACAO_COMPONENTES_DASHBOARD> GE_CLASSIFICACAO_COMPONENTES_DASHBOARD { get; set; }
        public virtual ICollection<GE_CLASSIFICACAO_FISCAL> GE_CLASSIFICACAO_FISCAL { get; set; }
        public virtual ICollection<GE_CLASSIFICACOES_PRODUTOS> GE_CLASSIFICACOES_PRODUTOS { get; set; }
        public virtual ICollection<GE_COMENTARIOS> GE_COMENTARIOS { get; set; }
        public virtual ICollection<GE_COMPARTILHAMENTOS> GE_COMPARTILHAMENTOS { get; set; }
        public virtual ICollection<GE_COMPONENTES_DASHBOARD> GE_COMPONENTES_DASHBOARD { get; set; }
        public virtual ICollection<GE_CONDICAO_PAGAMENTO> GE_CONDICAO_PAGAMENTO { get; set; }
        public virtual ICollection<GE_CONDUTORES> GE_CONDUTORES { get; set; }
        public virtual ICollection<GE_CONFIGURACAO_ALMOXARIFADOS_TRAY> GE_CONFIGURACAO_ALMOXARIFADOS_TRAY { get; set; }
        public virtual ICollection<GE_CONFIGURACAO_ALMOXARIFADO_ISET> GE_CONFIGURACAO_ALMOXARIFADO_ISET { get; set; }
        public virtual ICollection<GE_CONFIGURACAO_MODELO_PEDIDO> GE_CONFIGURACAO_MODELO_PEDIDO { get; set; }
        public virtual ICollection<GE_CONFIG_INTEGRACAO_BIMACHINE> GE_CONFIG_INTEGRACAO_BIMACHINE { get; set; }
        public virtual ICollection<GE_CONFIG_INTEGRACAO_ISET> GE_CONFIG_INTEGRACAO_ISET { get; set; }
        public virtual ICollection<GE_CONFIG_INTEGRACAO_TRAY> GE_CONFIG_INTEGRACAO_TRAY { get; set; }
        public virtual ICollection<GE_CONFIG_PAG_PIX> GE_CONFIG_PAG_PIX { get; set; }
        public virtual ICollection<GE_CONFIG_SERVICOS_TRAY> GE_CONFIG_SERVICOS_TRAY { get; set; }
        public virtual ICollection<GE_CONSULTAS_CONFIGURADAS> GE_CONSULTAS_CONFIGURADAS { get; set; }
        public virtual ICollection<GE_CONTAS_CONTABEIS> GE_CONTAS_CONTABEIS { get; set; }
        public virtual ICollection<GE_CONTAS_EMAIL> GE_CONTAS_EMAIL { get; set; }
        public virtual ICollection<GE_CONTA_EMAIL_PROCESSOS> GE_CONTA_EMAIL_PROCESSOS { get; set; }
        public virtual ICollection<GE_DASHBOARD> GE_DASHBOARD { get; set; }
        public virtual ICollection<GE_DRE> GE_DRE { get; set; }
        public virtual ICollection<GE_EMAILS_ENVIADOS> GE_EMAILS_ENVIADOS { get; set; }
        public virtual ICollection<GE_EMAILS_SPED_FISCAL> GE_EMAILS_SPED_FISCAL { get; set; }
        public virtual ICollection<GE_EMPRESAS_PADRAO> GE_EMPRESAS_PADRAOCOD_EMPRESA_IBPTNavigation { get; set; }
        public virtual ICollection<GE_EMPRESAS_PADRAO> GE_EMPRESAS_PADRAOCOD_EMPRESA_IFOODNavigation { get; set; }
        public virtual ICollection<GE_EMPRESAS_PADRAO> GE_EMPRESAS_PADRAOCOD_EMP_ALMOXARIFADOSNavigation { get; set; }
        public virtual ICollection<GE_EMPRESAS_PADRAO> GE_EMPRESAS_PADRAOCOD_EMP_BANCOSNavigation { get; set; }
        public virtual ICollection<GE_EMPRESAS_PADRAO> GE_EMPRESAS_PADRAOCOD_EMP_CANAL_VENDASNavigation { get; set; }
        public virtual ICollection<GE_EMPRESAS_PADRAO> GE_EMPRESAS_PADRAOCOD_EMP_CATEGORIAS_PRODUTOSNavigation { get; set; }
        public virtual ICollection<GE_EMPRESAS_PADRAO> GE_EMPRESAS_PADRAOCOD_EMP_CENTRO_CUSTONavigation { get; set; }
        public virtual ICollection<GE_EMPRESAS_PADRAO> GE_EMPRESAS_PADRAOCOD_EMP_CLASSIFICACAO_FISCALNavigation { get; set; }
        public virtual ICollection<GE_EMPRESAS_PADRAO> GE_EMPRESAS_PADRAOCOD_EMP_CLASSIFICACOES_PRODUTOSNavigation { get; set; }
        public virtual ICollection<GE_EMPRESAS_PADRAO> GE_EMPRESAS_PADRAOCOD_EMP_CONDICAO_PAGAMENTONavigation { get; set; }
        public virtual ICollection<GE_EMPRESAS_PADRAO> GE_EMPRESAS_PADRAOCOD_EMP_CONTAS_CONTABEISNavigation { get; set; }
        public virtual ICollection<GE_EMPRESAS_PADRAO> GE_EMPRESAS_PADRAOCOD_EMP_GRUPO_COMISSOESNavigation { get; set; }
        public virtual ICollection<GE_EMPRESAS_PADRAO> GE_EMPRESAS_PADRAOCOD_EMP_INDICENavigation { get; set; }
        public virtual ICollection<GE_EMPRESAS_PADRAO> GE_EMPRESAS_PADRAOCOD_EMP_LISTA_PRECONavigation { get; set; }
        public virtual ICollection<GE_EMPRESAS_PADRAO> GE_EMPRESAS_PADRAOCOD_EMP_MARCASNavigation { get; set; }
        public virtual ICollection<GE_EMPRESAS_PADRAO> GE_EMPRESAS_PADRAOCOD_EMP_MENSAGENSNavigation { get; set; }
        public virtual ICollection<GE_EMPRESAS_PADRAO> GE_EMPRESAS_PADRAOCOD_EMP_OPERACAO_FISCALNavigation { get; set; }
        public virtual ICollection<GE_EMPRESAS_PADRAO> GE_EMPRESAS_PADRAOCOD_EMP_OPERADORAS_CARTAONavigation { get; set; }
        public virtual ICollection<GE_EMPRESAS_PADRAO> GE_EMPRESAS_PADRAOCOD_EMP_PESSOASNavigation { get; set; }
        public virtual ICollection<GE_EMPRESAS_PADRAO> GE_EMPRESAS_PADRAOCOD_EMP_PRODUTOSNavigation { get; set; }
        public virtual ICollection<GE_EMPRESAS_PADRAO> GE_EMPRESAS_PADRAOCOD_EMP_PRODUTOS_VALORESNavigation { get; set; }
        public virtual ICollection<GE_EMPRESAS_PADRAO> GE_EMPRESAS_PADRAOCOD_EMP_PRODUTO_ALMOXARIFADOSNavigation { get; set; }
        public virtual ICollection<GE_EMPRESAS_PADRAO> GE_EMPRESAS_PADRAOCOD_EMP_PRODUTO_COMPOSICAONavigation { get; set; }
        public virtual ICollection<GE_EMPRESAS_PADRAO> GE_EMPRESAS_PADRAOCOD_EMP_PROGRAMA_FIDELIDADENavigation { get; set; }
        public virtual ICollection<GE_EMPRESAS_PADRAO> GE_EMPRESAS_PADRAOCOD_EMP_PROMOCOESNavigation { get; set; }
        public virtual ICollection<GE_EMPRESAS_PADRAO> GE_EMPRESAS_PADRAOCOD_EMP_REGRA_TRIBUTACAONavigation { get; set; }
        public virtual ICollection<GE_EMPRESAS_PADRAO> GE_EMPRESAS_PADRAOCOD_EMP_STATUS_ORDEMNavigation { get; set; }
        public virtual ICollection<GE_EMPRESAS_PADRAO> GE_EMPRESAS_PADRAOCOD_EMP_TECNICO_ORDEMNavigation { get; set; }
        public virtual ICollection<GE_EMPRESAS_PADRAO> GE_EMPRESAS_PADRAOCOD_EMP_TIPOS_ORDEMNavigation { get; set; }
        public virtual ICollection<GE_EMPRESAS_PADRAO> GE_EMPRESAS_PADRAOCOD_EMP_TIPOS_PAGAMENTOS_CONDICOES_PAGAMENTOSNavigation { get; set; }
        public virtual ICollection<GE_EMPRESAS_PADRAO> GE_EMPRESAS_PADRAOCOD_EMP_TIPO_MOVIMENTOS_CAIXANavigation { get; set; }
        public virtual ICollection<GE_EMPRESAS_PADRAO> GE_EMPRESAS_PADRAOCOD_EMP_TIPO_PAGAMENTONavigation { get; set; }
        public virtual ICollection<GE_EMPRESAS_PADRAO> GE_EMPRESAS_PADRAOCOD_EMP_TIPO_TITULONavigation { get; set; }
        public virtual ICollection<GE_EMPRESAS_PADRAO> GE_EMPRESAS_PADRAOCOD_EMP_UNIDADE_MEDIDANavigation { get; set; }
        public virtual ICollection<GE_EMPRESAS_UF> GE_EMPRESAS_UF { get; set; }
        public virtual ICollection<GE_ETIQUETAS> GE_ETIQUETAS { get; set; }
        public virtual ICollection<GE_FILA_SPED_FISCAL> GE_FILA_SPED_FISCAL { get; set; }
        public virtual ICollection<GE_GESTAO_COMPARTILHAMENTOS> GE_GESTAO_COMPARTILHAMENTOS { get; set; }
        public virtual ICollection<GE_GESTAO_COMPARTILHAMENTOS_PROCESSOS_PERMISSOES> GE_GESTAO_COMPARTILHAMENTOS_PROCESSOS_PERMISSOES { get; set; }
        public virtual ICollection<GE_IBPT> GE_IBPT { get; set; }
        public virtual ICollection<GE_INDICES> GE_INDICES { get; set; }
        public virtual ICollection<GE_INTERMEDIADOR> GE_INTERMEDIADOR { get; set; }
        public virtual ICollection<GE_INTREGRACAO_WHATSAPP> GE_INTREGRACAO_WHATSAPP { get; set; }
        public virtual ICollection<GE_LISTA_PRECOS> GE_LISTA_PRECOS { get; set; }
        public virtual ICollection<GE_LOGS_COMPARTILHAMENTOS> GE_LOGS_COMPARTILHAMENTOS { get; set; }
        public virtual ICollection<GE_MARCAS> GE_MARCAS { get; set; }
        public virtual ICollection<GE_MENSAGEM_PADRAO> GE_MENSAGEM_PADRAO { get; set; }
        public virtual ICollection<GE_MENSAGENS> GE_MENSAGENS { get; set; }
        public virtual ICollection<GE_OPERACAO_FISCAL> GE_OPERACAO_FISCAL { get; set; }
        public virtual ICollection<GE_OPERADORAS_CARTAO> GE_OPERADORAS_CARTAO { get; set; }
        public virtual ICollection<GE_POSICAO> GE_POSICAO { get; set; }
        public virtual ICollection<GE_PROGRAMA_FIDELIDADE> GE_PROGRAMA_FIDELIDADE { get; set; }
        public virtual ICollection<GE_PROPRIETARIO_VEICULOS> GE_PROPRIETARIO_VEICULOS { get; set; }
        public virtual ICollection<GE_REGRAS_TRIBUTACAO> GE_REGRAS_TRIBUTACAO { get; set; }
        public virtual ICollection<GE_REGRAS_TRIBUTACAO_XML_ENTRADA> GE_REGRAS_TRIBUTACAO_XML_ENTRADA { get; set; }
        public virtual ICollection<GE_RELACOES_LISTAS_PRECOS> GE_RELACOES_LISTAS_PRECOS { get; set; }
        public virtual ICollection<GE_SEGURADORAS> GE_SEGURADORAS { get; set; }
        public virtual ICollection<GE_TIPOS_PAGAMENTOS_CONDICOES_PAGAMENTOS> GE_TIPOS_PAGAMENTOS_CONDICOES_PAGAMENTOS { get; set; }
        public virtual ICollection<GE_TIPO_ENDERECO> GE_TIPO_ENDERECO { get; set; }
        public virtual ICollection<GE_TIPO_PAGAMENTO> GE_TIPO_PAGAMENTO { get; set; }
        public virtual ICollection<GE_TIPO_TELEFONE> GE_TIPO_TELEFONE { get; set; }
        public virtual ICollection<GE_TIPO_TITULO> GE_TIPO_TITULO { get; set; }
        public virtual ICollection<GE_UNIDADE_MEDIDA> GE_UNIDADE_MEDIDA { get; set; }
        public virtual ICollection<GE_USUARIOS> GE_USUARIOS { get; set; }
        public virtual ICollection<GE_VEICULOS> GE_VEICULOS { get; set; }
        public virtual ICollection<GE_EMPRESAS> InverseCOD_EMPRESA_MATRIZNavigation { get; set; }
        public virtual ICollection<OS_ORDEM> OS_ORDEM { get; set; }
        public virtual ICollection<OS_ORDEM_MATERIAIS> OS_ORDEM_MATERIAIS { get; set; }
        public virtual ICollection<OS_ORDEM_SERVICO> OS_ORDEM_SERVICO { get; set; }
        public virtual ICollection<OS_PARAMETROS> OS_PARAMETROS { get; set; }
        public virtual ICollection<PS_CANAL_VENDAS> PS_CANAL_VENDAS { get; set; }
        public virtual ICollection<PS_CLIENTES_VENCIMENTOS> PS_CLIENTES_VENCIMENTOS { get; set; }
        public virtual ICollection<PS_CONTRATOS> PS_CONTRATOS { get; set; }
        public virtual ICollection<PS_CONTRATOS_ITENS> PS_CONTRATOS_ITENS { get; set; }
        public virtual ICollection<PS_CONTRATOS_REAJUSTES> PS_CONTRATOS_REAJUSTES { get; set; }
        public virtual ICollection<PS_LANCAMENTOS> PS_LANCAMENTOS { get; set; }
        public virtual ICollection<PS_LANCAMENTOS_ITENS> PS_LANCAMENTOS_ITENS { get; set; }
        public virtual ICollection<PS_LANCAMENTOS_VENCIMENTO> PS_LANCAMENTOS_VENCIMENTO { get; set; }
        public virtual ICollection<PS_PESSOAS> PS_PESSOASCOD_EMPRESANavigation { get; set; }
        public virtual ICollection<PS_PESSOAS> PS_PESSOASCOD_EMPRESA_ORIGEMNavigation { get; set; }
        public virtual ICollection<PS_RAMOS_ATIVIDADES> PS_RAMOS_ATIVIDADES { get; set; }
        public virtual ICollection<SW_CLIENTES_PEDIDOS_ISET> SW_CLIENTES_PEDIDOS_ISET { get; set; }
        public virtual ICollection<SW_CLIENTES_PEDIDOS_TRAY> SW_CLIENTES_PEDIDOS_TRAY { get; set; }
        public virtual ICollection<SW_EMAILS_ALERTAS_ISET> SW_EMAILS_ALERTAS_ISET { get; set; }
        public virtual ICollection<SW_EMAILS_ALERTAS_TRAY> SW_EMAILS_ALERTAS_TRAY { get; set; }
        public virtual ICollection<SW_ERROS_APLICACAO> SW_ERROS_APLICACAO { get; set; }
        public virtual ICollection<SW_LOG_REGISTROS> SW_LOG_REGISTROS { get; set; }
        public virtual ICollection<SW_PAGAMENTOS_PEDIDOS_ISET> SW_PAGAMENTOS_PEDIDOS_ISET { get; set; }
        public virtual ICollection<SW_PAGAMENTOS_PEDIDOS_TRAY> SW_PAGAMENTOS_PEDIDOS_TRAY { get; set; }
        public virtual ICollection<SW_PEDIDOS_ISET> SW_PEDIDOS_ISET { get; set; }
        public virtual ICollection<SW_PEDIDOS_ISET_ITENS> SW_PEDIDOS_ISET_ITENS { get; set; }
        public virtual ICollection<SW_PEDIDOS_TRAY> SW_PEDIDOS_TRAY { get; set; }
        public virtual ICollection<SW_PEDIDOS_TRAY_ITENS> SW_PEDIDOS_TRAY_ITENS { get; set; }
        public virtual ICollection<SW_PROCESSOS_FIFO> SW_PROCESSOS_FIFO { get; set; }
        public virtual ICollection<SW_RELACAO_PAGAMENTO_ISET> SW_RELACAO_PAGAMENTO_ISET { get; set; }
        public virtual ICollection<SW_RELACAO_PAGAMENTO_TRAY> SW_RELACAO_PAGAMENTO_TRAY { get; set; }
        public virtual ICollection<SW_RELACAO_TIPO_PAGAMENTO_TRAY> SW_RELACAO_TIPO_PAGAMENTO_TRAY { get; set; }
        public virtual ICollection<SW_USUARIOS_LOGADOS> SW_USUARIOS_LOGADOS { get; set; }

        public virtual ICollection<GE_USUARIOS> COD_USUARIO { get; set; }
    }
}