// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class GE_ETIQUETAS
    {
        public int COD_ETIQUETA { get; set; }
        public int COD_EMPRESA { get; set; }
        public int COD_ENTIDADES { get; set; }
        public string? DES_ETIQUETA { get; set; }
        public string? DES_OBSERVACAO { get; set; }
        public DateTime DTA_CRIACAO { get; set; }
        public int COD_USUARIO { get; set; }
        public int NUM_COLUNAS { get; set; }
        public decimal NUM_ALTURA { get; set; }
        public decimal NUM_LARGURA { get; set; }
        public string? DES_JSON { get; set; }
        public decimal? NUM_ESPACAMENTO_COLUNAS { get; set; }
        public decimal? NUM_ESPACAMENTO_LINHAS { get; set; }

        public virtual GE_EMPRESAS COD_EMPRESANavigation { get; set; } = null!;
        public virtual SW_ENTIDADES COD_ENTIDADESNavigation { get; set; } = null!;
        public virtual GE_USUARIOS COD_USUARIONavigation { get; set; } = null!;
    }
}