// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class GE_EMAILS_ENVIADOS
    {
        public GE_EMAILS_ENVIADOS()
        {
            GE_ANEXOS_EMAIL = new HashSet<GE_ANEXOS_EMAIL>();
        }

        public int COD_EMAIL { get; set; }
        public DateTime? DTA_CRIACAO { get; set; }
        public int COD_CONTA_EMAIL { get; set; }
        public string? DES_ASSUNTO { get; set; }
        public string? DES_MENSAGEM { get; set; }
        public string? DES_REMETENTE { get; set; }
        public string? DES_DESTINATARIO { get; set; }
        public bool? TIP_MENSAGEM_HTML { get; set; }
        public DateTime? DTA_ENVIO { get; set; }
        public string? DES_LOG { get; set; }
        public int COD_ORGANIZACAO { get; set; }
        public int? COD_EMPRESA { get; set; }
        public int? COD_PROCESSO { get; set; }
        public string? COD_CHAVE_ENTIDADE { get; set; }
        public int? COD_USUARIO { get; set; }
        public int? IND_STATUS { get; set; }
        public string? DES_GUID { get; set; }

        public virtual GE_CONTAS_EMAIL COD_CONTA_EMAILNavigation { get; set; } = null!;
        public virtual GE_EMPRESAS? COD_EMPRESANavigation { get; set; }
        public virtual GE_ORGANIZACAO COD_ORGANIZACAONavigation { get; set; } = null!;
        public virtual SW_PROCESSOS? COD_PROCESSONavigation { get; set; }
        public virtual GE_USUARIOS? COD_USUARIONavigation { get; set; }
        public virtual ICollection<GE_ANEXOS_EMAIL> GE_ANEXOS_EMAIL { get; set; }
    }
}