// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class GE_EMPRESAS_PADRAO
    {
        public GE_EMPRESAS_PADRAO()
        {
            GE_PROMOCOES = new HashSet<GE_PROMOCOES>();
            OS_STATUS_ORDEM = new HashSet<OS_STATUS_ORDEM>();
            OS_TECNICOS = new HashSet<OS_TECNICOS>();
            OS_TIPOS_ORDEM = new HashSet<OS_TIPOS_ORDEM>();
        }

        public int COD_EMPRESA { get; set; }
        public int COD_ORGANIZACAO { get; set; }
        public int COD_EMP_PESSOAS { get; set; }
        public int? COD_EMP_OPERACAO_FISCAL { get; set; }
        public int? COD_EMP_MENSAGENS { get; set; }
        public int? COD_EMP_BANCOS { get; set; }
        public int? COD_EMP_TIPO_PAGAMENTO { get; set; }
        public int? COD_EMP_CONDICAO_PAGAMENTO { get; set; }
        public int? COD_EMP_UNIDADE_MEDIDA { get; set; }
        public int? COD_EMP_CLASSIFICACAO_FISCAL { get; set; }
        public int? COD_EMP_PRODUTOS { get; set; }
        public int? COD_EMP_TIPO_TITULO { get; set; }
        public int? COD_EMP_INDICE { get; set; }
        public int? COD_EMP_CONTAS_CONTABEIS { get; set; }
        public int? COD_EMP_MARCAS { get; set; }
        public int? COD_EMP_CATEGORIAS_PRODUTOS { get; set; }
        public int? COD_EMP_CLASSIFICACOES_PRODUTOS { get; set; }
        public int? COD_EMP_ALMOXARIFADOS { get; set; }
        public int? COD_EMP_REGRA_TRIBUTACAO { get; set; }
        public int? COD_EMP_CENTRO_CUSTO { get; set; }
        public int? COD_EMP_PRODUTO_ALMOXARIFADOS { get; set; }
        public int? COD_EMP_LISTA_PRECO { get; set; }
        public int? COD_EMP_PRODUTOS_VALORES { get; set; }
        public int? COD_EMP_OPERADORAS_CARTAO { get; set; }
        public int? COD_EMP_PRODUTO_COMPOSICAO { get; set; }
        public int? COD_EMP_PROGRAMA_FIDELIDADE { get; set; }
        public int? COD_EMP_TIPOS_PAGAMENTOS_CONDICOES_PAGAMENTOS { get; set; }
        public int? COD_EMPRESA_IBPT { get; set; }
        public int? COD_EMPRESA_IFOOD { get; set; }
        public int? COD_EMP_PROMOCOES { get; set; }
        public int? COD_EMP_TIPOS_ORDEM { get; set; }
        public int? COD_EMP_STATUS_ORDEM { get; set; }
        public int? COD_EMP_TECNICO_ORDEM { get; set; }
        public int? COD_EMP_TIPO_MOVIMENTOS_CAIXA { get; set; }
        public int? COD_EMP_PLANO_DRE { get; set; }
        public int? COD_EMP_CANAL_VENDAS { get; set; }
        public int? COD_EMP_GRUPO_COMISSOES { get; set; }

        public virtual GE_EMPRESAS COD_EMPRESANavigation { get; set; } = null!;
        public virtual GE_EMPRESAS? COD_EMPRESA_IBPTNavigation { get; set; }
        public virtual GE_EMPRESAS? COD_EMPRESA_IFOODNavigation { get; set; }
        public virtual GE_EMPRESAS? COD_EMP_ALMOXARIFADOSNavigation { get; set; }
        public virtual GE_EMPRESAS? COD_EMP_BANCOSNavigation { get; set; }
        public virtual GE_EMPRESAS? COD_EMP_CANAL_VENDASNavigation { get; set; }
        public virtual GE_EMPRESAS? COD_EMP_CATEGORIAS_PRODUTOSNavigation { get; set; }
        public virtual GE_EMPRESAS? COD_EMP_CENTRO_CUSTONavigation { get; set; }
        public virtual GE_EMPRESAS? COD_EMP_CLASSIFICACAO_FISCALNavigation { get; set; }
        public virtual GE_EMPRESAS? COD_EMP_CLASSIFICACOES_PRODUTOSNavigation { get; set; }
        public virtual GE_EMPRESAS? COD_EMP_CONDICAO_PAGAMENTONavigation { get; set; }
        public virtual GE_EMPRESAS? COD_EMP_CONTAS_CONTABEISNavigation { get; set; }
        public virtual GE_EMPRESAS? COD_EMP_GRUPO_COMISSOESNavigation { get; set; }
        public virtual GE_EMPRESAS? COD_EMP_INDICENavigation { get; set; }
        public virtual GE_EMPRESAS? COD_EMP_LISTA_PRECONavigation { get; set; }
        public virtual GE_EMPRESAS? COD_EMP_MARCASNavigation { get; set; }
        public virtual GE_EMPRESAS? COD_EMP_MENSAGENSNavigation { get; set; }
        public virtual GE_EMPRESAS? COD_EMP_OPERACAO_FISCALNavigation { get; set; }
        public virtual GE_EMPRESAS? COD_EMP_OPERADORAS_CARTAONavigation { get; set; }
        public virtual GE_EMPRESAS COD_EMP_PESSOASNavigation { get; set; } = null!;
        public virtual GE_EMPRESAS? COD_EMP_PRODUTOSNavigation { get; set; }
        public virtual GE_EMPRESAS? COD_EMP_PRODUTOS_VALORESNavigation { get; set; }
        public virtual GE_EMPRESAS? COD_EMP_PRODUTO_ALMOXARIFADOSNavigation { get; set; }
        public virtual GE_EMPRESAS? COD_EMP_PRODUTO_COMPOSICAONavigation { get; set; }
        public virtual GE_EMPRESAS? COD_EMP_PROGRAMA_FIDELIDADENavigation { get; set; }
        public virtual GE_EMPRESAS? COD_EMP_PROMOCOESNavigation { get; set; }
        public virtual GE_EMPRESAS? COD_EMP_REGRA_TRIBUTACAONavigation { get; set; }
        public virtual GE_EMPRESAS? COD_EMP_STATUS_ORDEMNavigation { get; set; }
        public virtual GE_EMPRESAS? COD_EMP_TECNICO_ORDEMNavigation { get; set; }
        public virtual GE_EMPRESAS? COD_EMP_TIPOS_ORDEMNavigation { get; set; }
        public virtual GE_EMPRESAS? COD_EMP_TIPOS_PAGAMENTOS_CONDICOES_PAGAMENTOSNavigation { get; set; }
        public virtual GE_EMPRESAS? COD_EMP_TIPO_MOVIMENTOS_CAIXANavigation { get; set; }
        public virtual GE_EMPRESAS? COD_EMP_TIPO_PAGAMENTONavigation { get; set; }
        public virtual GE_EMPRESAS? COD_EMP_TIPO_TITULONavigation { get; set; }
        public virtual GE_EMPRESAS? COD_EMP_UNIDADE_MEDIDANavigation { get; set; }
        public virtual GE_ORGANIZACAO COD_ORGANIZACAONavigation { get; set; } = null!;
        public virtual ICollection<GE_PROMOCOES> GE_PROMOCOES { get; set; }
        public virtual ICollection<OS_STATUS_ORDEM> OS_STATUS_ORDEM { get; set; }
        public virtual ICollection<OS_TECNICOS> OS_TECNICOS { get; set; }
        public virtual ICollection<OS_TIPOS_ORDEM> OS_TIPOS_ORDEM { get; set; }
    }
}