// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class GE_FAVORITOS
    {
        public int COD_FAVORITO { get; set; }
        public int COD_USUARIO { get; set; }
        public int? COD_FUNCAO { get; set; }
        public int? NUM_ORDEM { get; set; }

        public virtual SW_FUNCOES? COD_FUNCAONavigation { get; set; }
        public virtual GE_USUARIOS COD_USUARIONavigation { get; set; } = null!;
    }
}