// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class GE_FILA_PARAMETROS_SPED_FISCAL
    {
        public int COD_PARAMETRO { get; set; }
        public int COD_FILA { get; set; }
        public string? DES_JSON { get; set; }

        public virtual GE_FILA_SPED_FISCAL COD_FILANavigation { get; set; } = null!;
    }
}