// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class GE_GESTAO_COMPARTILHAMENTOS_PROCESSOS_PERMISSOES
    {
        public int COD_PERMISSAO { get; set; }
        public int COD_GESTAO_PROCESSO { get; set; }
        public int? COD_USUARIO { get; set; }
        public int? COD_EMPRESA { get; set; }
        public int? COD_LOCALIZACAO { get; set; }
        public int? COD_AREA { get; set; }
        public int? COD_POSICAO { get; set; }
        public int? COD_PAPEL { get; set; }
        public int? COD_HABILIDADE { get; set; }

        public virtual GE_AREA? COD_AREANavigation { get; set; }
        public virtual GE_EMPRESAS? COD_EMPRESANavigation { get; set; }
        public virtual GE_GESTAO_COMPARTILHAMENTOS_PROCESSOS COD_GESTAO_PROCESSONavigation { get; set; } = null!;
        public virtual GE_HABILIDADES? COD_HABILIDADENavigation { get; set; }
        public virtual GE_LOCALIZACAO? COD_LOCALIZACAONavigation { get; set; }
        public virtual GE_PAPEL? COD_PAPELNavigation { get; set; }
        public virtual GE_POSICAO? COD_POSICAONavigation { get; set; }
        public virtual GE_USUARIOS? COD_USUARIONavigation { get; set; }
    }
}