// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class GE_GESTAO_COMPARTILHAMENTOS_PROCESSOS
    {
        public GE_GESTAO_COMPARTILHAMENTOS_PROCESSOS()
        {
            GE_GESTAO_COMPARTILHAMENTOS_PROCESSOS_PERMISSOES = new HashSet<GE_GESTAO_COMPARTILHAMENTOS_PROCESSOS_PERMISSOES>();
        }

        public int COD_GESTAO_PROCESSO { get; set; }
        public int COD_GESTAO { get; set; }
        public int COD_TIPO_COMPARTILHAMENTO { get; set; }
        public int IND_ENVIO_RECEBIMENTO { get; set; }
        public bool? TIP_ATIVO { get; set; }

        public virtual GE_GESTAO_COMPARTILHAMENTOS COD_GESTAONavigation { get; set; } = null!;
        public virtual GE_TIPO_COMPARTILHAMENTOS COD_TIPO_COMPARTILHAMENTONavigation { get; set; } = null!;
        public virtual ICollection<GE_GESTAO_COMPARTILHAMENTOS_PROCESSOS_PERMISSOES> GE_GESTAO_COMPARTILHAMENTOS_PROCESSOS_PERMISSOES { get; set; }
    }
}