// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class GE_HORARIO_TRABALHO_TURNOS
    {
        public int COD_HORARIO_TURNO { get; set; }
        public int? COD_HORARIO_TRABALHO { get; set; }
        public int? NUM_DIA_SEMANA { get; set; }
        public bool? TIP_TRABALHA { get; set; }
        public string? HMS_INI_1 { get; set; }
        public string? HMS_FIM_1 { get; set; }
        public string? HMS_INI_2 { get; set; }
        public string? HMS_FIM_2 { get; set; }
        public string? HMS_INI_3 { get; set; }
        public string? HMS_FIM_3 { get; set; }
        public string? HMS_INI_4 { get; set; }
        public string? HMS_FIM_4 { get; set; }
        public int? COD_ORGANIZACAO { get; set; }

        public virtual GE_HORARIO_TRABALHO? COD_HORARIO_TRABALHONavigation { get; set; }
        public virtual GE_ORGANIZACAO? COD_ORGANIZACAONavigation { get; set; }
    }
}