// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class GE_HORARIO_TRABALHO
    {
        public GE_HORARIO_TRABALHO()
        {
            GE_EMPRESAS = new HashSet<GE_EMPRESAS>();
            GE_HORARIO_TRABALHO_TURNOS = new HashSet<GE_HORARIO_TRABALHO_TURNOS>();
            GE_ORGANIZACAO = new HashSet<GE_ORGANIZACAO>();
            GE_USUARIOS = new HashSet<GE_USUARIOS>();
        }

        public int COD_HORARIO_TRABALHO { get; set; }
        public string? DES_NOME { get; set; }
        public string? DES_FANTASIA { get; set; }
        public DateTime? DTA_CRIACAO { get; set; }
        public int? COD_ORGANIZACAO { get; set; }

        public virtual GE_ORGANIZACAO? COD_ORGANIZACAONavigation { get; set; }
        public virtual ICollection<GE_EMPRESAS> GE_EMPRESAS { get; set; }
        public virtual ICollection<GE_HORARIO_TRABALHO_TURNOS> GE_HORARIO_TRABALHO_TURNOS { get; set; }
        public virtual ICollection<GE_ORGANIZACAO> GE_ORGANIZACAO { get; set; }
        public virtual ICollection<GE_USUARIOS> GE_USUARIOS { get; set; }
    }
}