// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class GE_INTREGRACAO_WHATSAPP
    {
        public int COD_INTEGRACAO { get; set; }
        public string? DES_NOME { get; set; }
        public string? DES_TOKEN { get; set; }
        public int? COD_FILA { get; set; }
        public int? COD_USUARIO_FILA { get; set; }
        public DateTime? DTA_CRIACAO { get; set; }
        public bool? TIP_PADRAO { get; set; }
        public int? COD_USUARIO { get; set; }
        public int? COD_EMPRESA { get; set; }
        public string? DES_URL { get; set; }
        public bool? MOSTRAR_ASSINATURA { get; set; }

        public virtual GE_EMPRESAS? COD_EMPRESANavigation { get; set; }
        public virtual GE_USUARIOS? COD_USUARIONavigation { get; set; }
    }
}