// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class GE_INTERMEDIADOR
    {
        public GE_INTERMEDIADOR()
        {
            FT_NOTAS = new HashSet<FT_NOTAS>();
            FT_PEDIDOS = new HashSet<FT_PEDIDOS>();
        }

        public int COD_INTERMEDADOR { get; set; }
        public string? DES_INTERMEDIADOR { get; set; }
        public string? NUM_CNPJ { get; set; }
        public int COD_EMPRESA { get; set; }
        public int? COD_REPRESENTANTE { get; set; }

        public virtual GE_EMPRESAS COD_EMPRESANavigation { get; set; } = null!;
        public virtual PS_PESSOAS? COD_REPRESENTANTENavigation { get; set; }
        public virtual ICollection<FT_NOTAS> FT_NOTAS { get; set; }
        public virtual ICollection<FT_PEDIDOS> FT_PEDIDOS { get; set; }
    }
}