// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class GE_INDICES_ITENS
    {
        public int COD_INDICE_ITEM { get; set; }
        public int COD_INDICE { get; set; }
        public DateTime DTA_INICIO { get; set; }
        public decimal PER_INDICE { get; set; }
        public int COD_ORGANIZACAO { get; set; }

        public virtual GE_INDICES COD_INDICENavigation { get; set; } = null!;
        public virtual GE_ORGANIZACAO COD_ORGANIZACAONavigation { get; set; } = null!;
    }
}