// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class GE_INDICES
    {
        public GE_INDICES()
        {
            GE_INDICES_ITENS = new HashSet<GE_INDICES_ITENS>();
            PS_CONTRATOS = new HashSet<PS_CONTRATOS>();
        }

        public int COD_INDICE { get; set; }
        public string DES_INDICE { get; set; } = null!;
        public int COD_EMPRESA { get; set; }
        public int COD_ORGANIZACAO { get; set; }

        public virtual GE_EMPRESAS COD_EMPRESANavigation { get; set; } = null!;
        public virtual GE_ORGANIZACAO COD_ORGANIZACAONavigation { get; set; } = null!;
        public virtual ICollection<GE_INDICES_ITENS> GE_INDICES_ITENS { get; set; }
        public virtual ICollection<PS_CONTRATOS> PS_CONTRATOS { get; set; }
    }
}