// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class GE_IBPT
    {
        public int COD_IBPT { get; set; }
        public int COD_NCM { get; set; }
        public int COD_EMPRESA { get; set; }
        public string? DES_EX { get; set; }
        public int? COD_TIPO { get; set; }
        public string? DES_DESCRICAO { get; set; }
        public decimal? VLR_NACIONAL_FEDERAL { get; set; }
        public decimal? VLR_IMPORTADOS_FEDERAL { get; set; }
        public decimal? VLR_ESTADUAL { get; set; }
        public decimal? VLR_MUNICIPAL { get; set; }
        public DateTime? DTA_VIGENCIA_INICIO { get; set; }
        public DateTime? DTA_VIGENCIA_FIM { get; set; }
        public string? DES_CHAVE { get; set; }
        public string? DES_VERSAO { get; set; }
        public string? DES_FONTE { get; set; }

        public virtual GE_EMPRESAS COD_EMPRESANavigation { get; set; } = null!;
    }
}