// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class GE_LISTA_PRECOS_PRODUTOS
    {
        public int COD_LISTA_PRODUTO { get; set; }
        public int COD_LISTA { get; set; }
        public int COD_PRODUTO { get; set; }
        public int COD_USUARIO { get; set; }
        public decimal? VLR_PRECO_LISTA { get; set; }
        public decimal? PER_ACRESCIMO_DESCONTO { get; set; }
        public int? IND_VALOR_BASE { get; set; }
        public int COD_COMPOSICAO { get; set; }
        public DateTime DTA_CRIACAO { get; set; }

        public virtual SW_COMPOSICAO_LISTA_PRECOS COD_COMPOSICAONavigation { get; set; } = null!;
        public virtual GE_LISTA_PRECOS COD_LISTANavigation { get; set; } = null!;
        public virtual CE_PRODUTOS COD_PRODUTONavigation { get; set; } = null!;
        public virtual GE_USUARIOS COD_USUARIONavigation { get; set; } = null!;
    }
}