// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class GE_LOCALIZACAO
    {
        public GE_LOCALIZACAO()
        {
            CO_REGRAS_APROVADORES_USUARIOS = new HashSet<CO_REGRAS_APROVADORES_USUARIOS>();
            GE_EMPRESAS = new HashSet<GE_EMPRESAS>();
            GE_GESTAO_COMPARTILHAMENTOS_PROCESSOS_PERMISSOES = new HashSet<GE_GESTAO_COMPARTILHAMENTOS_PROCESSOS_PERMISSOES>();
            GE_USUARIOS = new HashSet<GE_USUARIOS>();
            InverseCOD_LOCALIZACAO_PAINavigation = new HashSet<GE_LOCALIZACAO>();
        }

        public int COD_LOCALIZACAO { get; set; }
        public string? DES_NOME { get; set; }
        public string? DES_FANTASIA { get; set; }
        public int? COD_ORGANIZACAO { get; set; }
        public int? COD_LOCALIZACAO_PAI { get; set; }

        public virtual GE_LOCALIZACAO? COD_LOCALIZACAO_PAINavigation { get; set; }
        public virtual GE_ORGANIZACAO? COD_ORGANIZACAONavigation { get; set; }
        public virtual ICollection<CO_REGRAS_APROVADORES_USUARIOS> CO_REGRAS_APROVADORES_USUARIOS { get; set; }
        public virtual ICollection<GE_EMPRESAS> GE_EMPRESAS { get; set; }
        public virtual ICollection<GE_GESTAO_COMPARTILHAMENTOS_PROCESSOS_PERMISSOES> GE_GESTAO_COMPARTILHAMENTOS_PROCESSOS_PERMISSOES { get; set; }
        public virtual ICollection<GE_USUARIOS> GE_USUARIOS { get; set; }
        public virtual ICollection<GE_LOCALIZACAO> InverseCOD_LOCALIZACAO_PAINavigation { get; set; }
    }
}