// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class GE_LOGS_COMPARTILHAMENTOS
    {
        public int COD_LOG { get; set; }
        public int COD_EMPRESA { get; set; }
        public int COD_USUARIO { get; set; }
        public DateTime DTA_COMPARTILHAMENTO { get; set; }
        public int IND_TIPO_PROCESSO { get; set; }
        public string? DES_OBSERVACAO { get; set; }
        public string DES_GUID_COMPARTILHAMENTO { get; set; } = null!;
        public string? DES_DESTINATARIO { get; set; }
        public string NUM_CPF_CNPJ_DESTINATARIO { get; set; } = null!;

        public virtual GE_EMPRESAS COD_EMPRESANavigation { get; set; } = null!;
        public virtual GE_USUARIOS COD_USUARIONavigation { get; set; } = null!;
        public virtual GE_TIPO_COMPARTILHAMENTOS IND_TIPO_PROCESSONavigation { get; set; } = null!;
    }
}