// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class GE_LISTA_PRECOS
    {
        public GE_LISTA_PRECOS()
        {
            FT_NOTAS = new HashSet<FT_NOTAS>();
            GE_CONFIG_INTEGRACAO_ISET = new HashSet<GE_CONFIG_INTEGRACAO_ISET>();
            GE_CONFIG_INTEGRACAO_TRAY = new HashSet<GE_CONFIG_INTEGRACAO_TRAY>();
            GE_LISTA_PRECOS_PRODUTOS = new HashSet<GE_LISTA_PRECOS_PRODUTOS>();
            GE_PARAMETROS = new HashSet<GE_PARAMETROS>();
            GE_RELACOES_LISTAS_PRECOS = new HashSet<GE_RELACOES_LISTAS_PRECOS>();
            InverseCOD_LISTA_HISTORICONavigation = new HashSet<GE_LISTA_PRECOS>();
        }

        public int COD_LISTA { get; set; }
        public string? DES_LISTA { get; set; }
        public int COD_USUARIO { get; set; }
        public string? DES_OBS { get; set; }
        public DateTime DTA_CRIACAO { get; set; }
        public DateTime? DTA_VALIDADE_INICIAL { get; set; }
        public DateTime? DTA_VALIDADE_FINAL { get; set; }
        public int COD_EMPRESA { get; set; }
        public int COD_ORGANIZACAO { get; set; }
        public int? COD_LISTA_HISTORICO { get; set; }
        public bool? TIP_LISTAR_FRENTE_CAIXA { get; set; }
        public bool? TIP_VALOR_FINAL { get; set; }

        public virtual GE_EMPRESAS COD_EMPRESANavigation { get; set; } = null!;
        public virtual GE_LISTA_PRECOS? COD_LISTA_HISTORICONavigation { get; set; }
        public virtual GE_ORGANIZACAO COD_ORGANIZACAONavigation { get; set; } = null!;
        public virtual GE_USUARIOS COD_USUARIONavigation { get; set; } = null!;
        public virtual ICollection<FT_NOTAS> FT_NOTAS { get; set; }
        public virtual ICollection<GE_CONFIG_INTEGRACAO_ISET> GE_CONFIG_INTEGRACAO_ISET { get; set; }
        public virtual ICollection<GE_CONFIG_INTEGRACAO_TRAY> GE_CONFIG_INTEGRACAO_TRAY { get; set; }
        public virtual ICollection<GE_LISTA_PRECOS_PRODUTOS> GE_LISTA_PRECOS_PRODUTOS { get; set; }
        public virtual ICollection<GE_PARAMETROS> GE_PARAMETROS { get; set; }
        public virtual ICollection<GE_RELACOES_LISTAS_PRECOS> GE_RELACOES_LISTAS_PRECOS { get; set; }
        public virtual ICollection<GE_LISTA_PRECOS> InverseCOD_LISTA_HISTORICONavigation { get; set; }
    }
}