// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class GE_MENSAGENS
    {
        public GE_MENSAGENS()
        {
            GE_MENSAGEM_PADRAO = new HashSet<GE_MENSAGEM_PADRAO>();
            GE_OPERACAO_FISCAL_MENSAGENS = new HashSet<GE_OPERACAO_FISCAL_MENSAGENS>();
        }

        public int COD_MENSAGEM { get; set; }
        public string DES_MENSAGEM { get; set; } = null!;
        public int COD_EMPRESA { get; set; }
        public int? COD_ORGANIZACAO { get; set; }
        public string? COD_APLICACAO_EXTERNA { get; set; }

        public virtual GE_EMPRESAS COD_EMPRESANavigation { get; set; } = null!;
        public virtual GE_ORGANIZACAO? COD_ORGANIZACAONavigation { get; set; }
        public virtual ICollection<GE_MENSAGEM_PADRAO> GE_MENSAGEM_PADRAO { get; set; }
        public virtual ICollection<GE_OPERACAO_FISCAL_MENSAGENS> GE_OPERACAO_FISCAL_MENSAGENS { get; set; }
    }
}