// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class GE_MENSAGEM_PADRAO
    {
        public int COD_MENSAGEM_PADRAO { get; set; }
        public int COD_MENSAGEM { get; set; }
        public int COD_TIPO { get; set; }
        public int COD_EMPRESA { get; set; }
        public int NUM_SEQUENCIA { get; set; }

        public virtual GE_EMPRESAS COD_EMPRESANavigation { get; set; } = null!;
        public virtual GE_MENSAGENS COD_MENSAGEMNavigation { get; set; } = null!;
        public virtual SW_TIPO_MENSAGENS COD_TIPONavigation { get; set; } = null!;
    }
}