// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class GE_OPERACAO_FISCAL
    {
        public GE_OPERACAO_FISCAL()
        {
            CE_NOTAS = new HashSet<CE_NOTAS>();
            CE_NOTAS_ITENS = new HashSet<CE_NOTAS_ITENS>();
            CE_NOTAS_PENDENCIAS_PRODUTOS = new HashSet<CE_NOTAS_PENDENCIAS_PRODUTOS>();
            CE_PRODUTO_TRIBUTACAO = new HashSet<CE_PRODUTO_TRIBUTACAO>();
            CO_ORDENS = new HashSet<CO_ORDENS>();
            CO_ORDENS_ITENS = new HashSet<CO_ORDENS_ITENS>();
            FT_NOTAS = new HashSet<FT_NOTAS>();
            FT_NOTAS_ITENS = new HashSet<FT_NOTAS_ITENS>();
            FT_PEDIDOS = new HashSet<FT_PEDIDOS>();
            FT_PEDIDOS_ITENS = new HashSet<FT_PEDIDOS_ITENS>();
            GE_OPERACAO_FISCAL_MENSAGENS = new HashSet<GE_OPERACAO_FISCAL_MENSAGENS>();
            GE_REGRAS_TRIBUTACAOCOD_OPERACAO_FISCALNavigation = new HashSet<GE_REGRAS_TRIBUTACAO>();
            GE_REGRAS_TRIBUTACAOCOD_OPERACAO_FISCAL_CONSUMIDOR_FINALNavigation = new HashSet<GE_REGRAS_TRIBUTACAO>();
            GE_REGRAS_TRIBUTACAOCOD_OPERACAO_FISCAL_NAO_CONTRIBUINTENavigation = new HashSet<GE_REGRAS_TRIBUTACAO>();
            GE_REGRAS_TRIBUTACAO_XML_ENTRADACOD_OPERACAO_FISCAL_COMPRANavigation = new HashSet<GE_REGRAS_TRIBUTACAO_XML_ENTRADA>();
            GE_REGRAS_TRIBUTACAO_XML_ENTRADACOD_OPERACAO_FISCAL_NOTANavigation = new HashSet<GE_REGRAS_TRIBUTACAO_XML_ENTRADA>();
            GE_REGRAS_TRIBUTACAO_XML_ENTRADACOD_OPERACAO_FISCAL_PDVNavigation = new HashSet<GE_REGRAS_TRIBUTACAO_XML_ENTRADA>();
            InverseCOD_OPERACAO_DEVOLUCAONavigation = new HashSet<GE_OPERACAO_FISCAL>();
            InverseCOD_OPERACAO_FISCAL_NFCENavigation = new HashSet<GE_OPERACAO_FISCAL>();
            OS_ORDEM_MATERIAIS = new HashSet<OS_ORDEM_MATERIAIS>();
            OS_ORDEM_SERVICO = new HashSet<OS_ORDEM_SERVICO>();
        }

        public int COD_OPERACAO_FISCAL { get; set; }
        public string? DES_OPERACAO_FISCAL { get; set; }
        public int? COD_CFOP { get; set; }
        public int? IND_TIPO_OPERACAO { get; set; }
        public int COD_EMPRESA { get; set; }
        public int COD_ORGANIZACAO { get; set; }
        public decimal? PER_ISS { get; set; }
        public decimal? PER_IR { get; set; }
        public decimal? PER_PIS { get; set; }
        public decimal? PER_COFINS { get; set; }
        public decimal? PER_CSLL { get; set; }
        public decimal? PER_INSS { get; set; }
        public string? DES_NOTA { get; set; }
        public string? NUM_CST_ICMS { get; set; }
        public string? NUM_CST_IPI { get; set; }
        public string? NUM_CST_PIS { get; set; }
        public string? NUM_CST_COFINS { get; set; }
        public decimal? PER_REDUCAO_BASE_ICMS { get; set; }
        public decimal? PER_ICMS_DIFERIDO { get; set; }
        public bool? TIP_SOMAR_IPI_BASE_ICMS { get; set; }
        public bool? TIP_SOMAR_FRETE_BASE_ICMS { get; set; }
        public bool? TIP_SOMAR_DESPESAS_BASE_ICMS { get; set; }
        public int? COD_CFOP_FORA_ESTADO { get; set; }
        public int? COD_CFOP_EXTERIOR { get; set; }
        public int? IND_DIFERENCIAL_ALIQUOTA { get; set; }
        public bool? TIP_SOMAR_FRETE_BASE_IPI { get; set; }
        public string? COD_ENQUADRAMENTO_IPI { get; set; }
        public decimal? PER_REDUCAO_BASE_IPI { get; set; }
        public bool? TIP_CONSIDERAR_DESCONTO_IPI { get; set; }
        public decimal? PER_REDUCAO_BASE_PIS { get; set; }
        public decimal? PER_REDUCAO_BASE_COFINS { get; set; }
        public decimal? PER_PIS_ST { get; set; }
        public decimal? PER_COFINS_ST { get; set; }
        public bool? TIP_ST_SEM_REDUCAO_ICMS { get; set; }
        public bool? TIP_CALCULAR_SUBSTITUICAO_TRIBUTARIA { get; set; }
        public int? IND_ENTRADA_SAIDA { get; set; }
        public bool? TIP_MOVIMENTA_ESTOQUE { get; set; }
        public bool? TIP_FCP_ST { get; set; }
        public string? COD_APLICACAO_EXTERNA { get; set; }
        public bool? TIP_CALCULAR_FCP { get; set; }
        public int? IND_ICMS_CUSTO_REAL { get; set; }
        public int? IND_IPI_CUSTO_REAL { get; set; }
        public int? IND_PIS_CUSTO_REAL { get; set; }
        public int? IND_COFINS_CUSTO_REAL { get; set; }
        public int? IND_IMPOSTO_IMPORTACAO_CUSTO_REAL { get; set; }
        public int? IND_DIFERENCA_ICMS_CUSTO_REAL { get; set; }
        public int? IND_ST_CUSTO_REAL { get; set; }
        public int? IND_FRETE_CUSTO_REAL { get; set; }
        public int? IND_DESPESAS_CUSTO_REAL { get; set; }
        public int? IND_SEGURO_CUSTO_REAL { get; set; }
        public int? IND_ICMS_CUSTO_REPOSICAO { get; set; }
        public int? IND_IPI_CUSTO_REPOSICAO { get; set; }
        public int? IND_PIS_CUSTO_REPOSICAO { get; set; }
        public int? IND_COFINS_CUSTO_REPOSICAO { get; set; }
        public int? IND_DIFERENCA_ICMS_CUSTO_REPOSICAO { get; set; }
        public int? IND_ST_CUSTO_REPOSICAO { get; set; }
        public int? IND_FRETE_CUSTO_REPOSICAO { get; set; }
        public int? IND_IMPOSTO_IMPORTACAO_CUSTO_REPOSICAO { get; set; }
        public int? IND_SEGURO_CUSTO_REPOSICAO { get; set; }
        public int? IND_DESPESAS_CUSTO_REPOSICAO { get; set; }
        public bool? TIP_ATUALIZA_CUSTOS { get; set; }
        public bool? TIP_ICMS_CAMPO_PROPRIO { get; set; }
        public bool? TIP_CALCULAR_IMPOSTOS_LEI_FEDERAL { get; set; }
        public bool? TIP_SOMAR_SEGURO_BASE_ICMS { get; set; }
        public bool? TIP_SOMAR_DESPESAS_BASE_IPI { get; set; }
        public bool? TIP_SOMAR_SEGURO_BASE_IPI { get; set; }
        public bool? TIP_SOMAR_SEGURO_BASE_PIS { get; set; }
        public bool? TIP_SOMAR_SEGURO_BASE_COFINS { get; set; }
        public bool? TIP_CONSIDERAR_COMISSAO { get; set; }
        public string? COD_CBENF { get; set; }
        public int? COD_OPERACAO_FISCAL_NFCE { get; set; }
        public bool? TIP_NAO_CONSIDERAR_RELATORIO_VENDAS { get; set; }
        public bool? TIP_NAO_GERAR_FINANCEIRO { get; set; }
        public int? COD_OPERACAO_DEVOLUCAO { get; set; }
        public bool? TIP_OBRIGAR_FCI { get; set; }
        public bool? TIP_ABATER_ICMS_BASE_PIS { get; set; }
        public bool? TIP_ABATER_ICMS_BASE_COFINS { get; set; }
        public bool? TIP_NAO_CONSIDERAR_RELATORIO_COMPRAS { get; set; }
        public int? COD_CONTA_CONTABIL { get; set; }
        public int? COD_CENTRO_CUSTO { get; set; }
        public bool? TIP_RESPEITAR_OPERACAO { get; set; }
        public int? IND_VALOR_VENDA { get; set; }
        public bool? TIP_NAO_GERAR_SPED_FISCAL { get; set; }
        public bool? TIP_ST_OBSERVACOES { get; set; }
        public bool? TIP_IPI_OBSERVACOES { get; set; }
        public bool? TIP_NAO_GERAR_PIS { get; set; }
        public bool? TIP_NAO_GERAR_CONFIS { get; set; }
        public bool? TIP_NAO_LISTAR_LIVROS { get; set; }
        public bool? TIP_DESCONTO_SUFRAMA { get; set; }
        public bool? TIP_INATIVAR { get; set; }
        public bool? TIP_BLOQUEAR_ALTERACAO_OPERACAO { get; set; }
        public int? COD_USUARIO_INATIVACAO { get; set; }
        public int? COD_USUARIO_BLOQUEIO { get; set; }
        public DateTime? DTA_BLOQUEIO { get; set; }
        public DateTime? DTA_INATIVACAO { get; set; }
        public bool? TIP_EXCLUIDO { get; set; }
        public int? COD_USUARIO_ATIVACAO { get; set; }
        public int? COD_USUARIO_DESBLOQUEIO { get; set; }
        public DateTime? DTA_DESBLOQUEIO { get; set; }
        public DateTime? DTA_ATIVACAO { get; set; }

        public virtual GE_CENTRO_CUSTOS? COD_CENTRO_CUSTONavigation { get; set; }
        public virtual SW_CFOP? COD_CFOP_EXTERIORNavigation { get; set; }
        public virtual SW_CFOP? COD_CFOP_FORA_ESTADONavigation { get; set; }
        public virtual GE_CONTAS_CONTABEIS? COD_CONTA_CONTABILNavigation { get; set; }
        public virtual GE_EMPRESAS COD_EMPRESANavigation { get; set; } = null!;
        public virtual SW_ENQUADRAMENTO_IPI? COD_ENQUADRAMENTO_IPINavigation { get; set; }
        public virtual GE_OPERACAO_FISCAL? COD_OPERACAO_DEVOLUCAONavigation { get; set; }
        public virtual GE_OPERACAO_FISCAL? COD_OPERACAO_FISCAL_NFCENavigation { get; set; }
        public virtual GE_ORGANIZACAO COD_ORGANIZACAONavigation { get; set; } = null!;
        public virtual GE_USUARIOS? COD_USUARIO_ATIVACAONavigation { get; set; }
        public virtual GE_USUARIOS? COD_USUARIO_BLOQUEIONavigation { get; set; }
        public virtual GE_USUARIOS? COD_USUARIO_DESBLOQUEIONavigation { get; set; }
        public virtual GE_USUARIOS? COD_USUARIO_INATIVACAONavigation { get; set; }
        public virtual SW_CST_COFINS? NUM_CST_COFINSNavigation { get; set; }
        public virtual SW_CST_ICMS? NUM_CST_ICMSNavigation { get; set; }
        public virtual SW_CST_IPI? NUM_CST_IPINavigation { get; set; }
        public virtual SW_CST_PIS? NUM_CST_PISNavigation { get; set; }
        public virtual ICollection<CE_NOTAS> CE_NOTAS { get; set; }
        public virtual ICollection<CE_NOTAS_ITENS> CE_NOTAS_ITENS { get; set; }
        public virtual ICollection<CE_NOTAS_PENDENCIAS_PRODUTOS> CE_NOTAS_PENDENCIAS_PRODUTOS { get; set; }
        public virtual ICollection<CE_PRODUTO_TRIBUTACAO> CE_PRODUTO_TRIBUTACAO { get; set; }
        public virtual ICollection<CO_ORDENS> CO_ORDENS { get; set; }
        public virtual ICollection<CO_ORDENS_ITENS> CO_ORDENS_ITENS { get; set; }
        public virtual ICollection<FT_NOTAS> FT_NOTAS { get; set; }
        public virtual ICollection<FT_NOTAS_ITENS> FT_NOTAS_ITENS { get; set; }
        public virtual ICollection<FT_PEDIDOS> FT_PEDIDOS { get; set; }
        public virtual ICollection<FT_PEDIDOS_ITENS> FT_PEDIDOS_ITENS { get; set; }
        public virtual ICollection<GE_OPERACAO_FISCAL_MENSAGENS> GE_OPERACAO_FISCAL_MENSAGENS { get; set; }
        public virtual ICollection<GE_REGRAS_TRIBUTACAO> GE_REGRAS_TRIBUTACAOCOD_OPERACAO_FISCALNavigation { get; set; }
        public virtual ICollection<GE_REGRAS_TRIBUTACAO> GE_REGRAS_TRIBUTACAOCOD_OPERACAO_FISCAL_CONSUMIDOR_FINALNavigation { get; set; }
        public virtual ICollection<GE_REGRAS_TRIBUTACAO> GE_REGRAS_TRIBUTACAOCOD_OPERACAO_FISCAL_NAO_CONTRIBUINTENavigation { get; set; }
        public virtual ICollection<GE_REGRAS_TRIBUTACAO_XML_ENTRADA> GE_REGRAS_TRIBUTACAO_XML_ENTRADACOD_OPERACAO_FISCAL_COMPRANavigation { get; set; }
        public virtual ICollection<GE_REGRAS_TRIBUTACAO_XML_ENTRADA> GE_REGRAS_TRIBUTACAO_XML_ENTRADACOD_OPERACAO_FISCAL_NOTANavigation { get; set; }
        public virtual ICollection<GE_REGRAS_TRIBUTACAO_XML_ENTRADA> GE_REGRAS_TRIBUTACAO_XML_ENTRADACOD_OPERACAO_FISCAL_PDVNavigation { get; set; }
        public virtual ICollection<GE_OPERACAO_FISCAL> InverseCOD_OPERACAO_DEVOLUCAONavigation { get; set; }
        public virtual ICollection<GE_OPERACAO_FISCAL> InverseCOD_OPERACAO_FISCAL_NFCENavigation { get; set; }
        public virtual ICollection<OS_ORDEM_MATERIAIS> OS_ORDEM_MATERIAIS { get; set; }
        public virtual ICollection<OS_ORDEM_SERVICO> OS_ORDEM_SERVICO { get; set; }
    }
}