// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class GE_OPERADORAS_CARTAO
    {
        public GE_OPERADORAS_CARTAO()
        {
            FT_NOTAS_PAGAMENTOS = new HashSet<FT_NOTAS_PAGAMENTOS>();
            GE_RELACAO_OPERADORAS_TIPO_PAGAMENTOS = new HashSet<GE_RELACAO_OPERADORAS_TIPO_PAGAMENTOS>();
        }

        public int COD_OPERADORA { get; set; }
        public string DES_OPERADORA { get; set; } = null!;
        public string DES_GUID { get; set; } = null!;
        public int COD_OPERADORA_SEFAZ { get; set; }
        public int COD_EMPRESA { get; set; }
        public int COD_ORGANIZACAO { get; set; }

        public virtual GE_EMPRESAS COD_EMPRESANavigation { get; set; } = null!;
        public virtual SW_OPERADORAS_CARTAO_SEFAZ COD_OPERADORA_SEFAZNavigation { get; set; } = null!;
        public virtual GE_ORGANIZACAO COD_ORGANIZACAONavigation { get; set; } = null!;
        public virtual ICollection<FT_NOTAS_PAGAMENTOS> FT_NOTAS_PAGAMENTOS { get; set; }
        public virtual ICollection<GE_RELACAO_OPERADORAS_TIPO_PAGAMENTOS> GE_RELACAO_OPERADORAS_TIPO_PAGAMENTOS { get; set; }
    }
}