// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class GE_PARAMETROS
    {
        public int COD_EMPRESA { get; set; }
        public int? COD_ORGANIZACAO { get; set; }
        public int? NUM_CASAS_VALOR_UNITARIO { get; set; }
        public int? COD_LISTA { get; set; }

        public virtual GE_LISTA_PRECOS? COD_LISTANavigation { get; set; }
        public virtual GE_ORGANIZACAO? COD_ORGANIZACAONavigation { get; set; }
    }
}