// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class GE_PROMOCOES_MARCAS
    {
        public int COD_PROMOCAO_MARCA { get; set; }
        public int COD_PROMOCAO { get; set; }
        public int COD_MARCA { get; set; }
        public decimal? VLR_PROMOCAO { get; set; }
        public decimal? PER_PROMOCAO { get; set; }
        public int? QTD_MAXIMA_AVENDER { get; set; }
        public int? QTD_VENDIDA { get; set; }
        public int? IND_PERCENTUAL_VALOR { get; set; }

        public virtual GE_MARCAS COD_MARCANavigation { get; set; } = null!;
        public virtual GE_PROMOCOES COD_PROMOCAONavigation { get; set; } = null!;
    }
}