// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class GE_PROMOCOES
    {
        public GE_PROMOCOES()
        {
            GE_PROMOCOES_CATEGORIAS = new HashSet<GE_PROMOCOES_CATEGORIAS>();
            GE_PROMOCOES_CLASSIFICACOES = new HashSet<GE_PROMOCOES_CLASSIFICACOES>();
            GE_PROMOCOES_MARCAS = new HashSet<GE_PROMOCOES_MARCAS>();
            GE_PROMOCOES_PRODUTOS = new HashSet<GE_PROMOCOES_PRODUTOS>();
        }

        public int COD_PROMOCAO { get; set; }
        public string? DES_PROMOCAO { get; set; }
        public int COD_USUARIO { get; set; }
        public string? DES_OBSERVACAO { get; set; }
        public DateTime DTA_CRIACAO { get; set; }
        public DateTime? DTA_VALIDADE_INICIAL { get; set; }
        public DateTime? DTA_VALIDADE_FINAL { get; set; }
        public int IND_TIPO_PROMOCAO { get; set; }
        public int? COD_EMPRESA { get; set; }

        public virtual GE_EMPRESAS_PADRAO? COD_EMPRESANavigation { get; set; }
        public virtual GE_USUARIOS COD_USUARIONavigation { get; set; } = null!;
        public virtual ICollection<GE_PROMOCOES_CATEGORIAS> GE_PROMOCOES_CATEGORIAS { get; set; }
        public virtual ICollection<GE_PROMOCOES_CLASSIFICACOES> GE_PROMOCOES_CLASSIFICACOES { get; set; }
        public virtual ICollection<GE_PROMOCOES_MARCAS> GE_PROMOCOES_MARCAS { get; set; }
        public virtual ICollection<GE_PROMOCOES_PRODUTOS> GE_PROMOCOES_PRODUTOS { get; set; }
    }
}