// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class GE_PROGRAMA_FIDELIDADE
    {
        public int COD_FIDELIDADE { get; set; }
        public int COD_EMPRESA { get; set; }
        public int COD_PROGRAMA { get; set; }
        public string? DES_TOKEN { get; set; }
        public decimal? VLR_FATOR_CONVERSAO { get; set; }
        public bool TIP_ATIVO { get; set; }
        public string? DES_NOME_PROGRAMA { get; set; }
        public decimal? VLR_PER_RESGATE_MAXIMO { get; set; }
        public string? DES_MENSAGEM_CUPOM { get; set; }

        public virtual GE_EMPRESAS COD_EMPRESANavigation { get; set; } = null!;
        public virtual SW_PROGRAMA_FIDELIDADE COD_PROGRAMANavigation { get; set; } = null!;
    }
}