// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class GE_REGRAS_TRIBUTACAO_XML_ENTRADA
    {
        public int COD_REGRA { get; set; }
        public int COD_EMPRESA { get; set; }
        public int NUM_CFOP_ORIGEM { get; set; }
        public string? NUM_CST_ICMS { get; set; }
        public string? NUM_CSOSN { get; set; }
        public int COD_OPERACAO_FISCAL_COMPRA { get; set; }
        public int? COD_OPERACAO_FISCAL_PDV { get; set; }
        public int? COD_OPERACAO_FISCAL_NOTA { get; set; }

        public virtual GE_EMPRESAS COD_EMPRESANavigation { get; set; } = null!;
        public virtual GE_OPERACAO_FISCAL COD_OPERACAO_FISCAL_COMPRANavigation { get; set; } = null!;
        public virtual GE_OPERACAO_FISCAL? COD_OPERACAO_FISCAL_NOTANavigation { get; set; }
        public virtual GE_OPERACAO_FISCAL? COD_OPERACAO_FISCAL_PDVNavigation { get; set; }
    }
}