// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class GE_REGRAS_TRIBUTACAO
    {
        public int COD_REGRA_TRIBUTACAO { get; set; }
        public int? COD_UF { get; set; }
        public int? COD_CLASSIFICACAO_FISCAL { get; set; }
        public string? COD_ORIGEM { get; set; }
        public int? COD_PESSSOA { get; set; }
        public int? COD_PRODUTO { get; set; }
        public int COD_EMPRESA { get; set; }
        public int COD_ORGANIZACAO { get; set; }
        public int COD_OPERACAO_FISCAL { get; set; }
        public decimal? PER_ICMS { get; set; }
        public decimal? PER_MVA { get; set; }
        public decimal? PER_ICMS_INTERNO { get; set; }
        public bool? TIP_ST_REGIME_SIMPLIFICADO { get; set; }
        public decimal? PER_CARGA_TRIBUTARIA_MEDIA { get; set; }
        public decimal? PER_REDUCAO_BASE_ST { get; set; }
        public int? IND_TIPO_PESSOA { get; set; }
        public string? DES_OBSERVACAO { get; set; }
        public int? COD_OPERACAO_FISCAL_NAO_CONTRIBUINTE { get; set; }
        public int? COD_OPERACAO_FISCAL_CONSUMIDOR_FINAL { get; set; }

        public virtual GE_CLASSIFICACAO_FISCAL? COD_CLASSIFICACAO_FISCALNavigation { get; set; }
        public virtual GE_EMPRESAS COD_EMPRESANavigation { get; set; } = null!;
        public virtual GE_OPERACAO_FISCAL COD_OPERACAO_FISCALNavigation { get; set; } = null!;
        public virtual GE_OPERACAO_FISCAL? COD_OPERACAO_FISCAL_CONSUMIDOR_FINALNavigation { get; set; }
        public virtual GE_OPERACAO_FISCAL? COD_OPERACAO_FISCAL_NAO_CONTRIBUINTENavigation { get; set; }
        public virtual GE_ORGANIZACAO COD_ORGANIZACAONavigation { get; set; } = null!;
        public virtual SW_ORIGEM_MERCADORIAS? COD_ORIGEMNavigation { get; set; }
        public virtual PS_PESSOAS? COD_PESSSOANavigation { get; set; }
        public virtual CE_PRODUTOS? COD_PRODUTONavigation { get; set; }
        public virtual SW_UF? COD_UFNavigation { get; set; }
    }
}