// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class GE_RELACOES_LISTAS_PRECOS
    {
        public int COD_RELACAO { get; set; }
        public int COD_LISTA { get; set; }
        public int COD_EMPRESA { get; set; }
        public int? COD_CLIENTE { get; set; }
        public int? COD_REPRESENTENTE { get; set; }
        public int? COD_UF { get; set; }

        public virtual PS_PESSOAS? COD_CLIENTENavigation { get; set; }
        public virtual GE_EMPRESAS COD_EMPRESANavigation { get; set; } = null!;
        public virtual GE_LISTA_PRECOS COD_LISTANavigation { get; set; } = null!;
        public virtual PS_PESSOAS? COD_REPRESENTENTENavigation { get; set; }
        public virtual SW_UF? COD_UFNavigation { get; set; }
    }
}