// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class GE_TIPO_PAGAMENTO
    {
        public GE_TIPO_PAGAMENTO()
        {
            CO_ORDENS_PAGAMENTOS = new HashSet<CO_ORDENS_PAGAMENTOS>();
            CP_HISTORICO = new HashSet<CP_HISTORICO>();
            CP_TITULOS = new HashSet<CP_TITULOS>();
            CR_HISTORICOS = new HashSet<CR_HISTORICOS>();
            CR_TITULOS = new HashSet<CR_TITULOS>();
            FT_NOTAS = new HashSet<FT_NOTAS>();
            FT_NOTAS_PAGAMENTOS = new HashSet<FT_NOTAS_PAGAMENTOS>();
            FT_PEDIDOS = new HashSet<FT_PEDIDOS>();
            FT_PEDIDOS_PAGAMENTOS = new HashSet<FT_PEDIDOS_PAGAMENTOS>();
            GE_RELACAO_OPERADORAS_TIPO_PAGAMENTOS = new HashSet<GE_RELACAO_OPERADORAS_TIPO_PAGAMENTOS>();
            GE_TIPOS_PAGAMENTOS_CONDICOES_PAGAMENTOS = new HashSet<GE_TIPOS_PAGAMENTOS_CONDICOES_PAGAMENTOS>();
            PS_CONTRATOS = new HashSet<PS_CONTRATOS>();
            SW_RELACAO_TIPO_PAGAMENTO_TRAY = new HashSet<SW_RELACAO_TIPO_PAGAMENTO_TRAY>();
        }

        public int COD_TIPO_PAGAMENTO { get; set; }
        public int COD_EMPRESA { get; set; }
        public string DES_TIPO_PAGAMENTO { get; set; } = null!;
        public int? COD_ORGANIZACAO { get; set; }
        public bool? TIP_GERA_BOLETO { get; set; }
        public int COD_TIPO_PAGAMENTO_SEFAZ { get; set; }
        public bool? TIP_PERMITE_NFCE { get; set; }
        public bool? TIP_OBRIGAR_OPERADORA_CARTAO { get; set; }
        public string? DES_TECLA_ATALHO { get; set; }
        public bool? TIP_SOLICITAR_AUTORIZACAO_CARTAO { get; set; }
        public bool? TIP_TEF { get; set; }
        public bool? TIP_OBRIGAR_INFORMAR_CAIXA { get; set; }
        public int? NUM_SEQUENCIA_PDV { get; set; }
        public bool? TIP_NAO_LISTAR_NOS_RELATORIOS { get; set; }

        public virtual GE_EMPRESAS COD_EMPRESANavigation { get; set; } = null!;
        public virtual GE_ORGANIZACAO? COD_ORGANIZACAONavigation { get; set; }
        public virtual SW_TIPOS_PAGAMENTOS COD_TIPO_PAGAMENTO_SEFAZNavigation { get; set; } = null!;
        public virtual ICollection<CO_ORDENS_PAGAMENTOS> CO_ORDENS_PAGAMENTOS { get; set; }
        public virtual ICollection<CP_HISTORICO> CP_HISTORICO { get; set; }
        public virtual ICollection<CP_TITULOS> CP_TITULOS { get; set; }
        public virtual ICollection<CR_HISTORICOS> CR_HISTORICOS { get; set; }
        public virtual ICollection<CR_TITULOS> CR_TITULOS { get; set; }
        public virtual ICollection<FT_NOTAS> FT_NOTAS { get; set; }
        public virtual ICollection<FT_NOTAS_PAGAMENTOS> FT_NOTAS_PAGAMENTOS { get; set; }
        public virtual ICollection<FT_PEDIDOS> FT_PEDIDOS { get; set; }
        public virtual ICollection<FT_PEDIDOS_PAGAMENTOS> FT_PEDIDOS_PAGAMENTOS { get; set; }
        public virtual ICollection<GE_RELACAO_OPERADORAS_TIPO_PAGAMENTOS> GE_RELACAO_OPERADORAS_TIPO_PAGAMENTOS { get; set; }
        public virtual ICollection<GE_TIPOS_PAGAMENTOS_CONDICOES_PAGAMENTOS> GE_TIPOS_PAGAMENTOS_CONDICOES_PAGAMENTOS { get; set; }
        public virtual ICollection<PS_CONTRATOS> PS_CONTRATOS { get; set; }
        public virtual ICollection<SW_RELACAO_TIPO_PAGAMENTO_TRAY> SW_RELACAO_TIPO_PAGAMENTO_TRAY { get; set; }
    }
}