// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class GE_TIPO_TELEFONE
    {
        public GE_TIPO_TELEFONE()
        {
            PS_TELEFONES = new HashSet<PS_TELEFONES>();
        }

        public int COD_TIPO_TELEFONE { get; set; }
        public int COD_EMPRESA { get; set; }
        public string DES_TIPO_TELEFONE { get; set; } = null!;
        public int? COD_ORGANIZACAO { get; set; }

        public virtual GE_EMPRESAS COD_EMPRESANavigation { get; set; } = null!;
        public virtual GE_ORGANIZACAO? COD_ORGANIZACAONavigation { get; set; }
        public virtual ICollection<PS_TELEFONES> PS_TELEFONES { get; set; }
    }
}