// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class GE_TIPOS_PAGAMENTOS_CONDICOES_PAGAMENTOS
    {
        public int COD_TIPOS_PAGAMENTOS_CONDICAO_PAGAMENTOS { get; set; }
        public int COD_EMPRESA { get; set; }
        public int COD_ORGANIZACAO { get; set; }
        public int COD_TIPO_PAGAMENTO { get; set; }
        public int COD_CONDICAO_PAGAMENTO { get; set; }
        public int? NUM_ORDEM { get; set; }

        public virtual GE_CONDICAO_PAGAMENTO COD_CONDICAO_PAGAMENTONavigation { get; set; } = null!;
        public virtual GE_EMPRESAS COD_EMPRESANavigation { get; set; } = null!;
        public virtual GE_ORGANIZACAO COD_ORGANIZACAONavigation { get; set; } = null!;
        public virtual GE_TIPO_PAGAMENTO COD_TIPO_PAGAMENTONavigation { get; set; } = null!;
    }
}