// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class GE_TIPOS_ALERTA
    {
        public GE_TIPOS_ALERTA()
        {
            GE_ALERTAS = new HashSet<GE_ALERTAS>();
            GE_ALERTAS_USUARIO = new HashSet<GE_ALERTAS_USUARIO>();
        }

        public int COD_TIPO { get; set; }
        public string? DES_TIPO { get; set; }
        public string? DES_MENSAGEM { get; set; }
        public int? COD_FUNCAO { get; set; }

        public virtual SW_FUNCOES? COD_FUNCAONavigation { get; set; }
        public virtual ICollection<GE_ALERTAS> GE_ALERTAS { get; set; }
        public virtual ICollection<GE_ALERTAS_USUARIO> GE_ALERTAS_USUARIO { get; set; }
    }
}