// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class GE_UNIDADE_MEDIDA
    {
        public GE_UNIDADE_MEDIDA()
        {
            CE_INVENTARIOS_PRODUTOS = new HashSet<CE_INVENTARIOS_PRODUTOS>();
            CE_INVENTARIO_SPED_ITENS = new HashSet<CE_INVENTARIO_SPED_ITENS>();
            CE_NOTAS_ITENSCOD_UNIDADE_CONVERSAONavigation = new HashSet<CE_NOTAS_ITENS>();
            CE_NOTAS_ITENSCOD_UNIDADE_MEDIDANavigation = new HashSet<CE_NOTAS_ITENS>();
            CE_PRODUTOS = new HashSet<CE_PRODUTOS>();
            CE_PRODUTO_CONVERSAO_UNIDADES = new HashSet<CE_PRODUTO_CONVERSAO_UNIDADES>();
            CO_ORDENS_ITENSCOD_UNIDADE_CONVERSAONavigation = new HashSet<CO_ORDENS_ITENS>();
            CO_ORDENS_ITENSCOD_UNIDADE_MEDIDANavigation = new HashSet<CO_ORDENS_ITENS>();
            FT_NOTAS_ITENSCOD_UNIDADE_CONVERSAONavigation = new HashSet<FT_NOTAS_ITENS>();
            FT_NOTAS_ITENSCOD_UNIDADE_MEDIDANavigation = new HashSet<FT_NOTAS_ITENS>();
            FT_PEDIDOS_ITENSCOD_UNIDADE_CONVERSAONavigation = new HashSet<FT_PEDIDOS_ITENS>();
            FT_PEDIDOS_ITENSCOD_UNIDADE_MEDIDANavigation = new HashSet<FT_PEDIDOS_ITENS>();
        }

        public int COD_UNIDADE_MEDIDA { get; set; }
        public string DES_UNIDADE_MEDIDA { get; set; } = null!;
        public string DES_SIGLA { get; set; } = null!;
        public int COD_EMPRESA { get; set; }
        public int? COD_ORGANIZACAO { get; set; }
        public int? NUM_CASAS_DECIMAIS { get; set; }
        public bool? TIP_LEITURA_BALANCA { get; set; }
        public bool? TIP_IMPRESSAO_ETIQUETA { get; set; }

        public virtual GE_EMPRESAS COD_EMPRESANavigation { get; set; } = null!;
        public virtual GE_ORGANIZACAO? COD_ORGANIZACAONavigation { get; set; }
        public virtual ICollection<CE_INVENTARIOS_PRODUTOS> CE_INVENTARIOS_PRODUTOS { get; set; }
        public virtual ICollection<CE_INVENTARIO_SPED_ITENS> CE_INVENTARIO_SPED_ITENS { get; set; }
        public virtual ICollection<CE_NOTAS_ITENS> CE_NOTAS_ITENSCOD_UNIDADE_CONVERSAONavigation { get; set; }
        public virtual ICollection<CE_NOTAS_ITENS> CE_NOTAS_ITENSCOD_UNIDADE_MEDIDANavigation { get; set; }
        public virtual ICollection<CE_PRODUTOS> CE_PRODUTOS { get; set; }
        public virtual ICollection<CE_PRODUTO_CONVERSAO_UNIDADES> CE_PRODUTO_CONVERSAO_UNIDADES { get; set; }
        public virtual ICollection<CO_ORDENS_ITENS> CO_ORDENS_ITENSCOD_UNIDADE_CONVERSAONavigation { get; set; }
        public virtual ICollection<CO_ORDENS_ITENS> CO_ORDENS_ITENSCOD_UNIDADE_MEDIDANavigation { get; set; }
        public virtual ICollection<FT_NOTAS_ITENS> FT_NOTAS_ITENSCOD_UNIDADE_CONVERSAONavigation { get; set; }
        public virtual ICollection<FT_NOTAS_ITENS> FT_NOTAS_ITENSCOD_UNIDADE_MEDIDANavigation { get; set; }
        public virtual ICollection<FT_PEDIDOS_ITENS> FT_PEDIDOS_ITENSCOD_UNIDADE_CONVERSAONavigation { get; set; }
        public virtual ICollection<FT_PEDIDOS_ITENS> FT_PEDIDOS_ITENSCOD_UNIDADE_MEDIDANavigation { get; set; }
    }
}