// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class GE_USUARIOS
    {
        public GE_USUARIOS()
        {
            APP_IFOOD_AUTORIZACAO = new HashSet<APP_IFOOD_AUTORIZACAO>();
            CA_ABERTURA_FECHAMENTOCOD_USUARIO_ABERTURANavigation = new HashSet<CA_ABERTURA_FECHAMENTO>();
            CA_ABERTURA_FECHAMENTOCOD_USUARIO_FECHAMENTONavigation = new HashSet<CA_ABERTURA_FECHAMENTO>();
            CA_MOVIMENTOS = new HashSet<CA_MOVIMENTOS>();
            CE_INVENTARIOSCOD_USUARIONavigation = new HashSet<CE_INVENTARIOS>();
            CE_INVENTARIOSCOD_USUARIO_ENCERRAMENTONavigation = new HashSet<CE_INVENTARIOS>();
            CE_INVENTARIOS_PRODUTOS_HISTORICOS = new HashSet<CE_INVENTARIOS_PRODUTOS_HISTORICOS>();
            CE_INVENTARIO_SPED = new HashSet<CE_INVENTARIO_SPED>();
            CE_MOVIMENTOS_ESTOQUES = new HashSet<CE_MOVIMENTOS_ESTOQUES>();
            CE_NOTAS = new HashSet<CE_NOTAS>();
            CE_NOTAS_XML = new HashSet<CE_NOTAS_XML>();
            CE_PRODUTOSCOD_USUARIO_ALTERACAONavigation = new HashSet<CE_PRODUTOS>();
            CE_PRODUTOSCOD_USUARIO_CRIACAONavigation = new HashSet<CE_PRODUTOS>();
            CO_APROVADORES = new HashSet<CO_APROVADORES>();
            CO_LOGS_STATUS_ORDENS = new HashSet<CO_LOGS_STATUS_ORDENS>();
            CO_ORDENS = new HashSet<CO_ORDENS>();
            CO_ORDENS_APROVADORES = new HashSet<CO_ORDENS_APROVADORES>();
            CO_ORDENS_ITENS = new HashSet<CO_ORDENS_ITENS>();
            CO_REGRAS_APROVADORES_USUARIOS = new HashSet<CO_REGRAS_APROVADORES_USUARIOS>();
            CR_REMESSA_OPEN_BANK = new HashSet<CR_REMESSA_OPEN_BANK>();
            FT_FATURA = new HashSet<FT_FATURA>();
            FT_LIBERACAO_MARGEM_MINIMA = new HashSet<FT_LIBERACAO_MARGEM_MINIMA>();
            FT_MDFE = new HashSet<FT_MDFE>();
            FT_MDFE_EVENTOS = new HashSet<FT_MDFE_EVENTOS>();
            FT_NOTASCOD_USUARIO_CANCELAMENTONavigation = new HashSet<FT_NOTAS>();
            FT_NOTASCOD_USUARIO_EMISSAONavigation = new HashSet<FT_NOTAS>();
            FT_NOTASCOD_USUARIO_REGERAR_DANFENavigation = new HashSet<FT_NOTAS>();
            FT_NOTAS_CARTA_CORRECAO = new HashSet<FT_NOTAS_CARTA_CORRECAO>();
            FT_NOTAS_INUTILIZADAS = new HashSet<FT_NOTAS_INUTILIZADAS>();
            FT_NOTAS_XML = new HashSet<FT_NOTAS_XML>();
            FT_PEDIDOSCOD_USUARIO_APROVACAONavigation = new HashSet<FT_PEDIDOS>();
            FT_PEDIDOSCOD_USUARIO_EMISSAONavigation = new HashSet<FT_PEDIDOS>();
            FT_PEDIDOS_HISTORICOS = new HashSet<FT_PEDIDOS_HISTORICOS>();
            GE_ADMINISTRADORES_ORGANIZACAO = new HashSet<GE_ADMINISTRADORES_ORGANIZACAO>();
            GE_ALERTAS = new HashSet<GE_ALERTAS>();
            GE_ALERTAS_PROCESSOS = new HashSet<GE_ALERTAS_PROCESSOS>();
            GE_ALERTAS_USUARIO = new HashSet<GE_ALERTAS_USUARIO>();
            GE_ANEXOS = new HashSet<GE_ANEXOS>();
            GE_ANOTACOES = new HashSet<GE_ANOTACOES>();
            GE_ANOTACOES_ANEXO = new HashSet<GE_ANOTACOES_ANEXO>();
            GE_ANOTACOES_USUARIO = new HashSet<GE_ANOTACOES_USUARIO>();
            GE_CADASTRO_FRENTE_CAIXACOD_USUARIONavigation = new HashSet<GE_CADASTRO_FRENTE_CAIXA>();
            GE_CADASTRO_FRENTE_CAIXACOD_USUARIO_DESATIVACAONavigation = new HashSet<GE_CADASTRO_FRENTE_CAIXA>();
            GE_CHATCOD_USUARIO_DESTINATARIONavigation = new HashSet<GE_CHAT>();
            GE_CHATCOD_USUARIO_REMETENTENavigation = new HashSet<GE_CHAT>();
            GE_CLASSIFICACAO_COMPONENTES_DASHBOARD = new HashSet<GE_CLASSIFICACAO_COMPONENTES_DASHBOARD>();
            GE_COLABORACAO = new HashSet<GE_COLABORACAO>();
            GE_COLABORACAO_CURTIDAS = new HashSet<GE_COLABORACAO_CURTIDAS>();
            GE_COLABORACAO_DESTINATARIO = new HashSet<GE_COLABORACAO_DESTINATARIO>();
            GE_COMENTARIOS = new HashSet<GE_COMENTARIOS>();
            GE_COMPARTILHAMENTOSCOD_USUARIO_DESCARTENavigation = new HashSet<GE_COMPARTILHAMENTOS>();
            GE_COMPARTILHAMENTOSCOD_USUARIO_IMPORTACAONavigation = new HashSet<GE_COMPARTILHAMENTOS>();
            GE_COMPONENTES_DASHBOARD = new HashSet<GE_COMPONENTES_DASHBOARD>();
            GE_COMPONENTES_PERMISSOES = new HashSet<GE_COMPONENTES_PERMISSOES>();
            GE_CONFIG_INTEGRACAO_BIMACHINE = new HashSet<GE_CONFIG_INTEGRACAO_BIMACHINE>();
            GE_CONSULTAS = new HashSet<GE_CONSULTAS>();
            GE_CONSULTAS_CONFIGURADASCOD_USUARIONavigation = new HashSet<GE_CONSULTAS_CONFIGURADAS>();
            GE_CONSULTAS_CONFIGURADASCOD_USUARIO_ALTERACAONavigation = new HashSet<GE_CONSULTAS_CONFIGURADAS>();
            GE_DASHBOARD = new HashSet<GE_DASHBOARD>();
            GE_EMAILS_ENVIADOS = new HashSet<GE_EMAILS_ENVIADOS>();
            GE_EMAILS_SPED_FISCAL = new HashSet<GE_EMAILS_SPED_FISCAL>();
            GE_ETIQUETAS = new HashSet<GE_ETIQUETAS>();
            GE_FAVORITOS = new HashSet<GE_FAVORITOS>();
            GE_FILA_SPED_FISCAL = new HashSet<GE_FILA_SPED_FISCAL>();
            GE_GESTAO_COMPARTILHAMENTOS = new HashSet<GE_GESTAO_COMPARTILHAMENTOS>();
            GE_GESTAO_COMPARTILHAMENTOS_PROCESSOS_PERMISSOES = new HashSet<GE_GESTAO_COMPARTILHAMENTOS_PROCESSOS_PERMISSOES>();
            GE_INTREGRACAO_WHATSAPP = new HashSet<GE_INTREGRACAO_WHATSAPP>();
            GE_LISTA_PRECOS = new HashSet<GE_LISTA_PRECOS>();
            GE_LISTA_PRECOS_PRODUTOS = new HashSet<GE_LISTA_PRECOS_PRODUTOS>();
            GE_LOGS_COMPARTILHAMENTOS = new HashSet<GE_LOGS_COMPARTILHAMENTOS>();
            GE_OPERACAO_FISCALCOD_USUARIO_ATIVACAONavigation = new HashSet<GE_OPERACAO_FISCAL>();
            GE_OPERACAO_FISCALCOD_USUARIO_BLOQUEIONavigation = new HashSet<GE_OPERACAO_FISCAL>();
            GE_OPERACAO_FISCALCOD_USUARIO_DESBLOQUEIONavigation = new HashSet<GE_OPERACAO_FISCAL>();
            GE_OPERACAO_FISCALCOD_USUARIO_INATIVACAONavigation = new HashSet<GE_OPERACAO_FISCAL>();
            GE_PROMOCOES = new HashSet<GE_PROMOCOES>();
            GE_USUARIOS_COMPARTILHADOS = new HashSet<GE_USUARIOS_COMPARTILHADOS>();
            InverseCOD_SUPERIORNavigation = new HashSet<GE_USUARIOS>();
            OS_ORDEM = new HashSet<OS_ORDEM>();
            PS_CONTRATOS_REAJUSTES = new HashSet<PS_CONTRATOS_REAJUSTES>();
            PS_REPRESENTANTES = new HashSet<PS_REPRESENTANTES>();
            SW_ERROS_APLICACAO = new HashSet<SW_ERROS_APLICACAO>();
            SW_LOG_ACESSO_TELA = new HashSet<SW_LOG_ACESSO_TELA>();
            SW_LOG_ATRIBUTOS = new HashSet<SW_LOG_ATRIBUTOS>();
            SW_LOG_REGISTROS = new HashSet<SW_LOG_REGISTROS>();
            SW_USUARIOS_LOGADOS = new HashSet<SW_USUARIOS_LOGADOS>();
            COD_EMPRESA1 = new HashSet<GE_EMPRESAS>();
            COD_HABILIDADE = new HashSet<GE_HABILIDADES>();
            COD_PAPEL = new HashSet<GE_PAPEL>();
            COD_POSICAO = new HashSet<GE_POSICAO>();
        }

        public int COD_USUARIO { get; set; }
        public string? DES_LOGIN { get; set; }
        public string? DES_NOME_COMPLETO { get; set; }
        public string? DES_APELIDO { get; set; }
        public int? COD_ORGANIZACAO { get; set; }
        public int? COD_AREA { get; set; }
        public int? COD_LOCALIZACAO { get; set; }
        public int? TIP_ATIVO { get; set; }
        public int? COD_SUPERIOR { get; set; }
        public bool? TIP_RECEBE_EMAIL { get; set; }
        public bool? TIP_RECEBE_ALERTA { get; set; }
        public string? DES_EMAIL { get; set; }
        public string? NUM_TELEFONE { get; set; }
        public string? NUM_CELULAR { get; set; }
        public int? COD_HORARIO_TRABALHO { get; set; }
        public int? COD_LINGUAGEM { get; set; }
        public string? DES_FOTO { get; set; }
        public string? DES_SENHA { get; set; }
        public bool? TIP_ROOT { get; set; }
        public int? COD_EMPRESA { get; set; }
        public bool? TIP_TODAS_EMPRESAS { get; set; }
        public string DES_GUID { get; set; } = null!;
        public string? DES_PERFIL { get; set; }
        public int? COD_USUARIO_ACCOUNT { get; set; }
        public bool? TIP_LIBERA_PEDIDOS { get; set; }
        public bool? TIP_HABILITAR_BLOQUEAR_OPERACAO { get; set; }

        public virtual GE_AREA? COD_AREANavigation { get; set; }
        public virtual GE_EMPRESAS? COD_EMPRESANavigation { get; set; }
        public virtual GE_HORARIO_TRABALHO? COD_HORARIO_TRABALHONavigation { get; set; }
        public virtual SW_LINGUAGEM? COD_LINGUAGEMNavigation { get; set; }
        public virtual GE_LOCALIZACAO? COD_LOCALIZACAONavigation { get; set; }
        public virtual GE_ORGANIZACAO? COD_ORGANIZACAONavigation { get; set; }
        public virtual GE_USUARIOS? COD_SUPERIORNavigation { get; set; }
        public virtual ICollection<APP_IFOOD_AUTORIZACAO> APP_IFOOD_AUTORIZACAO { get; set; }
        public virtual ICollection<CA_ABERTURA_FECHAMENTO> CA_ABERTURA_FECHAMENTOCOD_USUARIO_ABERTURANavigation { get; set; }
        public virtual ICollection<CA_ABERTURA_FECHAMENTO> CA_ABERTURA_FECHAMENTOCOD_USUARIO_FECHAMENTONavigation { get; set; }
        public virtual ICollection<CA_MOVIMENTOS> CA_MOVIMENTOS { get; set; }
        public virtual ICollection<CE_INVENTARIOS> CE_INVENTARIOSCOD_USUARIONavigation { get; set; }
        public virtual ICollection<CE_INVENTARIOS> CE_INVENTARIOSCOD_USUARIO_ENCERRAMENTONavigation { get; set; }
        public virtual ICollection<CE_INVENTARIOS_PRODUTOS_HISTORICOS> CE_INVENTARIOS_PRODUTOS_HISTORICOS { get; set; }
        public virtual ICollection<CE_INVENTARIO_SPED> CE_INVENTARIO_SPED { get; set; }
        public virtual ICollection<CE_MOVIMENTOS_ESTOQUES> CE_MOVIMENTOS_ESTOQUES { get; set; }
        public virtual ICollection<CE_NOTAS> CE_NOTAS { get; set; }
        public virtual ICollection<CE_NOTAS_XML> CE_NOTAS_XML { get; set; }
        public virtual ICollection<CE_PRODUTOS> CE_PRODUTOSCOD_USUARIO_ALTERACAONavigation { get; set; }
        public virtual ICollection<CE_PRODUTOS> CE_PRODUTOSCOD_USUARIO_CRIACAONavigation { get; set; }
        public virtual ICollection<CO_APROVADORES> CO_APROVADORES { get; set; }
        public virtual ICollection<CO_LOGS_STATUS_ORDENS> CO_LOGS_STATUS_ORDENS { get; set; }
        public virtual ICollection<CO_ORDENS> CO_ORDENS { get; set; }
        public virtual ICollection<CO_ORDENS_APROVADORES> CO_ORDENS_APROVADORES { get; set; }
        public virtual ICollection<CO_ORDENS_ITENS> CO_ORDENS_ITENS { get; set; }
        public virtual ICollection<CO_REGRAS_APROVADORES_USUARIOS> CO_REGRAS_APROVADORES_USUARIOS { get; set; }
        public virtual ICollection<CR_REMESSA_OPEN_BANK> CR_REMESSA_OPEN_BANK { get; set; }
        public virtual ICollection<FT_FATURA> FT_FATURA { get; set; }
        public virtual ICollection<FT_LIBERACAO_MARGEM_MINIMA> FT_LIBERACAO_MARGEM_MINIMA { get; set; }
        public virtual ICollection<FT_MDFE> FT_MDFE { get; set; }
        public virtual ICollection<FT_MDFE_EVENTOS> FT_MDFE_EVENTOS { get; set; }
        public virtual ICollection<FT_NOTAS> FT_NOTASCOD_USUARIO_CANCELAMENTONavigation { get; set; }
        public virtual ICollection<FT_NOTAS> FT_NOTASCOD_USUARIO_EMISSAONavigation { get; set; }
        public virtual ICollection<FT_NOTAS> FT_NOTASCOD_USUARIO_REGERAR_DANFENavigation { get; set; }
        public virtual ICollection<FT_NOTAS_CARTA_CORRECAO> FT_NOTAS_CARTA_CORRECAO { get; set; }
        public virtual ICollection<FT_NOTAS_INUTILIZADAS> FT_NOTAS_INUTILIZADAS { get; set; }
        public virtual ICollection<FT_NOTAS_XML> FT_NOTAS_XML { get; set; }
        public virtual ICollection<FT_PEDIDOS> FT_PEDIDOSCOD_USUARIO_APROVACAONavigation { get; set; }
        public virtual ICollection<FT_PEDIDOS> FT_PEDIDOSCOD_USUARIO_EMISSAONavigation { get; set; }
        public virtual ICollection<FT_PEDIDOS_HISTORICOS> FT_PEDIDOS_HISTORICOS { get; set; }
        public virtual ICollection<GE_ADMINISTRADORES_ORGANIZACAO> GE_ADMINISTRADORES_ORGANIZACAO { get; set; }
        public virtual ICollection<GE_ALERTAS> GE_ALERTAS { get; set; }
        public virtual ICollection<GE_ALERTAS_PROCESSOS> GE_ALERTAS_PROCESSOS { get; set; }
        public virtual ICollection<GE_ALERTAS_USUARIO> GE_ALERTAS_USUARIO { get; set; }
        public virtual ICollection<GE_ANEXOS> GE_ANEXOS { get; set; }
        public virtual ICollection<GE_ANOTACOES> GE_ANOTACOES { get; set; }
        public virtual ICollection<GE_ANOTACOES_ANEXO> GE_ANOTACOES_ANEXO { get; set; }
        public virtual ICollection<GE_ANOTACOES_USUARIO> GE_ANOTACOES_USUARIO { get; set; }
        public virtual ICollection<GE_CADASTRO_FRENTE_CAIXA> GE_CADASTRO_FRENTE_CAIXACOD_USUARIONavigation { get; set; }
        public virtual ICollection<GE_CADASTRO_FRENTE_CAIXA> GE_CADASTRO_FRENTE_CAIXACOD_USUARIO_DESATIVACAONavigation { get; set; }
        public virtual ICollection<GE_CHAT> GE_CHATCOD_USUARIO_DESTINATARIONavigation { get; set; }
        public virtual ICollection<GE_CHAT> GE_CHATCOD_USUARIO_REMETENTENavigation { get; set; }
        public virtual ICollection<GE_CLASSIFICACAO_COMPONENTES_DASHBOARD> GE_CLASSIFICACAO_COMPONENTES_DASHBOARD { get; set; }
        public virtual ICollection<GE_COLABORACAO> GE_COLABORACAO { get; set; }
        public virtual ICollection<GE_COLABORACAO_CURTIDAS> GE_COLABORACAO_CURTIDAS { get; set; }
        public virtual ICollection<GE_COLABORACAO_DESTINATARIO> GE_COLABORACAO_DESTINATARIO { get; set; }
        public virtual ICollection<GE_COMENTARIOS> GE_COMENTARIOS { get; set; }
        public virtual ICollection<GE_COMPARTILHAMENTOS> GE_COMPARTILHAMENTOSCOD_USUARIO_DESCARTENavigation { get; set; }
        public virtual ICollection<GE_COMPARTILHAMENTOS> GE_COMPARTILHAMENTOSCOD_USUARIO_IMPORTACAONavigation { get; set; }
        public virtual ICollection<GE_COMPONENTES_DASHBOARD> GE_COMPONENTES_DASHBOARD { get; set; }
        public virtual ICollection<GE_COMPONENTES_PERMISSOES> GE_COMPONENTES_PERMISSOES { get; set; }
        public virtual ICollection<GE_CONFIG_INTEGRACAO_BIMACHINE> GE_CONFIG_INTEGRACAO_BIMACHINE { get; set; }
        public virtual ICollection<GE_CONSULTAS> GE_CONSULTAS { get; set; }
        public virtual ICollection<GE_CONSULTAS_CONFIGURADAS> GE_CONSULTAS_CONFIGURADASCOD_USUARIONavigation { get; set; }
        public virtual ICollection<GE_CONSULTAS_CONFIGURADAS> GE_CONSULTAS_CONFIGURADASCOD_USUARIO_ALTERACAONavigation { get; set; }
        public virtual ICollection<GE_DASHBOARD> GE_DASHBOARD { get; set; }
        public virtual ICollection<GE_EMAILS_ENVIADOS> GE_EMAILS_ENVIADOS { get; set; }
        public virtual ICollection<GE_EMAILS_SPED_FISCAL> GE_EMAILS_SPED_FISCAL { get; set; }
        public virtual ICollection<GE_ETIQUETAS> GE_ETIQUETAS { get; set; }
        public virtual ICollection<GE_FAVORITOS> GE_FAVORITOS { get; set; }
        public virtual ICollection<GE_FILA_SPED_FISCAL> GE_FILA_SPED_FISCAL { get; set; }
        public virtual ICollection<GE_GESTAO_COMPARTILHAMENTOS> GE_GESTAO_COMPARTILHAMENTOS { get; set; }
        public virtual ICollection<GE_GESTAO_COMPARTILHAMENTOS_PROCESSOS_PERMISSOES> GE_GESTAO_COMPARTILHAMENTOS_PROCESSOS_PERMISSOES { get; set; }
        public virtual ICollection<GE_INTREGRACAO_WHATSAPP> GE_INTREGRACAO_WHATSAPP { get; set; }
        public virtual ICollection<GE_LISTA_PRECOS> GE_LISTA_PRECOS { get; set; }
        public virtual ICollection<GE_LISTA_PRECOS_PRODUTOS> GE_LISTA_PRECOS_PRODUTOS { get; set; }
        public virtual ICollection<GE_LOGS_COMPARTILHAMENTOS> GE_LOGS_COMPARTILHAMENTOS { get; set; }
        public virtual ICollection<GE_OPERACAO_FISCAL> GE_OPERACAO_FISCALCOD_USUARIO_ATIVACAONavigation { get; set; }
        public virtual ICollection<GE_OPERACAO_FISCAL> GE_OPERACAO_FISCALCOD_USUARIO_BLOQUEIONavigation { get; set; }
        public virtual ICollection<GE_OPERACAO_FISCAL> GE_OPERACAO_FISCALCOD_USUARIO_DESBLOQUEIONavigation { get; set; }
        public virtual ICollection<GE_OPERACAO_FISCAL> GE_OPERACAO_FISCALCOD_USUARIO_INATIVACAONavigation { get; set; }
        public virtual ICollection<GE_PROMOCOES> GE_PROMOCOES { get; set; }
        public virtual ICollection<GE_USUARIOS_COMPARTILHADOS> GE_USUARIOS_COMPARTILHADOS { get; set; }
        public virtual ICollection<GE_USUARIOS> InverseCOD_SUPERIORNavigation { get; set; }
        public virtual ICollection<OS_ORDEM> OS_ORDEM { get; set; }
        public virtual ICollection<PS_CONTRATOS_REAJUSTES> PS_CONTRATOS_REAJUSTES { get; set; }
        public virtual ICollection<PS_REPRESENTANTES> PS_REPRESENTANTES { get; set; }
        public virtual ICollection<SW_ERROS_APLICACAO> SW_ERROS_APLICACAO { get; set; }
        public virtual ICollection<SW_LOG_ACESSO_TELA> SW_LOG_ACESSO_TELA { get; set; }
        public virtual ICollection<SW_LOG_ATRIBUTOS> SW_LOG_ATRIBUTOS { get; set; }
        public virtual ICollection<SW_LOG_REGISTROS> SW_LOG_REGISTROS { get; set; }
        public virtual ICollection<SW_USUARIOS_LOGADOS> SW_USUARIOS_LOGADOS { get; set; }

        public virtual ICollection<GE_EMPRESAS> COD_EMPRESA1 { get; set; }
        public virtual ICollection<GE_HABILIDADES> COD_HABILIDADE { get; set; }
        public virtual ICollection<GE_PAPEL> COD_PAPEL { get; set; }
        public virtual ICollection<GE_POSICAO> COD_POSICAO { get; set; }
    }
}