// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class GE_USUARIOS_COMPARTILHADOS
    {
        public int COD_INSTANCIA { get; set; }
        public int COD_USUARIO { get; set; }
        public bool? TIP_PERMITE_EDITAR { get; set; }
        public bool? TIP_PERMITE_VISUALIZAR { get; set; }
        public int? COD_ORGANIZACAO { get; set; }

        public virtual GE_ORGANIZACAO? COD_ORGANIZACAONavigation { get; set; }
        public virtual GE_USUARIOS COD_USUARIONavigation { get; set; } = null!;
    }
}