// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class OS_STATUS_ORDEM
    {
        public OS_STATUS_ORDEM()
        {
            OS_ORDEM = new HashSet<OS_ORDEM>();
            OS_PARAMETROSCOD_STATUS_APROVACAONavigation = new HashSet<OS_PARAMETROS>();
            OS_PARAMETROSCOD_STATUS_FATURADO_PARCIALNavigation = new HashSet<OS_PARAMETROS>();
            OS_PARAMETROSCOD_STATUS_FATURADO_TOTALNavigation = new HashSet<OS_PARAMETROS>();
            OS_PARAMETROSCOD_STATUS_INICIALNavigation = new HashSet<OS_PARAMETROS>();
            OS_PARAMETROSCOD_STATUS_REPROVACAONavigation = new HashSet<OS_PARAMETROS>();
        }

        public int COD_STATUS { get; set; }
        public string? DES_STATUS { get; set; }
        public string? COD_COR { get; set; }
        public int COD_EMPRESA { get; set; }

        public virtual GE_EMPRESAS_PADRAO COD_EMPRESANavigation { get; set; } = null!;
        public virtual ICollection<OS_ORDEM> OS_ORDEM { get; set; }
        public virtual ICollection<OS_PARAMETROS> OS_PARAMETROSCOD_STATUS_APROVACAONavigation { get; set; }
        public virtual ICollection<OS_PARAMETROS> OS_PARAMETROSCOD_STATUS_FATURADO_PARCIALNavigation { get; set; }
        public virtual ICollection<OS_PARAMETROS> OS_PARAMETROSCOD_STATUS_FATURADO_TOTALNavigation { get; set; }
        public virtual ICollection<OS_PARAMETROS> OS_PARAMETROSCOD_STATUS_INICIALNavigation { get; set; }
        public virtual ICollection<OS_PARAMETROS> OS_PARAMETROSCOD_STATUS_REPROVACAONavigation { get; set; }
    }
}