// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class OS_TIPOS_ORDEM
    {
        public OS_TIPOS_ORDEM()
        {
            OS_ORDEM = new HashSet<OS_ORDEM>();
        }

        public int COD_TIPO { get; set; }
        public string? DES_TIPO { get; set; }
        public int COD_EMPRESA { get; set; }

        public virtual GE_EMPRESAS_PADRAO COD_EMPRESANavigation { get; set; } = null!;
        public virtual ICollection<OS_ORDEM> OS_ORDEM { get; set; }
    }
}