// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class OS_TECNICOS
    {
        public OS_TECNICOS()
        {
            OS_ORDEM_SERVICO = new HashSet<OS_ORDEM_SERVICO>();
        }

        public int COD_TECNICO { get; set; }
        public string? DES_TECNICO { get; set; }
        public int COD_EMPRESA { get; set; }

        public virtual GE_EMPRESAS_PADRAO COD_EMPRESANavigation { get; set; } = null!;
        public virtual ICollection<OS_ORDEM_SERVICO> OS_ORDEM_SERVICO { get; set; }
    }
}