// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class PS_CONTATOS_PROCESSOS
    {
        public int COD_CONTATO_PROCESSO { get; set; }
        public int COD_CONTATO { get; set; }
        public int COD_PROCESSO { get; set; }
        public int? COD_ORGANIZACAO { get; set; }

        public virtual PS_CONTATOS COD_CONTATONavigation { get; set; } = null!;
        public virtual GE_ORGANIZACAO? COD_ORGANIZACAONavigation { get; set; }
        public virtual SW_PROCESSOS COD_PROCESSONavigation { get; set; } = null!;
    }
}