// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class PS_CANAL_VENDAS
    {
        public PS_CANAL_VENDAS()
        {
            FT_NOTAS = new HashSet<FT_NOTAS>();
            FT_PARAMETROS = new HashSet<FT_PARAMETROS>();
            FT_PEDIDOS = new HashSet<FT_PEDIDOS>();
            GE_CONFIG_INTEGRACAO_ISET = new HashSet<GE_CONFIG_INTEGRACAO_ISET>();
            GE_CONFIG_INTEGRACAO_TRAY = new HashSet<GE_CONFIG_INTEGRACAO_TRAY>();
            PS_CLIENTES = new HashSet<PS_CLIENTES>();
        }

        public int COD_CANAL { get; set; }
        public string? DES_CANAL { get; set; }
        public int COD_EMPRESA { get; set; }

        public virtual GE_EMPRESAS COD_EMPRESANavigation { get; set; } = null!;
        public virtual ICollection<FT_NOTAS> FT_NOTAS { get; set; }
        public virtual ICollection<FT_PARAMETROS> FT_PARAMETROS { get; set; }
        public virtual ICollection<FT_PEDIDOS> FT_PEDIDOS { get; set; }
        public virtual ICollection<GE_CONFIG_INTEGRACAO_ISET> GE_CONFIG_INTEGRACAO_ISET { get; set; }
        public virtual ICollection<GE_CONFIG_INTEGRACAO_TRAY> GE_CONFIG_INTEGRACAO_TRAY { get; set; }
        public virtual ICollection<PS_CLIENTES> PS_CLIENTES { get; set; }
    }
}