// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class PS_CONTRATOS_REAJUSTES
    {
        public int COD_CONTRATO_REAJUSTE { get; set; }
        public int COD_CONTRATO_ITENS { get; set; }
        public int COD_PRODUTO { get; set; }
        public decimal? VLR_CONTRATO_ANTERIOR { get; set; }
        public decimal? VLR_CONTRATO_ATUAL { get; set; }
        public int? IND_TIPO_CONTRATO { get; set; }
        public bool? TIP_EXCLUIDO { get; set; }
        public decimal? PER_REAJUSTE { get; set; }
        public DateTime? DTA_REAJUSTE { get; set; }
        public int? COD_USUARIO { get; set; }
        public int? COD_EMPRESA { get; set; }
        public int? COD_ORGANIZACAO { get; set; }
        public int NUM_REAJUSTE { get; set; }
        public DateTime? DTA_REALIZADO { get; set; }

        public virtual PS_CONTRATOS_ITENS COD_CONTRATO_ITENSNavigation { get; set; } = null!;
        public virtual GE_EMPRESAS? COD_EMPRESANavigation { get; set; }
        public virtual GE_ORGANIZACAO? COD_ORGANIZACAONavigation { get; set; }
        public virtual CE_PRODUTOS COD_PRODUTONavigation { get; set; } = null!;
        public virtual GE_USUARIOS? COD_USUARIONavigation { get; set; }
    }
}