// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class PS_CONTATOS_PROCESSOS_CONECTADO
    {
        public int COD_CONTATO_PROCESSO_CONECTADO { get; set; }
        public int COD_CONTATO { get; set; }
        public int? COD_MODELO_PROCESSO { get; set; }

        public virtual PS_CONTATOS COD_CONTATONavigation { get; set; } = null!;
    }
}