// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class PS_CLIENTES_VENCIMENTOS
    {
        public int COD_SEQUENCIA { get; set; }
        public int? COD_EMPRESA { get; set; }
        public int COD_PESSOA { get; set; }
        public int? NUM_DIA_INICIAL { get; set; }
        public int? NUM_DIA_FINAL { get; set; }
        public int? NUM_DIA_VENCIMENTO { get; set; }
        public int? IND_DIA_SEMANA { get; set; }

        public virtual GE_EMPRESAS? COD_EMPRESANavigation { get; set; }
        public virtual PS_PESSOAS COD_PESSOANavigation { get; set; } = null!;
    }
}