// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class PS_CONTRATOS
    {
        public PS_CONTRATOS()
        {
            FT_FATURAS_NAO_GERADAS = new HashSet<FT_FATURAS_NAO_GERADAS>();
            PS_CONTRATOS_ITENS = new HashSet<PS_CONTRATOS_ITENS>();
        }

        public int COD_CONTRATO { get; set; }
        public int COD_PESSOA { get; set; }
        public string NUM_CONTRATO { get; set; } = null!;
        public DateTime? DTA_CONTRATO { get; set; }
        public DateTime DTA_VIGENCIA_INICIAL { get; set; }
        public DateTime? DTA_VIGENCIA_FINAL { get; set; }
        public int NUM_DIA_EMISSAO { get; set; }
        public int NUM_DIA_VENCIMENTO { get; set; }
        public int? IND_REGRA_VENCIMENTO { get; set; }
        public int IND_RECORRENCIA { get; set; }
        public int NUM_MES_REAJUSTE { get; set; }
        public int? COD_INDICE { get; set; }
        public string? DES_OBSERVACAO { get; set; }
        public int? COD_TIPO_PAGAMENTO { get; set; }
        public int COD_EMPRESA { get; set; }
        public int COD_ORGANIZACAO { get; set; }
        public bool? TIP_GERAR_NFSE { get; set; }
        public int? QTD_FRANQUIA { get; set; }
        public int? IND_TIPO_FRANQUIA { get; set; }
        public decimal? VLR_CONTRATO { get; set; }
        public DateTime? DTA_ALTERACAO { get; set; }
        public DateTime? DTA_PROXIMA_FATURA_INICIAL { get; set; }
        public DateTime? DTA_PROXIMA_FATURA_FINAL { get; set; }
        public int IND_RECORRENCIA_FRANQUIA { get; set; }
        public DateTime? DTA_ULTIMA_FATURA { get; set; }
        public int? COD_CONVENIO_BANCARIO { get; set; }
        public int? COD_PRODUTO_NOTA_FISCAL { get; set; }
        public int? IND_FIXADO { get; set; }

        public virtual GE_EMPRESAS COD_EMPRESANavigation { get; set; } = null!;
        public virtual GE_INDICES? COD_INDICENavigation { get; set; }
        public virtual GE_ORGANIZACAO COD_ORGANIZACAONavigation { get; set; } = null!;
        public virtual PS_PESSOAS COD_PESSOANavigation { get; set; } = null!;
        public virtual CE_PRODUTOS? COD_PRODUTO_NOTA_FISCALNavigation { get; set; }
        public virtual GE_TIPO_PAGAMENTO? COD_TIPO_PAGAMENTONavigation { get; set; }
        public virtual ICollection<FT_FATURAS_NAO_GERADAS> FT_FATURAS_NAO_GERADAS { get; set; }
        public virtual ICollection<PS_CONTRATOS_ITENS> PS_CONTRATOS_ITENS { get; set; }
    }
}