// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class PS_CONTRATOS_ITENS
    {
        public PS_CONTRATOS_ITENS()
        {
            FT_FATURA_ITENS = new HashSet<FT_FATURA_ITENS>();
            PS_CONTRATOS_REAJUSTES = new HashSet<PS_CONTRATOS_REAJUSTES>();
        }

        public int COD_CONTRATO_ITENS { get; set; }
        public int COD_CONTRATO { get; set; }
        public int COD_PRODUTO { get; set; }
        public decimal? VLR_CONTRATO { get; set; }
        public int? IND_TIPO_CONTRATO { get; set; }
        public int COD_EMPRESA { get; set; }
        public int COD_ORGANIZACAO { get; set; }
        public int? QTD_FRANQUIA { get; set; }
        public string? DES_SERVICO_NOTA { get; set; }

        public virtual PS_CONTRATOS COD_CONTRATONavigation { get; set; } = null!;
        public virtual GE_EMPRESAS COD_EMPRESANavigation { get; set; } = null!;
        public virtual GE_ORGANIZACAO COD_ORGANIZACAONavigation { get; set; } = null!;
        public virtual CE_PRODUTOS COD_PRODUTONavigation { get; set; } = null!;
        public virtual ICollection<FT_FATURA_ITENS> FT_FATURA_ITENS { get; set; }
        public virtual ICollection<PS_CONTRATOS_REAJUSTES> PS_CONTRATOS_REAJUSTES { get; set; }
    }
}