// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class PS_ENDERECOS
    {
        public int COD_ENDERECO { get; set; }
        public int COD_PESSOA { get; set; }
        public int? COD_TIPO_ENDERECO { get; set; }
        public string? DES_ENDERECO { get; set; }
        public int? NUM_ENDERECO { get; set; }
        public string? DES_COMPLEMENTO { get; set; }
        public string? DES_BAIRRO { get; set; }
        public string? COD_CEP { get; set; }
        public string? NUM_CAIXAPOSTAL { get; set; }
        public bool? TIP_PRINCIPAL { get; set; }
        public bool? TIP_ENTREGA { get; set; }
        public bool? TIP_COBRANCA { get; set; }
        public decimal? NUM_LATITUDE { get; set; }
        public decimal? NUM_LONGITUDE { get; set; }
        public string? DES_PONTO_REFERENCIA { get; set; }
        public int? COD_ORGANIZACAO { get; set; }
        public int? COD_CIDADE { get; set; }
        public int? COD_PAIS { get; set; }
        public bool? TIP_USAR_ENDERECO_ENTREGA_NOTA_PEDIDO { get; set; }

        public virtual GE_CIDADES? COD_CIDADENavigation { get; set; }
        public virtual GE_ORGANIZACAO? COD_ORGANIZACAONavigation { get; set; }
        public virtual SW_PAISES? COD_PAISNavigation { get; set; }
        public virtual PS_PESSOAS COD_PESSOANavigation { get; set; } = null!;
        public virtual GE_TIPO_ENDERECO? COD_TIPO_ENDERECONavigation { get; set; }
    }
}