// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class PS_FISICAS
    {
        public int COD_PESSOA { get; set; }
        public string? NUM_RG { get; set; }
        public DateTime? DTA_NASCIMENTO { get; set; }
        public int? COD_ORGANIZACAO { get; set; }

        public virtual GE_ORGANIZACAO? COD_ORGANIZACAONavigation { get; set; }
        public virtual PS_PESSOAS COD_PESSOANavigation { get; set; } = null!;
    }
}