// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class PS_LANCAMENTOS_ITENS
    {
        public int COD_LANCAMENTO_ITEM { get; set; }
        public int COD_LANCAMENTO { get; set; }
        public int? HMS_LANCAMENTO { get; set; }
        public string? DES_OBSERVACAO { get; set; }
        public int COD_EMPRESA { get; set; }
        public int COD_ORGANIZACAO { get; set; }
        public bool? TIP_RESOLUTIVA { get; set; }

        public virtual GE_EMPRESAS COD_EMPRESANavigation { get; set; } = null!;
        public virtual PS_LANCAMENTOS COD_LANCAMENTONavigation { get; set; } = null!;
        public virtual GE_ORGANIZACAO COD_ORGANIZACAONavigation { get; set; } = null!;
    }
}