// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class PS_PESSOAS
    {
        public PS_PESSOAS()
        {
            CE_INVENTARIO_SPED_ITENS = new HashSet<CE_INVENTARIO_SPED_ITENS>();
            CE_MOVIMENTOS_ESTOQUES = new HashSet<CE_MOVIMENTOS_ESTOQUES>();
            CE_NOTASCOD_FORNECEDOR_TRIANGULARNavigation = new HashSet<CE_NOTAS>();
            CE_NOTASCOD_PESSOANavigation = new HashSet<CE_NOTAS>();
            CE_NOTASCOD_TRANSPORTADORANavigation = new HashSet<CE_NOTAS>();
            CE_PRODUTOS_FORNECEDORES = new HashSet<CE_PRODUTOS_FORNECEDORES>();
            CE_PRODUTO_CONVERSAO_UNIDADES = new HashSet<CE_PRODUTO_CONVERSAO_UNIDADES>();
            CO_ORDENSCOD_PESSOANavigation = new HashSet<CO_ORDENS>();
            CO_ORDENSCOD_TRANSPORTADORANavigation = new HashSet<CO_ORDENS>();
            CP_PARAMETROS = new HashSet<CP_PARAMETROS>();
            CP_TITULOS = new HashSet<CP_TITULOS>();
            CR_TITULOS = new HashSet<CR_TITULOS>();
            CR_TITULOS_COMISSOES = new HashSet<CR_TITULOS_COMISSOES>();
            FT_FATURA = new HashSet<FT_FATURA>();
            FT_NOTASCOD_PESSOANavigation = new HashSet<FT_NOTAS>();
            FT_NOTASCOD_TRANSPORTADORANavigation = new HashSet<FT_NOTAS>();
            FT_NOTASCOD_TRANSPORTADORA_REDESPACHONavigation = new HashSet<FT_NOTAS>();
            FT_NOTAS_ITENS_COMISSAO = new HashSet<FT_NOTAS_ITENS_COMISSAO>();
            FT_NOTAS_REPRESENTANTES = new HashSet<FT_NOTAS_REPRESENTANTES>();
            FT_PARAMETROS = new HashSet<FT_PARAMETROS>();
            FT_PARAMETROS_FORNECEDORES_MANIFESTO = new HashSet<FT_PARAMETROS_FORNECEDORES_MANIFESTO>();
            FT_PEDIDOSCOD_PESSOANavigation = new HashSet<FT_PEDIDOS>();
            FT_PEDIDOSCOD_TRANSPORTADORANavigation = new HashSet<FT_PEDIDOS>();
            FT_PEDIDOSCOD_TRANSPORTADORA_REDESPACHONavigation = new HashSet<FT_PEDIDOS>();
            FT_PEDIDOS_ITENS_COMISSAO = new HashSet<FT_PEDIDOS_ITENS_COMISSAO>();
            FT_PEDIDOS_REPRESENTANTES = new HashSet<FT_PEDIDOS_REPRESENTANTES>();
            GE_ALERTAS_PROCESSOS_PESSOAS = new HashSet<GE_ALERTAS_PROCESSOS_PESSOAS>();
            GE_CONFIG_INTEGRACAO_ISET = new HashSet<GE_CONFIG_INTEGRACAO_ISET>();
            GE_CONFIG_INTEGRACAO_TRAY = new HashSet<GE_CONFIG_INTEGRACAO_TRAY>();
            GE_INTERMEDIADOR = new HashSet<GE_INTERMEDIADOR>();
            GE_PARAMETROS_SPED = new HashSet<GE_PARAMETROS_SPED>();
            GE_REGRAS_TRIBUTACAO = new HashSet<GE_REGRAS_TRIBUTACAO>();
            GE_RELACOES_LISTAS_PRECOSCOD_CLIENTENavigation = new HashSet<GE_RELACOES_LISTAS_PRECOS>();
            GE_RELACOES_LISTAS_PRECOSCOD_REPRESENTENTENavigation = new HashSet<GE_RELACOES_LISTAS_PRECOS>();
            OS_ORDEM = new HashSet<OS_ORDEM>();
            PS_CLIENTESCOD_PESSOA_RELACIONADANavigation = new HashSet<PS_CLIENTES>();
            PS_CLIENTESCOD_REPRESENTANTENavigation = new HashSet<PS_CLIENTES>();
            PS_CLIENTESCOD_TRANSPORTADORANavigation = new HashSet<PS_CLIENTES>();
            PS_CLIENTES_VENCIMENTOS = new HashSet<PS_CLIENTES_VENCIMENTOS>();
            PS_CONTATOS = new HashSet<PS_CONTATOS>();
            PS_CONTRATOS = new HashSet<PS_CONTRATOS>();
            PS_ENDERECOS = new HashSet<PS_ENDERECOS>();
            PS_LANCAMENTOS = new HashSet<PS_LANCAMENTOS>();
            PS_TELEFONES_PESSOAS = new HashSet<PS_TELEFONES_PESSOAS>();
        }

        public int COD_PESSOA { get; set; }
        public int COD_EMPRESA { get; set; }
        public string? DES_PESSOA { get; set; }
        public string? DES_RAZAO_SOCIAL { get; set; }
        public int? IND_TIPO_PESSOA { get; set; }
        public string? NUM_CPF_CNPJ { get; set; }
        public string? NUM_IE { get; set; }
        public string? DES_EMAIL { get; set; }
        public DateTime? DTA_CADASTRO { get; set; }
        public DateTime? DTA_DESATIVACAO { get; set; }
        public string? TXT_OBSERVACAO { get; set; }
        public string? NUM_INSCRICAO_MUNICIPAL { get; set; }
        public bool? TIP_CLIENTE { get; set; }
        public bool? TIP_REPRESENTANTE { get; set; }
        public int? COD_ORGANIZACAO { get; set; }
        public bool? TIP_FORNECEDOR { get; set; }
        public bool? TIP_AGRUPA_FATURA_CONTRATO { get; set; }
        public DateTime? DTA_ALTERACAO { get; set; }
        public int? COD_TIPO_PAGAMENTO { get; set; }
        public int? COD_BANCO { get; set; }
        public bool? TIP_TRANSPORTADORA { get; set; }
        public int? IND_CONTRIBUINTE { get; set; }
        public string? COD_APLICACAO_EXTERNA { get; set; }
        public decimal? PER_COMISSAO { get; set; }
        public int? COD_CENTRO_CUSTO { get; set; }
        public int? COD_CONTA_CONTABIL_FORNECEDOR { get; set; }
        public string? DES_GUID { get; set; }
        public int? COD_EMPRESA_ORIGEM { get; set; }
        public int? COD_RAMO_ATIVIDADE { get; set; }
        public string? NUM_CONSELHO_REG_CONTAB { get; set; }
        public string? NUM_CNPJ_CONTABIL { get; set; }
        public int? COD_TIPO_TITULO { get; set; }

        public virtual GE_BANCOS? COD_BANCONavigation { get; set; }
        public virtual GE_CENTRO_CUSTOS? COD_CENTRO_CUSTONavigation { get; set; }
        public virtual GE_CONTAS_CONTABEIS? COD_CONTA_CONTABIL_FORNECEDORNavigation { get; set; }
        public virtual GE_EMPRESAS COD_EMPRESANavigation { get; set; } = null!;
        public virtual GE_EMPRESAS? COD_EMPRESA_ORIGEMNavigation { get; set; }
        public virtual GE_ORGANIZACAO? COD_ORGANIZACAONavigation { get; set; }
        public virtual PS_RAMOS_ATIVIDADES? COD_RAMO_ATIVIDADENavigation { get; set; }
        public virtual GE_TIPO_TITULO? COD_TIPO_TITULONavigation { get; set; }
        public virtual PS_CLIENTES? PS_CLIENTESCOD_PESSOANavigation { get; set; }
        public virtual PS_FISICAS? PS_FISICAS { get; set; }
        public virtual PS_REPRESENTANTES? PS_REPRESENTANTES { get; set; }
        public virtual ICollection<CE_INVENTARIO_SPED_ITENS> CE_INVENTARIO_SPED_ITENS { get; set; }
        public virtual ICollection<CE_MOVIMENTOS_ESTOQUES> CE_MOVIMENTOS_ESTOQUES { get; set; }
        public virtual ICollection<CE_NOTAS> CE_NOTASCOD_FORNECEDOR_TRIANGULARNavigation { get; set; }
        public virtual ICollection<CE_NOTAS> CE_NOTASCOD_PESSOANavigation { get; set; }
        public virtual ICollection<CE_NOTAS> CE_NOTASCOD_TRANSPORTADORANavigation { get; set; }
        public virtual ICollection<CE_PRODUTOS_FORNECEDORES> CE_PRODUTOS_FORNECEDORES { get; set; }
        public virtual ICollection<CE_PRODUTO_CONVERSAO_UNIDADES> CE_PRODUTO_CONVERSAO_UNIDADES { get; set; }
        public virtual ICollection<CO_ORDENS> CO_ORDENSCOD_PESSOANavigation { get; set; }
        public virtual ICollection<CO_ORDENS> CO_ORDENSCOD_TRANSPORTADORANavigation { get; set; }
        public virtual ICollection<CP_PARAMETROS> CP_PARAMETROS { get; set; }
        public virtual ICollection<CP_TITULOS> CP_TITULOS { get; set; }
        public virtual ICollection<CR_TITULOS> CR_TITULOS { get; set; }
        public virtual ICollection<CR_TITULOS_COMISSOES> CR_TITULOS_COMISSOES { get; set; }
        public virtual ICollection<FT_FATURA> FT_FATURA { get; set; }
        public virtual ICollection<FT_NOTAS> FT_NOTASCOD_PESSOANavigation { get; set; }
        public virtual ICollection<FT_NOTAS> FT_NOTASCOD_TRANSPORTADORANavigation { get; set; }
        public virtual ICollection<FT_NOTAS> FT_NOTASCOD_TRANSPORTADORA_REDESPACHONavigation { get; set; }
        public virtual ICollection<FT_NOTAS_ITENS_COMISSAO> FT_NOTAS_ITENS_COMISSAO { get; set; }
        public virtual ICollection<FT_NOTAS_REPRESENTANTES> FT_NOTAS_REPRESENTANTES { get; set; }
        public virtual ICollection<FT_PARAMETROS> FT_PARAMETROS { get; set; }
        public virtual ICollection<FT_PARAMETROS_FORNECEDORES_MANIFESTO> FT_PARAMETROS_FORNECEDORES_MANIFESTO { get; set; }
        public virtual ICollection<FT_PEDIDOS> FT_PEDIDOSCOD_PESSOANavigation { get; set; }
        public virtual ICollection<FT_PEDIDOS> FT_PEDIDOSCOD_TRANSPORTADORANavigation { get; set; }
        public virtual ICollection<FT_PEDIDOS> FT_PEDIDOSCOD_TRANSPORTADORA_REDESPACHONavigation { get; set; }
        public virtual ICollection<FT_PEDIDOS_ITENS_COMISSAO> FT_PEDIDOS_ITENS_COMISSAO { get; set; }
        public virtual ICollection<FT_PEDIDOS_REPRESENTANTES> FT_PEDIDOS_REPRESENTANTES { get; set; }
        public virtual ICollection<GE_ALERTAS_PROCESSOS_PESSOAS> GE_ALERTAS_PROCESSOS_PESSOAS { get; set; }
        public virtual ICollection<GE_CONFIG_INTEGRACAO_ISET> GE_CONFIG_INTEGRACAO_ISET { get; set; }
        public virtual ICollection<GE_CONFIG_INTEGRACAO_TRAY> GE_CONFIG_INTEGRACAO_TRAY { get; set; }
        public virtual ICollection<GE_INTERMEDIADOR> GE_INTERMEDIADOR { get; set; }
        public virtual ICollection<GE_PARAMETROS_SPED> GE_PARAMETROS_SPED { get; set; }
        public virtual ICollection<GE_REGRAS_TRIBUTACAO> GE_REGRAS_TRIBUTACAO { get; set; }
        public virtual ICollection<GE_RELACOES_LISTAS_PRECOS> GE_RELACOES_LISTAS_PRECOSCOD_CLIENTENavigation { get; set; }
        public virtual ICollection<GE_RELACOES_LISTAS_PRECOS> GE_RELACOES_LISTAS_PRECOSCOD_REPRESENTENTENavigation { get; set; }
        public virtual ICollection<OS_ORDEM> OS_ORDEM { get; set; }
        public virtual ICollection<PS_CLIENTES> PS_CLIENTESCOD_PESSOA_RELACIONADANavigation { get; set; }
        public virtual ICollection<PS_CLIENTES> PS_CLIENTESCOD_REPRESENTANTENavigation { get; set; }
        public virtual ICollection<PS_CLIENTES> PS_CLIENTESCOD_TRANSPORTADORANavigation { get; set; }
        public virtual ICollection<PS_CLIENTES_VENCIMENTOS> PS_CLIENTES_VENCIMENTOS { get; set; }
        public virtual ICollection<PS_CONTATOS> PS_CONTATOS { get; set; }
        public virtual ICollection<PS_CONTRATOS> PS_CONTRATOS { get; set; }
        public virtual ICollection<PS_ENDERECOS> PS_ENDERECOS { get; set; }
        public virtual ICollection<PS_LANCAMENTOS> PS_LANCAMENTOS { get; set; }
        public virtual ICollection<PS_TELEFONES_PESSOAS> PS_TELEFONES_PESSOAS { get; set; }
    }
}