// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class PS_REPRESENTANTES
    {
        public int COD_PESSOA { get; set; }
        public decimal? PER_COMISSAO { get; set; }
        public int? NUM_MATRICULA { get; set; }
        public int? COD_USUARIO { get; set; }
        public int? COD_GRUPO { get; set; }
        public int? IND_PAGAMENTO { get; set; }

        public virtual PS_PESSOAS COD_PESSOANavigation { get; set; } = null!;
        public virtual GE_USUARIOS? COD_USUARIONavigation { get; set; }
    }
}