// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class PS_RAMOS_ATIVIDADES
    {
        public PS_RAMOS_ATIVIDADES()
        {
            PS_PESSOAS = new HashSet<PS_PESSOAS>();
        }

        public int COD_RAMO { get; set; }
        public string? DES_RAMO { get; set; }
        public int COD_EMPRESA { get; set; }

        public virtual GE_EMPRESAS COD_EMPRESANavigation { get; set; } = null!;
        public virtual ICollection<PS_PESSOAS> PS_PESSOAS { get; set; }
    }
}