// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class PS_TELEFONES_PESSOAS
    {
        public int CD_TELEFONE_PESSOA { get; set; }
        public int COD_TELEFONE { get; set; }
        public int COD_PESSOA { get; set; }

        public virtual PS_PESSOAS COD_PESSOANavigation { get; set; } = null!;
        public virtual PS_TELEFONES COD_TELEFONENavigation { get; set; } = null!;
    }
}