// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class PS_TELEFONES_CONTATOS
    {
        public int COD_TELEFONE_CONTATO { get; set; }
        public int COD_TELEFONE { get; set; }
        public int COD_CONTATO { get; set; }

        public virtual PS_CONTATOS COD_CONTATONavigation { get; set; } = null!;
        public virtual PS_TELEFONES COD_TELEFONENavigation { get; set; } = null!;
    }
}