// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class SW_BANCOS_HOMOLOGADOS
    {
        public SW_BANCOS_HOMOLOGADOS()
        {
            CR_CONTAS_BANCARIAS = new HashSet<CR_CONTAS_BANCARIAS>();
            GE_BANCOS = new HashSet<GE_BANCOS>();
            SW_INTEGRADORES_BANCARIOS_BANCOS_HOMOLOGADOS = new HashSet<SW_INTEGRADORES_BANCARIOS_BANCOS_HOMOLOGADOS>();
            SW_OCORRENCIAS_BANCARIAS = new HashSet<SW_OCORRENCIAS_BANCARIAS>();
        }

        public int COD_BANCO_HOMOLOGADO { get; set; }
        public string DES_BANCO_HOMOLOGADO { get; set; } = null!;
        public string NUM_BANCO { get; set; } = null!;

        public virtual ICollection<CR_CONTAS_BANCARIAS> CR_CONTAS_BANCARIAS { get; set; }
        public virtual ICollection<GE_BANCOS> GE_BANCOS { get; set; }
        public virtual ICollection<SW_INTEGRADORES_BANCARIOS_BANCOS_HOMOLOGADOS> SW_INTEGRADORES_BANCARIOS_BANCOS_HOMOLOGADOS { get; set; }
        public virtual ICollection<SW_OCORRENCIAS_BANCARIAS> SW_OCORRENCIAS_BANCARIAS { get; set; }
    }
}