// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class SW_CLASSIF_ESTABELECIMENTO_SPED
    {
        public SW_CLASSIF_ESTABELECIMENTO_SPED()
        {
            GE_PARAMETROS_SPED = new HashSet<GE_PARAMETROS_SPED>();
        }

        public int COD_CLASSIFICACAO { get; set; }
        public string DES_CLASSIFICACAO { get; set; } = null!;
        public string COD_SPED { get; set; } = null!;

        public virtual ICollection<GE_PARAMETROS_SPED> GE_PARAMETROS_SPED { get; set; }
    }
}