// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class SW_CST_ICMS
    {
        public SW_CST_ICMS()
        {
            GE_OPERACAO_FISCAL = new HashSet<GE_OPERACAO_FISCAL>();
        }

        public string NUM_CST_ICMS { get; set; } = null!;
        public string DES_CST_ICMS { get; set; } = null!;
        public bool? TIP_SIMPLES_NACIONAL { get; set; }

        public virtual ICollection<GE_OPERACAO_FISCAL> GE_OPERACAO_FISCAL { get; set; }
    }
}