// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class SW_COMPOSICAO_LISTA_PRECOS
    {
        public SW_COMPOSICAO_LISTA_PRECOS()
        {
            GE_LISTA_PRECOS_PRODUTOS = new HashSet<GE_LISTA_PRECOS_PRODUTOS>();
        }

        public int COD_COMPOSICAO { get; set; }
        public string? DES_COMPOSICAO { get; set; }

        public virtual ICollection<GE_LISTA_PRECOS_PRODUTOS> GE_LISTA_PRECOS_PRODUTOS { get; set; }
    }
}