// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class SW_CEST
    {
        public SW_CEST()
        {
            GE_CLASSIFICACAO_FISCAL = new HashSet<GE_CLASSIFICACAO_FISCAL>();
        }

        public string COD_CEST { get; set; } = null!;
        public string? DES_CEST { get; set; }

        public virtual ICollection<GE_CLASSIFICACAO_FISCAL> GE_CLASSIFICACAO_FISCAL { get; set; }
    }
}