// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class SW_CTE_SITUACAO_DOCUMENTO
    {
        public SW_CTE_SITUACAO_DOCUMENTO()
        {
            CE_NOTAS = new HashSet<CE_NOTAS>();
        }

        public int COD_SITUACAO { get; set; }
        public string? COD_SEFAZ { get; set; }
        public string? DES_SITUACAO { get; set; }
        public bool? TIP_NOTA_ENTRADA { get; set; }

        public virtual ICollection<CE_NOTAS> CE_NOTAS { get; set; }
    }
}