// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class SW_CLIENTES_PEDIDOS_TRAY
    {
        public SW_CLIENTES_PEDIDOS_TRAY()
        {
            SW_PEDIDOS_TRAY = new HashSet<SW_PEDIDOS_TRAY>();
        }

        public int COD_CLIENTE_PEDIDO { get; set; }
        public int COD_CLIENTE_TRAY { get; set; }
        public int COD_PEDIDO_TRAY { get; set; }
        public string? DES_NOME { get; set; }
        public string? NUM_RG { get; set; }
        public string? NUM_CPF { get; set; }
        public string? NUM_CNPJ { get; set; }
        public string? NUM_TELEFONE { get; set; }
        public string? NUM_CELULAR { get; set; }
        public string? DES_EMAIL { get; set; }
        public string? DES_NOME_EMPRESA { get; set; }
        public string? NUM_CEP { get; set; }
        public string? DES_ENDERECO { get; set; }
        public string? DES_COMPLEMENTO { get; set; }
        public string? DES_NUMERO { get; set; }
        public string? DES_CIDADE { get; set; }
        public string? DES_UF { get; set; }
        public string? DES_BAIRRO { get; set; }
        public int COD_EMPRESA { get; set; }

        public virtual GE_EMPRESAS COD_EMPRESANavigation { get; set; } = null!;
        public virtual ICollection<SW_PEDIDOS_TRAY> SW_PEDIDOS_TRAY { get; set; }
    }
}