// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class SW_CONTAS_DRE
    {
        public SW_CONTAS_DRE()
        {
            GE_CONTAS_CONTABEIS = new HashSet<GE_CONTAS_CONTABEIS>();
        }

        public int COD_CONTA_DRE { get; set; }
        public string DES_CONTA_DRE { get; set; } = null!;
        public int COD_CONTA_DRE_PAI { get; set; }

        public virtual ICollection<GE_CONTAS_CONTABEIS> GE_CONTAS_CONTABEIS { get; set; }
    }
}