// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class SW_CHAVES_UNICAS
    {
        public SW_CHAVES_UNICAS()
        {
            SW_ENTIDADES_ATRIBUTOS_CHAVE_UNICA = new HashSet<SW_ENTIDADES_ATRIBUTOS_CHAVE_UNICA>();
        }

        public int COD_CHAVE_UNICA { get; set; }
        public string DES_CHAVE_UNICA { get; set; } = null!;

        public virtual ICollection<SW_ENTIDADES_ATRIBUTOS_CHAVE_UNICA> SW_ENTIDADES_ATRIBUTOS_CHAVE_UNICA { get; set; }
    }
}