// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class SW_CNAE
    {
        public SW_CNAE()
        {
            GE_EMPRESAS = new HashSet<GE_EMPRESAS>();
        }

        public string COD_CNAE { get; set; } = null!;
        public string? DES_CNAE { get; set; }

        public virtual ICollection<GE_EMPRESAS> GE_EMPRESAS { get; set; }
    }
}