// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class SW_ENQUADRAMENTO_IPI
    {
        public SW_ENQUADRAMENTO_IPI()
        {
            GE_OPERACAO_FISCAL = new HashSet<GE_OPERACAO_FISCAL>();
        }

        public string COD_ENQUADRAMENTO_IPI { get; set; } = null!;
        public string DES_ENQUADRAMENTO_IPI { get; set; } = null!;

        public virtual ICollection<GE_OPERACAO_FISCAL> GE_OPERACAO_FISCAL { get; set; }
    }
}