// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class SW_EMAILS_ALERTAS_TRAY
    {
        public int COD_ALERTA { get; set; }
        public int COD_EMPRESA { get; set; }
        public string DES_DESCRICAO_EMAIL { get; set; } = null!;

        public virtual GE_EMPRESAS COD_EMPRESANavigation { get; set; } = null!;
    }
}