// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class SW_EMPRESAS_FILA_MANIFESTO
    {
        public int COD_FILA { get; set; }
        public string? DES_GUID { get; set; }
        public bool? TIP_VERIFICAR_AUTOMATICAMENTE_CONSULTA_MANIFESTO_DESTINARIO { get; set; }
        public bool? TIP_CONFIRMAR_OPERACAO_IMPORTAR_MANIFESTACAO_AUTOMATICA { get; set; }
    }
}