// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class SW_ERROS_APLICACAO
    {
        public long COD_ERRO { get; set; }
        public int? COD_ORGANIZACAO { get; set; }
        public int? COD_USUARIO { get; set; }
        public DateTime? DTA_ERRO { get; set; }
        public string? DES_ERRO { get; set; }
        public int? COD_EMPRESA { get; set; }
        public int? COD_FUNCAO { get; set; }

        public virtual GE_EMPRESAS? COD_EMPRESANavigation { get; set; }
        public virtual SW_FUNCOES? COD_FUNCAONavigation { get; set; }
        public virtual GE_ORGANIZACAO? COD_ORGANIZACAONavigation { get; set; }
        public virtual GE_USUARIOS? COD_USUARIONavigation { get; set; }
    }
}