// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class SW_ENTIDADES
    {
        public SW_ENTIDADES()
        {
            GE_ANEXOS = new HashSet<GE_ANEXOS>();
            GE_ANOTACOES = new HashSet<GE_ANOTACOES>();
            GE_COMENTARIOS = new HashSet<GE_COMENTARIOS>();
            GE_CONSULTAS_CONFIGURADAS = new HashSet<GE_CONSULTAS_CONFIGURADAS>();
            GE_ETIQUETAS = new HashSet<GE_ETIQUETAS>();
            SW_ENTIDADES_ATRIBUTOSCOD_ENTIDADENavigation = new HashSet<SW_ENTIDADES_ATRIBUTOS>();
            SW_ENTIDADES_ATRIBUTOSCOD_ENTIDADE_RELACIONADANavigation = new HashSet<SW_ENTIDADES_ATRIBUTOS>();
            SW_LOG_REGISTROS = new HashSet<SW_LOG_REGISTROS>();
            SW_PROCESSOS = new HashSet<SW_PROCESSOS>();
        }

        public int COD_ENTIDADE { get; set; }
        public string? DES_ENTIDADE_ORIGEM { get; set; }
        public string? DES_FANTASIA { get; set; }
        public string? DES_OBS { get; set; }
        public string? DES_ATRIBUTO_CHAVE_PRIMARIA { get; set; }
        public int? COD_ATRIBUTO_PADRAO { get; set; }
        public string? DES_ATRIBUTO_PADRAO { get; set; }
        public bool? TIP_GRAVAR_LOG { get; set; }
        public bool? TIP_BLOQUEAR_CONSULTA { get; set; }

        public virtual SW_ENTIDADES_ATRIBUTOS? COD_ATRIBUTO_PADRAONavigation { get; set; }
        public virtual ICollection<GE_ANEXOS> GE_ANEXOS { get; set; }
        public virtual ICollection<GE_ANOTACOES> GE_ANOTACOES { get; set; }
        public virtual ICollection<GE_COMENTARIOS> GE_COMENTARIOS { get; set; }
        public virtual ICollection<GE_CONSULTAS_CONFIGURADAS> GE_CONSULTAS_CONFIGURADAS { get; set; }
        public virtual ICollection<GE_ETIQUETAS> GE_ETIQUETAS { get; set; }
        public virtual ICollection<SW_ENTIDADES_ATRIBUTOS> SW_ENTIDADES_ATRIBUTOSCOD_ENTIDADENavigation { get; set; }
        public virtual ICollection<SW_ENTIDADES_ATRIBUTOS> SW_ENTIDADES_ATRIBUTOSCOD_ENTIDADE_RELACIONADANavigation { get; set; }
        public virtual ICollection<SW_LOG_REGISTROS> SW_LOG_REGISTROS { get; set; }
        public virtual ICollection<SW_PROCESSOS> SW_PROCESSOS { get; set; }
    }
}