// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class SW_ENTIDADES_ATRIBUTOS_CHAVE_UNICA
    {
        public int COD_ATRIBUTO_CHAVE_UNICA { get; set; }
        public int COD_ATRIBUTO { get; set; }
        public int COD_CHAVE_UNICA { get; set; }

        public virtual SW_ENTIDADES_ATRIBUTOS COD_ATRIBUTONavigation { get; set; } = null!;
        public virtual SW_CHAVES_UNICAS COD_CHAVE_UNICANavigation { get; set; } = null!;
    }
}