// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class SW_FUNCOES
    {
        public SW_FUNCOES()
        {
            GE_CONSULTAS_CONFIGURADAS = new HashSet<GE_CONSULTAS_CONFIGURADAS>();
            GE_FAVORITOS = new HashSet<GE_FAVORITOS>();
            GE_TIPOS_ALERTA = new HashSet<GE_TIPOS_ALERTA>();
            InverseCOD_FUNCAO_PAINavigation = new HashSet<SW_FUNCOES>();
            SW_ERROS_APLICACAO = new HashSet<SW_ERROS_APLICACAO>();
            SW_LOG_ACESSO_TELA = new HashSet<SW_LOG_ACESSO_TELA>();
            SW_MENU = new HashSet<SW_MENU>();
            SW_PERMISSOES_FUNCAO = new HashSet<SW_PERMISSOES_FUNCAO>();
            SW_PROCESSOS = new HashSet<SW_PROCESSOS>();
        }

        public int COD_FUNCAO { get; set; }
        public string? DES_NOME { get; set; }
        public string? DES_FANTASIA { get; set; }
        public string? DES_OBS { get; set; }
        public string? DES_NOME_RECURSO { get; set; }
        public int? COD_FUNCAO_PAI { get; set; }
        public string? DES_URL { get; set; }
        public int? COD_TIPO_FUNCAO { get; set; }
        public string? DES_IMAGEM { get; set; }
        public bool? TIP_FAVORITO { get; set; }
        public string? COD_TELA { get; set; }
        public bool? TIP_ESCONDER_NA_PESQUISA_DE_RECURSOS { get; set; }

        public virtual SW_FUNCOES? COD_FUNCAO_PAINavigation { get; set; }
        public virtual SW_TIPOS_FUNCAO? COD_TIPO_FUNCAONavigation { get; set; }
        public virtual ICollection<GE_CONSULTAS_CONFIGURADAS> GE_CONSULTAS_CONFIGURADAS { get; set; }
        public virtual ICollection<GE_FAVORITOS> GE_FAVORITOS { get; set; }
        public virtual ICollection<GE_TIPOS_ALERTA> GE_TIPOS_ALERTA { get; set; }
        public virtual ICollection<SW_FUNCOES> InverseCOD_FUNCAO_PAINavigation { get; set; }
        public virtual ICollection<SW_ERROS_APLICACAO> SW_ERROS_APLICACAO { get; set; }
        public virtual ICollection<SW_LOG_ACESSO_TELA> SW_LOG_ACESSO_TELA { get; set; }
        public virtual ICollection<SW_MENU> SW_MENU { get; set; }
        public virtual ICollection<SW_PERMISSOES_FUNCAO> SW_PERMISSOES_FUNCAO { get; set; }
        public virtual ICollection<SW_PROCESSOS> SW_PROCESSOS { get; set; }
    }
}