// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class SW_FINALIDADE_EMISSAO_NOTA
    {
        public SW_FINALIDADE_EMISSAO_NOTA()
        {
            FT_NOTAS = new HashSet<FT_NOTAS>();
        }

        public string COD_FINALIDADE_EMISSAO { get; set; } = null!;
        public string? DES_FINALIDADE_EMISSAO { get; set; }

        public virtual ICollection<FT_NOTAS> FT_NOTAS { get; set; }
    }
}