// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class SW_INTEGRADOR_BANCARIO
    {
        public SW_INTEGRADOR_BANCARIO()
        {
            GE_ORGANIZACAO = new HashSet<GE_ORGANIZACAO>();
            SW_INTEGRADORES_BANCARIOS_BANCOS_HOMOLOGADOS = new HashSet<SW_INTEGRADORES_BANCARIOS_BANCOS_HOMOLOGADOS>();
        }

        public int COD_INTEGRADOR_BANCARIO { get; set; }
        public string DES_INTEGRADOR { get; set; } = null!;

        public virtual ICollection<GE_ORGANIZACAO> GE_ORGANIZACAO { get; set; }
        public virtual ICollection<SW_INTEGRADORES_BANCARIOS_BANCOS_HOMOLOGADOS> SW_INTEGRADORES_BANCARIOS_BANCOS_HOMOLOGADOS { get; set; }
    }
}