// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class SW_LOG_ALTERACAO_TABELAS
    {
        public int COD_LOG_ALTERACAO_TABELAS { get; set; }
        public DateTime DTA_ALTERACAO { get; set; }
        public string DES_GUID { get; set; } = null!;
        public string DES_SCRIPT { get; set; } = null!;
    }
}