// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class SW_LOCAL_DESTINO_OPERACAO
    {
        public SW_LOCAL_DESTINO_OPERACAO()
        {
            FT_NOTAS = new HashSet<FT_NOTAS>();
            FT_PEDIDOS = new HashSet<FT_PEDIDOS>();
        }

        public string COD_LOCAL_DESTINO { get; set; } = null!;
        public string? DES_LOCAL_DESTINO { get; set; }

        public virtual ICollection<FT_NOTAS> FT_NOTAS { get; set; }
        public virtual ICollection<FT_PEDIDOS> FT_PEDIDOS { get; set; }
    }
}