// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class SW_LOG_REGISTROS
    {
        public int COD_LOG { get; set; }
        public int? COD_TRANSACAO { get; set; }
        public string? DES_TRANSACAO { get; set; }
        public int? COD_ACAO { get; set; }
        public string? DES_ACAO { get; set; }
        public int? COD_ORGANIZACAO { get; set; }
        public int? COD_EMPRESA { get; set; }
        public int? COD_USUARIO { get; set; }
        public int? COD_ENTIDADE { get; set; }
        public string? COD_REGISTRO { get; set; }
        public string? DES_ATRIBUTO_PADRAO { get; set; }
        public DateTime DTA_LOG { get; set; }
        public string? DES_LOG { get; set; }

        public virtual GE_EMPRESAS? COD_EMPRESANavigation { get; set; }
        public virtual SW_ENTIDADES? COD_ENTIDADENavigation { get; set; }
        public virtual GE_ORGANIZACAO? COD_ORGANIZACAONavigation { get; set; }
        public virtual GE_USUARIOS? COD_USUARIONavigation { get; set; }
    }
}