// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class SW_LINGUAGEM
    {
        public SW_LINGUAGEM()
        {
            GE_EMPRESAS = new HashSet<GE_EMPRESAS>();
            GE_USUARIOS = new HashSet<GE_USUARIOS>();
        }

        public int COD_LINGUAGEM { get; set; }
        public string? DES_FANTASIA { get; set; }
        public string? DES_CULTURA { get; set; }
        public string? DES_PAIS { get; set; }
        public string? DES_CULTURA_FANTASIA { get; set; }

        public virtual ICollection<GE_EMPRESAS> GE_EMPRESAS { get; set; }
        public virtual ICollection<GE_USUARIOS> GE_USUARIOS { get; set; }
    }
}