// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class SW_LOG_ACESSO
    {
        public int COD_LOG { get; set; }
        public DateTime? DTA_LOG { get; set; }
        public string? DES_LOGIN { get; set; }
        public string? DES_LOG { get; set; }
        public string? NUM_IP { get; set; }
        public string? DES_HOST { get; set; }
        public int? COD_ORGANIZACAO { get; set; }
    }
}