// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class SW_LOG_ATRIBUTOS
    {
        public int COD_LOG { get; set; }
        public DateTime DTA_LOG { get; set; }
        public int COD_ORGANIZACAO { get; set; }
        public int COD_ENTIDADE { get; set; }
        public int COD_ATRIBUTO { get; set; }
        public int COD_CHAVE_PRIMARIA { get; set; }
        public int? COD_ATIVIDADE_EXECUCAO { get; set; }
        public int COD_USUARIO { get; set; }
        public string? DES_VALOR_ANTERIOR { get; set; }
        public string? DES_VALOR_NOVO { get; set; }

        public virtual GE_ORGANIZACAO COD_ORGANIZACAONavigation { get; set; } = null!;
        public virtual GE_USUARIOS COD_USUARIONavigation { get; set; } = null!;
    }
}