// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class SW_LOG_ACESSO_TELA
    {
        public int COD_LOG { get; set; }
        public int? COD_FUNCAO { get; set; }
        public int? COD_USUARIO { get; set; }
        public DateTime? DTA_ACESSO { get; set; }

        public virtual SW_FUNCOES? COD_FUNCAONavigation { get; set; }
        public virtual GE_USUARIOS? COD_USUARIONavigation { get; set; }
    }
}