// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class SW_MENU
    {
        public SW_MENU()
        {
            InverseCOD_MENU_PAINavigation = new HashSet<SW_MENU>();
        }

        public int COD_MENU { get; set; }
        public string? DES_MENU { get; set; }
        public int? COD_MENU_PAI { get; set; }
        public int? COD_FUNCAO { get; set; }
        public string? DES_IMAGEM { get; set; }
        public int? NUM_ORDEM { get; set; }

        public virtual SW_FUNCOES? COD_FUNCAONavigation { get; set; }
        public virtual SW_MENU? COD_MENU_PAINavigation { get; set; }
        public virtual ICollection<SW_MENU> InverseCOD_MENU_PAINavigation { get; set; }
    }
}