// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class SW_MODELO_NOTA
    {
        public SW_MODELO_NOTA()
        {
            CE_NOTAS = new HashSet<CE_NOTAS>();
            FT_MDFE = new HashSet<FT_MDFE>();
            FT_NOTAS = new HashSet<FT_NOTAS>();
            FT_NOTAS_PEDIDOS_REFERENCIADAS = new HashSet<FT_NOTAS_PEDIDOS_REFERENCIADAS>();
            FT_NOTAS_REFERENCIADAS = new HashSet<FT_NOTAS_REFERENCIADAS>();
        }

        public string COD_MODELO_NOTA { get; set; } = null!;
        public string? DES_MODELO_NOTA { get; set; }
        public bool? TIP_PERMITE_REFERENCIAR { get; set; }

        public virtual ICollection<CE_NOTAS> CE_NOTAS { get; set; }
        public virtual ICollection<FT_MDFE> FT_MDFE { get; set; }
        public virtual ICollection<FT_NOTAS> FT_NOTAS { get; set; }
        public virtual ICollection<FT_NOTAS_PEDIDOS_REFERENCIADAS> FT_NOTAS_PEDIDOS_REFERENCIADAS { get; set; }
        public virtual ICollection<FT_NOTAS_REFERENCIADAS> FT_NOTAS_REFERENCIADAS { get; set; }
    }
}