// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class SW_MODELO_PEDIDO
    {
        public SW_MODELO_PEDIDO()
        {
            FT_PARAMETROS = new HashSet<FT_PARAMETROS>();
            GE_CONFIGURACAO_MODELO_PEDIDO = new HashSet<GE_CONFIGURACAO_MODELO_PEDIDO>();
        }

        public int COD_MODELO { get; set; }
        public string? DES_MODELO { get; set; }

        public virtual ICollection<FT_PARAMETROS> FT_PARAMETROS { get; set; }
        public virtual ICollection<GE_CONFIGURACAO_MODELO_PEDIDO> GE_CONFIGURACAO_MODELO_PEDIDO { get; set; }
    }
}