// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class SW_MODALIDADES_FRETE
    {
        public SW_MODALIDADES_FRETE()
        {
            CE_NOTAS = new HashSet<CE_NOTAS>();
            CO_ORDENS = new HashSet<CO_ORDENS>();
            FT_NOTAS = new HashSet<FT_NOTAS>();
            FT_PEDIDOS = new HashSet<FT_PEDIDOS>();
            PS_CLIENTES = new HashSet<PS_CLIENTES>();
        }

        public string COD_MODALIDADE_FRETE { get; set; } = null!;
        public string? DES_MODALIDADE_FRETE { get; set; }

        public virtual ICollection<CE_NOTAS> CE_NOTAS { get; set; }
        public virtual ICollection<CO_ORDENS> CO_ORDENS { get; set; }
        public virtual ICollection<FT_NOTAS> FT_NOTAS { get; set; }
        public virtual ICollection<FT_PEDIDOS> FT_PEDIDOS { get; set; }
        public virtual ICollection<PS_CLIENTES> PS_CLIENTES { get; set; }
    }
}