// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class SW_NATUREZA_FRETE_CTE
    {
        public SW_NATUREZA_FRETE_CTE()
        {
            CE_NOTAS_ITENS = new HashSet<CE_NOTAS_ITENS>();
        }

        public int COD_NATUREZA { get; set; }
        public string? COD_SEFAZ { get; set; }
        public string? DES_NATUREZA { get; set; }

        public virtual ICollection<CE_NOTAS_ITENS> CE_NOTAS_ITENS { get; set; }
    }
}