// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class SW_ORIGEM_PEDIDO
    {
        public SW_ORIGEM_PEDIDO()
        {
            FT_PEDIDOS = new HashSet<FT_PEDIDOS>();
        }

        public int COD_ORIGEM { get; set; }
        public string? DES_ORIGEM { get; set; }

        public virtual ICollection<FT_PEDIDOS> FT_PEDIDOS { get; set; }
    }
}