// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class SW_OPERADORAS_CARTAO_SEFAZ
    {
        public SW_OPERADORAS_CARTAO_SEFAZ()
        {
            GE_OPERADORAS_CARTAO = new HashSet<GE_OPERADORAS_CARTAO>();
        }

        public int COD_OPERADORA_SEFAZ { get; set; }
        public string? COD_SEFAZ { get; set; }
        public string? DES_OPERADORA_SEFAZ { get; set; }

        public virtual ICollection<GE_OPERADORAS_CARTAO> GE_OPERADORAS_CARTAO { get; set; }
    }
}