// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class SW_OCORRENCIAS_BANCARIAS
    {
        public SW_OCORRENCIAS_BANCARIAS()
        {
            CR_RETORNO_HISTORICO = new HashSet<CR_RETORNO_HISTORICO>();
        }

        public int COD_OCORRENCIA_BANCARIA { get; set; }
        public int COD_BANCO_HOMOLOGADO { get; set; }
        public string COD_OCORRENCIA { get; set; } = null!;
        public string DES_OCORRENCIA { get; set; } = null!;
        public bool TIP_LIQUIDA { get; set; }

        public virtual SW_BANCOS_HOMOLOGADOS COD_BANCO_HOMOLOGADONavigation { get; set; } = null!;
        public virtual ICollection<CR_RETORNO_HISTORICO> CR_RETORNO_HISTORICO { get; set; }
    }
}