// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class SW_ORIGEM_MERCADORIAS
    {
        public SW_ORIGEM_MERCADORIAS()
        {
            CE_PRODUTOS = new HashSet<CE_PRODUTOS>();
            FT_NOTAS_ITENS = new HashSet<FT_NOTAS_ITENS>();
            FT_PEDIDOS_ITENS = new HashSet<FT_PEDIDOS_ITENS>();
            GE_REGRAS_TRIBUTACAO = new HashSet<GE_REGRAS_TRIBUTACAO>();
        }

        public string COD_ORIGEM { get; set; } = null!;
        public string DES_ORIGEM { get; set; } = null!;

        public virtual ICollection<CE_PRODUTOS> CE_PRODUTOS { get; set; }
        public virtual ICollection<FT_NOTAS_ITENS> FT_NOTAS_ITENS { get; set; }
        public virtual ICollection<FT_PEDIDOS_ITENS> FT_PEDIDOS_ITENS { get; set; }
        public virtual ICollection<GE_REGRAS_TRIBUTACAO> GE_REGRAS_TRIBUTACAO { get; set; }
    }
}