// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class SW_PERMISSOES_USUARIO_PDV
    {
        public int COD_PERMISSAO_USUARIO { get; set; }
        public int COD_USUARIO { get; set; }
        public bool TIP_LIBERAR_MARGEM_MINIMA { get; set; }
    }
}