// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class SW_PEDIDOS_ISET
    {
        public SW_PEDIDOS_ISET()
        {
            SW_PAGAMENTOS_PEDIDOS_ISET = new HashSet<SW_PAGAMENTOS_PEDIDOS_ISET>();
            SW_PEDIDOS_ISET_ITENS = new HashSet<SW_PEDIDOS_ISET_ITENS>();
        }

        public int COD_PEDIDO_ISET { get; set; }
        public string DES_STATUS { get; set; } = null!;
        public DateTime DTA_PEDIDO { get; set; }
        public int? COD_CLIENTE_ISET { get; set; }
        public decimal? VLR_FRETE { get; set; }
        public decimal? VLR_TOTAL { get; set; }
        public int? COD_PEDIDO_MABOO { get; set; }
        public string? DES_LOG_ERRO { get; set; }
        public string? DES_ORIGEM { get; set; }
        public int? NUM_PARCELAS_PEDIDO { get; set; }
        public string? DES_JSON { get; set; }
        public string? DES_FORMA_PAGAMENTO { get; set; }
        public string? DES_COD_RASTREIO { get; set; }
        public int COD_EMPRESA { get; set; }
        public DateTime? DTA_ESTIMADA_ENTREGA { get; set; }

        public virtual SW_CLIENTES_PEDIDOS_ISET? COD_CLIENTE_ISETNavigation { get; set; }
        public virtual GE_EMPRESAS COD_EMPRESANavigation { get; set; } = null!;
        public virtual FT_PEDIDOS? COD_PEDIDO_MABOONavigation { get; set; }
        public virtual ICollection<SW_PAGAMENTOS_PEDIDOS_ISET> SW_PAGAMENTOS_PEDIDOS_ISET { get; set; }
        public virtual ICollection<SW_PEDIDOS_ISET_ITENS> SW_PEDIDOS_ISET_ITENS { get; set; }
    }
}