// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class SW_PROCESSOS_FIFO
    {
        public int COD_FIFO { get; set; }
        public DateTime? DTA_FIFO { get; set; }
        public string? DES_HASH { get; set; }
        public int? COD_EMPRESA { get; set; }
        public int? IND_PROCESSO { get; set; }

        public virtual GE_EMPRESAS? COD_EMPRESANavigation { get; set; }
    }
}