// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class SW_PEDIDOS_ISET_ITENS
    {
        public int COD_PEDIDO_ITEM { get; set; }
        public int COD_PEDIDO_ISET { get; set; }
        public int COD_PRODUTO_ISET { get; set; }
        public string? DES_PRODUTO_ISET { get; set; }
        public decimal? VLR_PRECO { get; set; }
        public decimal? VLR_PESO { get; set; }
        public decimal? QTD_PRODUTO { get; set; }
        public decimal? VLR_DESCONTO { get; set; }
        public int COD_EMPRESA { get; set; }
        public string? DES_COD_VARIACAO { get; set; }

        public virtual GE_EMPRESAS COD_EMPRESANavigation { get; set; } = null!;
        public virtual SW_PEDIDOS_ISET COD_PEDIDO_ISETNavigation { get; set; } = null!;
    }
}