// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class SW_PROCESSOS
    {
        public SW_PROCESSOS()
        {
            GE_CONTA_EMAIL_PROCESSOS = new HashSet<GE_CONTA_EMAIL_PROCESSOS>();
            GE_EMAILS_ENVIADOS = new HashSet<GE_EMAILS_ENVIADOS>();
            InverseCOD_PROCESSO_PAINavigation = new HashSet<SW_PROCESSOS>();
            PS_CONTATOS_PROCESSOS = new HashSet<PS_CONTATOS_PROCESSOS>();
        }

        public int COD_PROCESSO { get; set; }
        public string DES_PROCESSO { get; set; } = null!;
        public int? COD_ENTIDADE { get; set; }
        public int? COD_PROCESSO_PAI { get; set; }
        public int? COD_FUNCAO { get; set; }
        public int? IND_PROCESSO { get; set; }

        public virtual SW_ENTIDADES? COD_ENTIDADENavigation { get; set; }
        public virtual SW_FUNCOES? COD_FUNCAONavigation { get; set; }
        public virtual SW_PROCESSOS? COD_PROCESSO_PAINavigation { get; set; }
        public virtual ICollection<GE_CONTA_EMAIL_PROCESSOS> GE_CONTA_EMAIL_PROCESSOS { get; set; }
        public virtual ICollection<GE_EMAILS_ENVIADOS> GE_EMAILS_ENVIADOS { get; set; }
        public virtual ICollection<SW_PROCESSOS> InverseCOD_PROCESSO_PAINavigation { get; set; }
        public virtual ICollection<PS_CONTATOS_PROCESSOS> PS_CONTATOS_PROCESSOS { get; set; }
    }
}