// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class SW_PERMISSOES_FUNCAO
    {
        public int COD_PERMISSAO_FUNCAO { get; set; }
        public int COD_ORGANIZACAO { get; set; }
        public int COD_FUNCAO { get; set; }
        public int COD_TIPO_AGRUPAMENTO { get; set; }
        public bool TIP_PERMITE { get; set; }
        public string? COD_CHAVE { get; set; }

        public virtual SW_FUNCOES COD_FUNCAONavigation { get; set; } = null!;
        public virtual GE_ORGANIZACAO COD_ORGANIZACAONavigation { get; set; } = null!;
        public virtual SW_TIPOS_AGRUPAMENTO COD_TIPO_AGRUPAMENTONavigation { get; set; } = null!;
    }
}