// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class SW_PAGAMENTOS_PEDIDOS_TRAY
    {
        public int COD_PAGAMENTO_TRAY { get; set; }
        public DateTime? DTA_CRIACAO { get; set; }
        public DateTime? DTA_MODIFICACAO { get; set; }
        public int? COD_PAGAMENTO { get; set; }
        public string? DES_FORMA_PAGAMENTO { get; set; }
        public string? DES_LOCAL_PAGAMENTO { get; set; }
        public int COD_PEDIDO_TRAY { get; set; }
        public decimal? VLR_PAGAMENTO { get; set; }
        public DateTime? DTA_PAGAMENTO { get; set; }
        public string? DES_OBS_PAGAMENTO { get; set; }
        public int COD_EMPRESA { get; set; }

        public virtual GE_EMPRESAS COD_EMPRESANavigation { get; set; } = null!;
        public virtual SW_PEDIDOS_TRAY COD_PEDIDO_TRAYNavigation { get; set; } = null!;
    }
}