// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class SW_PEDIDOS_TRAY
    {
        public SW_PEDIDOS_TRAY()
        {
            SW_PAGAMENTOS_PEDIDOS_TRAY = new HashSet<SW_PAGAMENTOS_PEDIDOS_TRAY>();
            SW_PEDIDOS_TRAY_ITENS = new HashSet<SW_PEDIDOS_TRAY_ITENS>();
        }

        public int COD_PEDIDO_TRAY { get; set; }
        public string? DES_STATUS { get; set; }
        public DateTime? DTA_PEDIDO { get; set; }
        public int? COD_CLIENTE_TRAY { get; set; }
        public decimal? VLR_PARCIAL { get; set; }
        public decimal? VLR_TAXAS { get; set; }
        public decimal? VLR_DESCONTO { get; set; }
        public decimal? VLR_FRETE { get; set; }
        public DateTime? DTA_ENVIO_PEDIDO { get; set; }
        public decimal? VLR_DESCONTO_CUPOM { get; set; }
        public decimal? VLR_TOTAL { get; set; }
        public DateTime? DTA_ESTIMADA_ENTREGA { get; set; }
        public int? COD_PEDIDO_MABOO { get; set; }
        public int? COD_REPRESENTANTE { get; set; }
        public string? DES_LOG_ERRO { get; set; }
        public int? COD_PAGAMENTO { get; set; }
        public string? DES_ORIGEM { get; set; }
        public int? NUM_PARCELAS_PEDIDO { get; set; }
        public int? COD_TRANSPORTADORA { get; set; }
        public string DES_JSON { get; set; } = null!;
        public int COD_EMPRESA { get; set; }
        public string? DES_FORMA_PAGAMENTO { get; set; }
        public string? DES_CODIGO_RASTREIO { get; set; }
        public bool? TIP_ERRO_INTEGRACAO_AUTOMATICA { get; set; }
        public bool? TIP_ENVIADO_DADOS_RASTREAMENTO { get; set; }

        public virtual SW_CLIENTES_PEDIDOS_TRAY? COD_CLIENTE_TRAYNavigation { get; set; }
        public virtual GE_EMPRESAS COD_EMPRESANavigation { get; set; } = null!;
        public virtual FT_PEDIDOS? COD_PEDIDO_MABOONavigation { get; set; }
        public virtual ICollection<SW_PAGAMENTOS_PEDIDOS_TRAY> SW_PAGAMENTOS_PEDIDOS_TRAY { get; set; }
        public virtual ICollection<SW_PEDIDOS_TRAY_ITENS> SW_PEDIDOS_TRAY_ITENS { get; set; }
    }
}