// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class SW_RELACAO_PAGAMENTO_TRAY
    {
        public int COD_RELACAO { get; set; }
        public int COD_PAGAMENTO_TRAY { get; set; }
        public int COD_PAGAMENTO { get; set; }
        public int COD_EMPRESA { get; set; }
        public string? DES_PAGAMENTO_TRAY { get; set; }

        public virtual GE_EMPRESAS COD_EMPRESANavigation { get; set; } = null!;
        public virtual GE_CONDICAO_PAGAMENTO COD_PAGAMENTONavigation { get; set; } = null!;
    }
}