// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class SW_STATUS_ORDENS
    {
        public SW_STATUS_ORDENS()
        {
            CO_LOGS_STATUS_ORDENS = new HashSet<CO_LOGS_STATUS_ORDENS>();
            CO_ORDENS = new HashSet<CO_ORDENS>();
            CO_PARAMETROSCOD_STATUS_FINALNavigation = new HashSet<CO_PARAMETROS>();
            CO_PARAMETROSCOD_STATUS_INICIALNavigation = new HashSet<CO_PARAMETROS>();
            CO_STATUS_CONFIGURACOES = new HashSet<CO_STATUS_CONFIGURACOES>();
        }

        public int COD_STATUS { get; set; }
        public string? DES_STATUS { get; set; }
        public string? DES_COR { get; set; }

        public virtual ICollection<CO_LOGS_STATUS_ORDENS> CO_LOGS_STATUS_ORDENS { get; set; }
        public virtual ICollection<CO_ORDENS> CO_ORDENS { get; set; }
        public virtual ICollection<CO_PARAMETROS> CO_PARAMETROSCOD_STATUS_FINALNavigation { get; set; }
        public virtual ICollection<CO_PARAMETROS> CO_PARAMETROSCOD_STATUS_INICIALNavigation { get; set; }
        public virtual ICollection<CO_STATUS_CONFIGURACOES> CO_STATUS_CONFIGURACOES { get; set; }
    }
}