// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class SW_STATUS_PEDIDO
    {
        public SW_STATUS_PEDIDO()
        {
            FT_PEDIDOS = new HashSet<FT_PEDIDOS>();
        }

        public int COD_STATUS { get; set; }
        public string? DES_STATUS { get; set; }

        public virtual ICollection<FT_PEDIDOS> FT_PEDIDOS { get; set; }
    }
}