// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class SW_TIPO_SERVICO
    {
        public SW_TIPO_SERVICO()
        {
            CE_PRODUTOS = new HashSet<CE_PRODUTOS>();
        }

        public string COD_TIPO_SERVICO { get; set; } = null!;
        public string? DES_TIPO_SERVIVO { get; set; }
        public string COD_SERVICO_LC { get; set; } = null!;

        public virtual ICollection<CE_PRODUTOS> CE_PRODUTOS { get; set; }
    }
}