// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class SW_TIPO_GENERO
    {
        public SW_TIPO_GENERO()
        {
            CE_PRODUTOS = new HashSet<CE_PRODUTOS>();
        }

        public int COD_GENERO { get; set; }
        public string COD_SPED { get; set; } = null!;
        public string DES_GENERO { get; set; } = null!;

        public virtual ICollection<CE_PRODUTOS> CE_PRODUTOS { get; set; }
    }
}