// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class SW_TIPOS_DOCUMENTOS
    {
        public SW_TIPOS_DOCUMENTOS()
        {
            CE_MOVIMENTOS_ESTOQUES = new HashSet<CE_MOVIMENTOS_ESTOQUES>();
        }

        public int COD_TIPO_DOCUMENTO { get; set; }
        public string? DES_TIPO_DOCUMENTO { get; set; }

        public virtual ICollection<CE_MOVIMENTOS_ESTOQUES> CE_MOVIMENTOS_ESTOQUES { get; set; }
    }
}