// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class SW_TIPOS_BARRAS
    {
        public SW_TIPOS_BARRAS()
        {
            CE_PRODUTO_BARRAS = new HashSet<CE_PRODUTO_BARRAS>();
        }

        public int COD_TIPO_BARRA { get; set; }
        public string? DES_TIPO_BARRA { get; set; }

        public virtual ICollection<CE_PRODUTO_BARRAS> CE_PRODUTO_BARRAS { get; set; }
    }
}