// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class SW_TIPO_CERTIFICADO
    {
        public SW_TIPO_CERTIFICADO()
        {
            GE_CERTIFICADO_DIGITAL = new HashSet<GE_CERTIFICADO_DIGITAL>();
        }

        public int COD_TIPO { get; set; }
        public string DES_NOME { get; set; } = null!;

        public virtual ICollection<GE_CERTIFICADO_DIGITAL> GE_CERTIFICADO_DIGITAL { get; set; }
    }
}