// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class SW_TIPO_DE_CONSULTAS
    {
        public SW_TIPO_DE_CONSULTAS()
        {
            GE_CONSULTAS = new HashSet<GE_CONSULTAS>();
        }

        public int COD_TIPO { get; set; }
        public string? DES_TIPO { get; set; }

        public virtual ICollection<GE_CONSULTAS> GE_CONSULTAS { get; set; }
    }
}