// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class SW_TIPO_ITEM_SPED
    {
        public SW_TIPO_ITEM_SPED()
        {
            CE_PRODUTOS = new HashSet<CE_PRODUTOS>();
        }

        public string COD_TIPO_ITEM { get; set; } = null!;
        public string? DES_TIPO_ITEM { get; set; }

        public virtual ICollection<CE_PRODUTOS> CE_PRODUTOS { get; set; }
    }
}