// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class SW_TIPO_RODADO
    {
        public SW_TIPO_RODADO()
        {
            FT_MDFE = new HashSet<FT_MDFE>();
        }

        public string COD_TIPO_RODADO { get; set; } = null!;
        public string? DES_TIPO_RODADO { get; set; }

        public virtual ICollection<FT_MDFE> FT_MDFE { get; set; }
    }
}