// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class SW_TIPO_MENSAGENS
    {
        public SW_TIPO_MENSAGENS()
        {
            GE_MENSAGEM_PADRAO = new HashSet<GE_MENSAGEM_PADRAO>();
        }

        public int COD_TIPO { get; set; }
        public string? DES_TIPO { get; set; }

        public virtual ICollection<GE_MENSAGEM_PADRAO> GE_MENSAGEM_PADRAO { get; set; }
    }
}