// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class SW_TIPOS_ALERTAS_PROCESSOS
    {
        public SW_TIPOS_ALERTAS_PROCESSOS()
        {
            GE_ALERTAS_PROCESSOS = new HashSet<GE_ALERTAS_PROCESSOS>();
        }

        public int COD_TIPO_ALERTA { get; set; }
        public string? DES_TIPO_ALERTA { get; set; }

        public virtual ICollection<GE_ALERTAS_PROCESSOS> GE_ALERTAS_PROCESSOS { get; set; }
    }
}