// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class SW_TIPOS_NOTAS
    {
        public SW_TIPOS_NOTAS()
        {
            FT_NOTAS = new HashSet<FT_NOTAS>();
        }

        public int COD_TIPO_NOTA { get; set; }
        public string? DES_TIPO_NOTA { get; set; }

        public virtual ICollection<FT_NOTAS> FT_NOTAS { get; set; }
    }
}