// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class SW_TIPO_TRANSPORTADOR
    {
        public SW_TIPO_TRANSPORTADOR()
        {
            FT_MDFE = new HashSet<FT_MDFE>();
        }

        public int COD_TIPO_TRANSPORTADOR { get; set; }
        public string? DES_TIPO_TRANSPORTADOR { get; set; }

        public virtual ICollection<FT_MDFE> FT_MDFE { get; set; }
    }
}