// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class SW_TIPOS_REGRAS_ORDENS
    {
        public SW_TIPOS_REGRAS_ORDENS()
        {
            CO_REGRAS_APROVADORES = new HashSet<CO_REGRAS_APROVADORES>();
        }

        public int COD_TIPO { get; set; }
        public string? DES_TIPO { get; set; }

        public virtual ICollection<CO_REGRAS_APROVADORES> CO_REGRAS_APROVADORES { get; set; }
    }
}