// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class SW_TIPO_CARROCERIA
    {
        public SW_TIPO_CARROCERIA()
        {
            FT_MDFE = new HashSet<FT_MDFE>();
            FT_MDFE_REBOQUE = new HashSet<FT_MDFE_REBOQUE>();
        }

        public string COD_TIPO_CARROCERIA { get; set; } = null!;
        public string? DES_TIPO_CARROCERIA { get; set; }

        public virtual ICollection<FT_MDFE> FT_MDFE { get; set; }
        public virtual ICollection<FT_MDFE_REBOQUE> FT_MDFE_REBOQUE { get; set; }
    }
}