// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class SW_TIPO_COMPONENTES
    {
        public SW_TIPO_COMPONENTES()
        {
            GE_COMPONENTES_DASHBOARD = new HashSet<GE_COMPONENTES_DASHBOARD>();
        }

        public int COD_TIPO { get; set; }
        public string DES_TIPO { get; set; } = null!;

        public virtual ICollection<GE_COMPONENTES_DASHBOARD> GE_COMPONENTES_DASHBOARD { get; set; }
    }
}