// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class SW_UF
    {
        public SW_UF()
        {
            CE_NOTAS = new HashSet<CE_NOTAS>();
            FT_MDFECOD_UF_CARREGAMENTONavigation = new HashSet<FT_MDFE>();
            FT_MDFECOD_UF_DESCARREGAMENTONavigation = new HashSet<FT_MDFE>();
            FT_MDFECOD_UF_LICENCIADONavigation = new HashSet<FT_MDFE>();
            FT_MDFECOD_UF_PROPRIETARIO_VEICULONavigation = new HashSet<FT_MDFE>();
            FT_MDFE_PERCURSO = new HashSet<FT_MDFE_PERCURSO>();
            FT_MDFE_REBOQUECOD_UF_LICENCIAMENTO_REBOQUENavigation = new HashSet<FT_MDFE_REBOQUE>();
            FT_MDFE_REBOQUECOD_UF_PROPRIETARIO_REBOQUENavigation = new HashSet<FT_MDFE_REBOQUE>();
            FT_NOTASCOD_IBGE_UFNavigation = new HashSet<FT_NOTAS>();
            FT_NOTASCOD_UF_EMBARQUENavigation = new HashSet<FT_NOTAS>();
            FT_NOTAS_ITENS_IMPORTACAOCOD_UF_ADQUIRENTENavigation = new HashSet<FT_NOTAS_ITENS_IMPORTACAO>();
            FT_NOTAS_ITENS_IMPORTACAOCOD_UF_DESEMBARACONavigation = new HashSet<FT_NOTAS_ITENS_IMPORTACAO>();
            FT_NOTAS_PEDIDOS_REFERENCIADAS = new HashSet<FT_NOTAS_PEDIDOS_REFERENCIADAS>();
            FT_NOTAS_REFERENCIADAS = new HashSet<FT_NOTAS_REFERENCIADAS>();
            FT_PEDIDOS = new HashSet<FT_PEDIDOS>();
            GE_CIDADES = new HashSet<GE_CIDADES>();
            GE_EMPRESAS_UF = new HashSet<GE_EMPRESAS_UF>();
            GE_PROPRIETARIO_VEICULOS = new HashSet<GE_PROPRIETARIO_VEICULOS>();
            GE_REGRAS_TRIBUTACAO = new HashSet<GE_REGRAS_TRIBUTACAO>();
            GE_RELACOES_LISTAS_PRECOS = new HashSet<GE_RELACOES_LISTAS_PRECOS>();
        }

        public int COD_IBGE_UF { get; set; }
        public string? DES_ABREVIATURA { get; set; }
        public string? DES_UF { get; set; }
        public decimal? PER_ICMS_INTERNO { get; set; }
        public int? IND_CALCULO_DIFAL { get; set; }
        public decimal? PER_FUNDO_COMBATE_POBREZA { get; set; }
        public decimal? PER_ICMS { get; set; }

        public virtual ICollection<CE_NOTAS> CE_NOTAS { get; set; }
        public virtual ICollection<FT_MDFE> FT_MDFECOD_UF_CARREGAMENTONavigation { get; set; }
        public virtual ICollection<FT_MDFE> FT_MDFECOD_UF_DESCARREGAMENTONavigation { get; set; }
        public virtual ICollection<FT_MDFE> FT_MDFECOD_UF_LICENCIADONavigation { get; set; }
        public virtual ICollection<FT_MDFE> FT_MDFECOD_UF_PROPRIETARIO_VEICULONavigation { get; set; }
        public virtual ICollection<FT_MDFE_PERCURSO> FT_MDFE_PERCURSO { get; set; }
        public virtual ICollection<FT_MDFE_REBOQUE> FT_MDFE_REBOQUECOD_UF_LICENCIAMENTO_REBOQUENavigation { get; set; }
        public virtual ICollection<FT_MDFE_REBOQUE> FT_MDFE_REBOQUECOD_UF_PROPRIETARIO_REBOQUENavigation { get; set; }
        public virtual ICollection<FT_NOTAS> FT_NOTASCOD_IBGE_UFNavigation { get; set; }
        public virtual ICollection<FT_NOTAS> FT_NOTASCOD_UF_EMBARQUENavigation { get; set; }
        public virtual ICollection<FT_NOTAS_ITENS_IMPORTACAO> FT_NOTAS_ITENS_IMPORTACAOCOD_UF_ADQUIRENTENavigation { get; set; }
        public virtual ICollection<FT_NOTAS_ITENS_IMPORTACAO> FT_NOTAS_ITENS_IMPORTACAOCOD_UF_DESEMBARACONavigation { get; set; }
        public virtual ICollection<FT_NOTAS_PEDIDOS_REFERENCIADAS> FT_NOTAS_PEDIDOS_REFERENCIADAS { get; set; }
        public virtual ICollection<FT_NOTAS_REFERENCIADAS> FT_NOTAS_REFERENCIADAS { get; set; }
        public virtual ICollection<FT_PEDIDOS> FT_PEDIDOS { get; set; }
        public virtual ICollection<GE_CIDADES> GE_CIDADES { get; set; }
        public virtual ICollection<GE_EMPRESAS_UF> GE_EMPRESAS_UF { get; set; }
        public virtual ICollection<GE_PROPRIETARIO_VEICULOS> GE_PROPRIETARIO_VEICULOS { get; set; }
        public virtual ICollection<GE_REGRAS_TRIBUTACAO> GE_REGRAS_TRIBUTACAO { get; set; }
        public virtual ICollection<GE_RELACOES_LISTAS_PRECOS> GE_RELACOES_LISTAS_PRECOS { get; set; }
    }
}