// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class SW_USUARIOS_LOGADOS
    {
        public int COD_CONTROLE { get; set; }
        public int COD_USUARIO { get; set; }
        public string DES_GUID_ACCOUNT { get; set; } = null!;
        public DateTime DTA_LOGIN { get; set; }
        public int COD_EMPRESA { get; set; }

        public virtual GE_EMPRESAS COD_EMPRESANavigation { get; set; } = null!;
        public virtual GE_USUARIOS COD_USUARIONavigation { get; set; } = null!;
    }
}