// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class SW_VIA_TRANSPORTE
    {
        public SW_VIA_TRANSPORTE()
        {
            FT_NOTAS_ITENS_IMPORTACAO = new HashSet<FT_NOTAS_ITENS_IMPORTACAO>();
        }

        public int COD_VIA_TRANSPORTE { get; set; }
        public string? DES_VIA_TRANSPORTE { get; set; }
        public string? COD_VIA_TRANSPORTE_SEFAZ { get; set; }

        public virtual ICollection<FT_NOTAS_ITENS_IMPORTACAO> FT_NOTAS_ITENS_IMPORTACAO { get; set; }
    }
}