// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class SW_VERSAO_DE_SISTEMA
    {
        public int COD_VERSAO { get; set; }
        public string DES_VERSAO { get; set; } = null!;
        public DateTime DTA_ATUALIZACAO { get; set; }
        public string DES_LINK_DA_RELEASE { get; set; } = null!;
    }
}