// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Relatorios.Dominio.Entities.Entities
{
    public partial class SW_VERSOES_SPED_FISCAL
    {
        public int COD_VERSAO { get; set; }
        public string? COD_VERSAO_LAYOUT { get; set; }
        public string? DES_VERSAO_LAYOUT { get; set; }
        public DateTime? DTA_INICIO { get; set; }
        public DateTime? DTA_FIM { get; set; }
    }
}